<?php
return array(

	'time_out_warning' => '請先登錄再進行操作',
	
	
	'menu_sup_org' => '組織管理',
	'menu_sup_set' => '系統工具',
	'menu_sup_ext' => '擴展功能',
	'menu_sup_report' => '查詢統計',
	'menu_sup_doc' => '文檔管理',
	'menu_sup_syncpush' => '數據推送',
	'menu_sup_platform' => '開放平臺', 
	'menu_sup_duty' => '在線值班',
	
	
	'menu_sub_org' => '組織管理',
	'menu_sub_user' => '人員管理',
	'menu_sub_role' => '角色管理',
	'menu_sub_grant' => '授權管理',
	'menu_sub_group' => '群組管理',
	'menu_sub_pos' => '銘牌管理',
	'menu_sub_tag' => '標簽管理',
	
	
	'menu_sub_service' => '服務控制',
	'menu_sub_set' => '系統設置',
	'menu_sub_webserver' => '後臺設置',
	'menu_sub_update' => '升級管理 ',
	'menu_sub_hl' => '單位互聯',
	'menu_sub_skin' => '皮膚管理',
	'menu_sub_server' => '服務器管理',
	'menu_sub_change' => '遷移管理',
	  
	'menu_sub_addin' => '插件管理',
	'menu_sub_interface' => '接口管理',
	'menu_sub_ext' => '擴展設置',
	'menu_sub_filter' => '敏感詞過濾', //'敏感词过滤'
	'menu_sub_client' => '程序發布',
	'menu_sub_config_fh' => '集成配置',
	'menu_sub_sms_account' => '短信帳號',
	
	'menu_sub_msg' => '私聊消息查詢',
	'menu_sub_chatlist' => '私聊查詢',
	'menu_sub_groupmsg' => '群聊消息查詢',
	'menu_sub_groupchatlist' => '群聊查詢',
	'menu_sub_livechatmsg' => '客服消息查詢',
	'menu_sub_livechatlist' => '客服查詢',
	'menu_sub_groupkefumsg' => '客服群聊消息查詢',
    'menu_sub_groupkefuchatlist' => '客服群聊查詢',
	'menu_sub_attach' => '附件查詢',
	'menu_sub_msgtotal' => '消息統計',
	'menu_sub_online' => '在線用戶',
	'menu_sub_board' => '公告信息',
	'menu_sub_log' => '登錄日誌',
	'menu_sub_sms' => '短信統計',
	'menu_sub_recsms' => '短信接收',
	'menu_sub_orgreport' => '組織統計',
	'menu_sub_livechat_msg' => '客服消息',
	'menu_sub_public_file' => '公共文檔',
	'menu_sub_person_file' => '個人文檔',
	'menu_sub_group_file' => '群組文件',
	'menu_sub_leave_file' => '離線文件',
	
	'menu_sub_config' => '文檔配置',
	'menu_sub_store' => '文檔存儲',
	'menu_sub_doclog' => '文檔日誌',
	
	'menu_sub_syncpush_set' => '推送設置',
	'menu_sub_syncpush_org' => '推送組織',
	'menu_sub_syncpush_log' => '推送日誌',
	
	'menu_sup_platform_app' => '應用管理', 
	'menu_sup_platform_token' => '令牌查看', 
	
	'menu_sub_operator' => '客服管理',
	'menu_sub_entrance' => '入口管理',
	'menu_sub_dialog_analysis' => '會話分析',
	'menu_sub_dialog' => '會話管理',
	'menu_sub_message' => '留言管理',
	'menu_sub_livemsg' => '留言查詢',
	'menu_sub_rate' => '評價管理',
	'menu_sub_transfer' => '轉接記錄',
	'menu_sub_blackip' => '黑名單ip記錄',
	'menu_sub_attachment' => '附件管理',
	'menu_sub_dialog_theme' => '會話主題管理',
	'menu_sub_visitor_label' => '訪客標籤管理',
	'menu_sub_visitor' => '訪客管理',
	'menu_sub_link' => '鏈接管理',
	'menu_sub_quicktalk' => '常用語管理',
	'menu_sub_question' => '問答庫',
	'menu_sub_config_lv' => '客服配置',
	'menu_sub_domain' => '域名管理',
	'menu_sub_wechat' => '公眾號/小程式管理',

	'menu_sub_permission' => '授權管理',
	
	'btn_reset_viewid' => '重置人員關系',
	'btn_autocreate' => '自動創建',
	'btn_set' => '設置',
	'btn_login' => '登錄',
	'btn_change' => '修改',
	'btn_save' => '保存',
	'btn_cancel' => '取消',
	'btn_back' => '返回',
	'btn_add' => '新增',
	'btn_edit' => '編輯',
	'btn_delete' => '刪除',
	'btn_clear' => '清空',
	'btn_ok' => '確定',
	'btn_reg' => '註冊',
	'btn_close' => '關閉',
	'btn_import' => '導入',
	'btn_export' => '導出',
	'btn_active' => '激活',
	'btn_adddept' => '新增部門',
	'btn_opdept' => '部門操作',
	'btn_editdept' => '編輯部門',
	'btn_deldept' => '刪除部門',
	'btn_movedept' => '移動部門',
	'btn_adduser' => '新增人員',
	'btn_edituser' => '編輯人員',
	'btn_opuser' => '人員操作',
	'btn_setattr' => '設置屬性',
	'btn_setdept' => '設置部門',
	'btn_setpos' => '設置銘牌',
	'btn_removeuser' => '從部門移出',
	'btn_deluser' => '刪除人員',
	'btn_batchop' => '批量操作',
	'btn_impuser' => '導入用戶',
	'btn_impdept' => '導入部門',
	'btn_impldap' => '導入域用戶',
	'btn_imprtx' => '導入rtx用戶',
	'btn_expuser' => '導出用戶',
	'btn_expdept' => '導出部門',
	'btn_exp_alluser' => '導出全部用戶',
	'btn_exp_seluser' => '導出選中用戶',
	'btn_expire_clear' => '清除過期數據',
	'btn_imptxt' => '導入驗證文件',
	'btn_doc_set' => '許可權設定',
	
	'btn_setpy' => '重置拼音',
	'btn_setdeptpath' => '重置部門路徑',
	'btn_setorder' => '重置排序',
	
	'btn_addmember' => '添加成員',
	'btn_setmember' => '設置成員',
	'btn_setkefum​​ember' => '設置禁止通知客服',
	'btn_setkefumember1' => '設定提醒客服',
	'btn_setkefumember2' => '設定禁止顯示客服',
	'btn_setkefumember3' => '設定顯示人員',
	'btn_setkefumember4' => '設定發送客服',
	'btn_setpublic' => '設定公眾號/小程式',
	'btn_setcdn' => '設置說明',
	
	'btn_reset_tag' => '重置標簽',
	'btn_sel_dept' => '選擇部門',
	'btn_addgrant' => '新增授權',
	'btn_addgroup' => '新增群組',
	'btn_delgroup' => '刪除群組',
	'btn_settag' => '設置標簽',
	'btn_search' => '查詢',
	
	'txt_to' => '至',
	'txt_search' => '查找',
	'txt_index_notice' => '從小到大進行排列',
	'txt_img_tip' => '更改圖片',
	'txt_order' => '從小到大進行排列',
	'txt_usersearch' => '輸入帳號或姓名',
	'txt_loading' => '正在加載中...',
	
	
	'label_name' => '名稱',
	'label_content' => '內容',
	'label_username' => '姓名',
	'label_account' => '帳號',
	'label_pwd' => '密碼',
	'label_desc' => '描述',
	
	'alert_date' => '開始日期必須小於結束日期',
	'alert_delconfirm' => '妳確定要刪除嗎?',
	
	
	
	//字段名稱
	'field_id' => 'ID',
	'field_user' => '用戶',
	'field_content' => '內容',
	'field_time' => '時間',
	'field_name' => '名稱',
	'field_type' => '類型',
	'field_account' => '帳號',
	'field_username' => '姓名',
	'field_sex' => '性別',
	'field_email' => '郵箱',
	'field_mobile' => '手機',
	'field_dept' => '部門',
	'field_disabled' => '禁用',
	'field_grant' => '授權範圍',
	'field_usercount' => '創建用戶數',
	'field_creator' => '創建者',
	'field_diskspace' => '群共享空間',
	'field_usedspace' => '已用空間',
	'field_desc' => '描述',
	'field_tag' => '標簽',
	'field_operate' => '操作',
	'field_icon' => '圖標',
	'field_index' => '序號',
	'field_synctime' => '同步時間',
	'field_dt' => '創建時間',
	'field_job' => '職務',
	'field_other' => '其他',
	
	// admin/sync/push_edit.php 2015年4月10日  zwz
	'syncpush_lb_name' => '推送名稱',
	'syncpush_lb_type' => '推送類型',
	'syncpush_lb_url' => '推送地址',
	
	
	
	//admin/sync/syncpush_list.php
	'syncpush_list_header' => '推送設置',
	'syncpush_list_btn_edit' => '新增推送',
	'syncpush_list_btn_delete' => '刪除推送',
	'syncpush_list_ph_search' => '查找名稱',
	'syncpush_list_col_id' => 'ID',
	'syncpush_list_col_name' => '推送名稱',
	'syncpush_list_col_type' => '推送類型',
	'syncpush_list_col_disabled' => '禁用',
	'syncpush_list_col_creator' => '創建者',
	'syncpush_list_edit' => '編輯',
	'syncpush_list_delete' => '刪除',
	
	'syncpush_org_header' => '推送組織設置',
	'syncpush_org_all' => '全部推送',
	'syncpush_org_increment' => '增量推送',
	
	
	//admin/sync/push_log.php
	'sycnpush_log_header' => '推送日誌',
	'sycnpush_log_col_data' => '數據',
	'sycnpush_log_col_systemname' => '系統名稱',
	'sycnpush_log_col_id' => 'ID',
	'sycnpush_log_col_datatype' => '數據類型',
	'sycnpush_log_col_optype' => '操作類型',
	'sycnpush_log_col_ipaddr' => 'IP',
	'sycnpush_log_col_dt_create' => '同步時間',
	'sycnpush_log_col_status' => '狀態',
	'sycnpush_log_col_result' => '同步結果',
	'sycnpush_log_col_dt_feedback' => '反饋時間',
	'sycnpush_log_icon_error' => '失敗',
	'sycnpush_log_icon_success' => '成功',
	'sycnpush_log_icon_warning' => '未反饋',
	'sycnpush_log_type_create' => '新增',
	'sycnpush_log_type_edit' => '更新',
	'sycnpush_log_type_delete' => '刪除',
	'sycnpush_log_type_text' => '消息',
	'sycnpush_log_type_file' => '附件',
	'sycnpush_log_type_sync' => '同步',
	'sycnpush_log_type_dept' => '部門',
	'sycnpush_log_type_user' => '用戶',
	'sycnpush_log_type_group' => '群組',
	'sycnpush_log_type_msg' => '消息',
	
	//admin/hl/hl_org.php
	'hlorg_header' => '單位互聯 / 組織管理',
	'hlorg_btn_create_dir' => '創建目錄',
	'hlorg_btn_delete_dir' => '刪除目錄',
	'hlorg_col_name' => '名稱',
	'hlorg_col_descibe' => '描述',
	'hlorg_col_address' => '端口地址',
	'hlorg_col_type' => '端口類型',
	'hlorg_col_status' => '狀態',
	
	
	// admin/account/login.php
	'browser_notice1' => '建議使用IE9或FireFox、Chrome瀏覽器，獲得更好的體驗...',
	'browser_notice2' => '妳的IE版本過低，請升級IE版本，或用Chrome/FireFox瀏覽器',
	
	
	'login_error' => '帳號或密碼錯誤',
	'login_error1' => '您今天的錯誤次數超過%1次，已被限制登錄！',
	
	'login_title' => '登錄',
	'login_notice' => '默認管理員帳號：admin 密碼為空，請在登錄後修改管理員密碼',
	'login_lb_account' => '帳號',
	'login_ph_account' => '請輸入帳號',
	'login_required_account' => '請輸入帳號',
	'login_lb_password' => '密碼',
	'login_ph_password' => '請輸入密碼',
	'login_required_password' => '請輸入密碼',
	
	'login_lb_verifycode' => '驗證碼',
	'login_ph_verifycode' => '驗證碼',
	'login_required_verifycode' => '請輸入驗證碼',
	
	// admin/account/setpassword.php
	'pwd_title' => '修改密碼',
	'pwd_notice' => '密碼修改成功，重新登錄生效。',
	'pwd_lb_old' => '舊密碼',
	'pwd_lb_new' => '新密碼',
	'pwd_lb_repeat' => '確認密碼',
	
	'doc_private_title' => '文檔管理 /配置信息',
	'doc_private_notice' => '修改成功',
	'doc_private_lb_path' => '存儲路徑',
	'doc_private_lb_switch' => '允許保存個人文檔',
	
	// admin/doc/doc_log.php
	'doc_log_title' => '文檔管理 /文檔日誌',
	
	// admin/doc/doc_tree.php
	'doc_public_title' => '文檔管理 /文檔存儲',
	'doc_btn_createroot' => '新增根目錄',
	'doc_btn_createfolder' => '新增目錄',
	'doc_btn_editfolder' => '修改目錄',
	'doc_btn_delfolder' => '刪除目錄',
	'doc_btn_addpower' => '添加權限',
	'doc_btn_adduser' => '添加用戶',
	'doc_btn_addrole' => '添加角色',
	'doc_btn_delpower' => '刪除權限',
	'doc_btn_batch' => '批量導入',
	'doc_btn_clean' => '清理資料夾',
	'doc_tree_title' => '存儲目錄',
	'doc_path_title' => '目錄屬性',
	'doc_lb_foldername' => '目錄名稱',
	'doc_ph_foldername' => '目錄名稱',
	'doc_lb_folderpath' => '目錄路徑',
	'doc_ph_folderpath' => '目錄路徑',
	
	// 文檔權限類型
	'doc_power_view' => '顯示',
	'doc_power_edit' => '查看',
    'doc_power_edit1' => '編輯',
	'doc_power_manage' => '移動',
	'doc_power_download' => '下載',
	'doc_power_create' => '創建',
	'doc_power_delete' => '刪除',
	'doc_power_rename' => '重命名',
	'doc_power_sendfile' => '分享',
	'doc_power_permission' => '權限',
	'doc_power_finalized' => '定版',
	
	// 文檔日誌類型
	'type_downloadfile' => '下載文件',
	'type_editfile' => '編輯文件',
	'type_newfile' => '創建文件',
	'type_removefile' => '移動文件',
	'type_viewfile' => '查看文件',
	'type_deletefile' => '刪除文件',
	'type_sharefile' => '共享文件',
	'type_login' => '登錄',
	
	// 版權信息
	'about_version' => '版本號',
	'about_publishdate' => '發布日期',
	'about_website' => '產品網址',
	'about_copyright' => '版權所有2015 %1. 保留所有權利。',
	
	// 軟件註冊
	'reg_machinecode' => '機器碼',
	'reg_licensenumber' => '許可數',
	'reg_usercount' => '總用戶數',
	'reg_expiredate' => '到期時間',
	'reg_lb_active' => '請輸入激活碼',
	
	//管理端設置
	'webserver_config_title' => '後臺設置',
	'webserver_config_antserver' => 'WebServer消息服務器配置',
	'webserver_config_common' => 'WebServer常用配置',
	'webserver_config_added' => 'WebServer增值配置',
	'webserver_lb_ant_server' => '消息服務器IP地址',
	'webserver_lb_ant_server_tip' => '請用真實IP，如192.168.0.1,代理服務器請用代理地址',
	'webserver_lb_ant_console_tip' => '請謹慎修改，修改後請搭建一個網站指向數據目錄並修改視頻播放地址，否則雲盤視頻無法網頁播放!',
	'webserver_lb_ant_port' => '端口',
	'webserver_lb_ant_datadir' => '數據目錄',
	'webserver_lb_ant_consoledir' => '控制臺目錄',
	'webserver_lb_ant_video' => '視頻播放地址',
	'webserver_lb_ant_video_tip' => '修改數據目錄後,並搭建一個網站指向數據目錄後才需要填寫!例如 http://192.168.1.4:94',
	'webserver_lb_export_field' => '數據導入導出格式',
	'webserver_lb_push_toket' => 'WebSerivce令牌',
	'webserver_lb_api_return_type' => 'WebSerivce 返回內容格式',
	'webserver_lb_sms_url' => '短信接口地址',
	'webserver_lb_sms_sample' => '例:http://192.168.0.1/sms_send.html?mobile={mobile}&content={content},多個手機號用,逗號分隔,返回的內容需JSON格式,如{"status":1} 或{"status":0,"msg":"error"}',
	'webserver_lb_smtp_info' => '郵件發送信息',
	'webserver_lb_smtp_server' => 'SMTP服務器地址：',
	'webserver_lb_smtp_port' => 'SMTP服務器端口：',
	'webserver_lb_smtp_account' => '郵箱帳號：',
	'webserver_lb_smtp_password' => '郵箱密碼：',
	'webserver_lb_back_onlineminute' => 'API 登錄心跳時長(超時設為退出)',
	'webserver_lb_log_level'=>'WebServer日誌級別',
	'webserver_lb_log_level_close'=>'關閉',
	'webserver_lb_log_level_debug'=>'debug',
	'webserver_lb_log_level_info'=>'info',
	'webserver_lb_log_level_error'=>'error',
	'webserver_lb_log_level_open'=>'開啟',
	'webserver_lb_push_sms' => '消息短信推送',
	'webserver_lb_push_email' => '消息郵件推送',
	'webserver_lb_push_sms_desc' => '當手機沒有收到推送消息,系統會發短信提醒用戶打開app查看消息',
	'webserver_lb_push_email_desc' => '當手機沒有收到推送消息,系統會發郵件提醒用戶打開app查看消息',
	  
	
	// 單位互聯
	'hl_config_title' => '單位互聯<small>（帶<i class="warnning">*</i>號為必填項 ）</small>',
	'hl_config_legend1' => '互聯信息',
	'hl_config_legend2' => '中心服務器(必選)',
	'hl_config_legend3' => '文件服務器(可選)',
	'hl_config_legend4' => '音視頻服務器(可選)',
	'hl_lb_unitid' => '單位ID',
	'hl_lb_connectpwd' => '連接密碼',
	'hl_ph_centerport' => '默認 8899',
	'hl_lb_serverip' => '服務器IP',
	'hl_lb_serverport' => '服務器端口',
	
	
	// 組織人員管理
	'org_title' => '組織管理',
	'org_ph_search' => '輸入帳號或姓名',
	'org_tree_title' => '部門管理',
	'org_user_title' => '人員列表',
	'dept_lb_path' => '上級部門',
	'dept_lb_name' => '部門名稱',
	'dept_ph_name' => '部門名稱',
	'dept_lb_desc' => '部門描述',
	'dept_ph_desc' => '部門描述',
	'dept_lb_index' => '排序號',
	'dept_ph_index' => '1000',
	'dept_lb_display' => '人員顯示',
	'dept_col_style0' => '狀態優先',
	'dept_col_style1' => '忽略狀態',
	
	'dept_lb_reset' => '刪除以前的部門',
	
	//分級管理
	'grant_lb_user' => '授權人員',
	'grant_lb_tree' => '授權部門',
	'grant_lb_usercount' => '人員數量',
	'grant_notice' => '0 表示創建用戶數不限制',
	'grant_title' => '授權管理',
	'grant_exist' => '此部門已經授權過',
	'grant_beyond' => '超出授權人數',
	
	//群組管理
	'group_tab_base' => '屬性',
	'group_tab_member' => '成員',
	'group_tab_board' => '群公告' ,
	'group_tab_tag' => '標簽',
	'group_lb_name' => '名稱',
	'group_ph_name' => '',
	'group_lb_diskspace' => '群空間大小',
	'group_ph_diskspace' => '',
	'group_lb_index' => '排序號',
	'group_ph_index' => '1000',
	'group_lb_desc' => '描述',
	'group_ph_desc' => '',
	'group_tree_title' => '選擇成員',
	'group_title' => '群組管理',
	'group_ph_search' => '查找群組',
	'group_ph_portrait' => '群頭像',
	'group_ph_Banned' => '全員禁言',
	//導入部門
	'imp_lb_filepath' => '導入文件',
	'imp_dept_warning' => '請設置導入文件為UTF-8編碼,以確保中文不亂碼',
	'imp_dept_link_path' => '導入【路徑】格式',
	'imp_dept_link_table' => '導入【表格】格式',
	
	//導入用戶
	'imp_user_warning' => '請使用UTF-8格式,以確保中文不亂碼',
	'imp_user_switch' => '快速導入',
	'imp_user_link' => '文本導入格式',
	
	'imp_txt_warning' => '請從微信公眾號/小程式下載驗證檔案',
	//導入域用戶
	'ldap_lb_domain' => '域控服務器',
	'ldap_ph_domain' => '域服務器域名',
	'ldap_lb_admin' => '管理員帳號',
	'ldap_ph_admin' => '管理員帳號',
	'ldap_lb_pwd' => '密碼',
	
	//職位銘牌
	'pos_lb_icon' => '圖標',
	'pos_lb_preview' => '預覽',
	'pos_lb_index' => '序號',
	'pos_lb_name' => '名稱',
	'pos_lb_desc' => '描述',
	'pos_title' => '銘牌管理',
	'pos_ph_search' => '查找銘牌',
	
	//角色
	'role_tab_base' => '屬性',
	'role_tab_member' => '成員',
	'role_tab_power' => '基本權限',
	'role_tab_org' => '組織權限',
	'role_tab_ip' => '登錄設置',
	'role_tab_file' => '文件管理',
	
	'role_tree_title' => '選擇成員',
	'role_ph_search' => '輸入帳號或姓名',
	
	'role_power_warning' => '當修改角色權限後，員工所擁有的角色權限也隨之改變，您無需修改員工所擁有的角色。',
	'role_power_warning1' => '拓展名限制為*表示上傳或發送文件類型無限制，輸入格式:rar;doc;xls',
	'role_power_chk_smscount' => '發送短信&nbsp;&nbsp;最多限制',
	'role_power_smscount' => '條/月',
	'role_power_chk_ptpsize' => '上傳個人文檔/共享文件',
	'role_power_ptpsize' => '上傳最大限制',
	'role_power_ptptype' => '上傳拓展名限制：',
	'role_power_download_ptpsize' => '下載個人文檔/共享文件',
	'role_power_chk_clotsize' => '上傳群組文件',
	'role_power_download_clotsize' => '下載群組文件',
	'role_power_chk_userssize' => '發送文件',
	'role_power_userssize' => '發送最大限制',
	'role_power_userstype' => '發送拓展名限制：',
	'role_power_download_userssize' => '接收文件',
	'role_power_download_networks' => '禁止在外網和手機下載所有文件',
	'role_power_other_department' => '禁止與其他部門聊天',
	'role_power_this_department' => '禁止與本部門聊天',
	'role_power_unauthorized_control' => '無權限控制(可以看到所有部門、賬號)',
	'role_power_switch0_department' => '禁止看到以下部門及其所屬賬號',
	'role_power_switch1_department' => '只允許看到以下部門及其所屬賬號',
	'role_power_remote_login' => '遠程登陸',
	'role_power_phone_login' => '手機登陸',
	'role_power_restrictip' => '限制IP',
	'role_power_restrictmac' => '限制MAC',
	'role_power_password' => '修改密碼',
	'role_power_sendboard' => '發布公告',
	'role_power_delboard' => '允許刪除公告',
	'role_power_attachsize' => '附件大小限制',
	'role_power_broadcast' => '群發個數限制',
	'role_power_setattr' => '修改個人設置',
	'role_power_setjob' => '禁止顯示職務',
	'role_power_recfile' => '禁止用戶接收附件',
	'role_power_video' => '語音視頻',
	'role_power_audio' => '禁止語音通話',
	'role_power_signout' => '禁止退出群組',
	'role_power_logout' => '禁止客戶端註銷',
	'role_power_remote' => '遠程屏幕和遠程控制',
	'role_power_ring' => '禁止客戶端聲音提示',
	'role_power_splashscreen' => '禁止發送閃屏',
	'role_power_signmsg' => '禁止發送簽收消息',
	'role_power_showsignature' => '禁止顯示個人簽名',
	'role_power_changephoto' => '禁止客戶端修改頭像',
	'role_power_screenshot' => '禁止截屏',
	'role_power_set' => '修改高級設置',
	'role_power_setaway' => '禁止隱身',
	'role_power_sendtopmsg' => '禁止發送置頂消息',
	'role_power_privatechat' => '禁止密聊功能',
	'role_power_sysview' => '顯示組織架構',
	'role_power_group_create' => '創建群組',
	'role_lb_ipaddr' => '允許的IP地址',
	'role_lb_loginpower' => '登陸權限設置',
	'role_lb_switch0' => '禁止',
	'role_lb_switch1' => '允許',
	
	//admin/hs/role_list.php
	'role_list_title' => '角色管理',
	'role_list_btn_add' => '新增角色',
	'role_list_btn_member' => '設置人員',
	'role_list_btn_delete' => '刪除角色',
	'role_list_btn_set' => '壹鍵設置角色',
	'role_list_ph_search' => '查找角色',
	'role_list_col_name' => '名稱',
	'role_list_col_description' => '描述',
	'role_list_col_creator_name' => '創建者',
	'role_list_col_disabled' => '禁用',
	'role_list_col_member' => '人員',
	'role_list_col_change' => '修改',
	'role_list_col_detele' => '刪除',
	'role_list_col_clone' => '克隆',
	'role_list_btn_role' => '設置角色',
	'role_list_btn_batches' => '批量設置角色',
	//admin/hs/role_picker.php
	'role_picker_col_name' => '名稱',
	'role_picker_col_description' => '描述',
	'role_picker_default_role' => '新增用戶默認角色',
	
	//admin/hs/tag_edit.php
	'tag_lb_name' => '標簽名稱',
	'tag_ph_name' => '標簽名稱',
	
	//admin/hs/tag_list.php
	'tag_list_title' => '標簽管理',
	'tag_list_btn_add' => '新增分類',
	'tag_list_type_edit' => '編輯',
	'tag_list_type_delete' => '刪除',
	'tag_list_ph_name' => '添加標簽',
	'tag_list_col_user' => '查看人員',
	'tag_list_col_group' => '查看群組',
	'tag_list_col_edit' => '修改標簽',
	'tag_list_col_delete' => '刪除標簽',
	
	//admin/hs/tag_picker.php
	'tag_picker_checkbox_reset' => '重置標簽',
	'tag_picker_alert' => '請選擇要設置的對象',
	
	//admin/hs/tag_type_edit.php
	'tag_type_lb_name' => '類型名稱',
	'tag_type_ph_name' => '類型名稱',
	
	//admin/hs/user_attr.php
	'user_attr_allowedcard' => '允許網卡地址(多條以,逗號分隔)',
	'user_attr_allowedip' => '允許IP地址(多條以,逗號分隔)',
	
	//admin/hs/user_edit.php
	'user_edit_tab_base' => '基本信息',
	'user_edit_tab_work' => '業務信息',
	'user_edit_tab_self' => '個人信息',
	'user_edit_tab_login' => '登錄信息',
	'user_edit_tab_power' => '角色與權限',
	'user_edit_account' => '帳號',
	'user_edit_username' => '姓名',
	'user_edit_psw' => '密碼',
	'user_edit_show_password' => '顯示密碼',
	'user_edit_sequence' => '排序號',
	'user_expiration_time' => '有效期',
	'user_expiration_tip' => '設置當前部門及下屬所有部門人員的過期時間',
	'user_expiration_set' => '長期有效',
	'user_edit_order' => '排序號越大，越排前面',
	'user_edit_checkbox_admin' => '管理員',
	'user_edit_checkbox_disabled' => '禁用帳號',
	'user_edit_lb_jobtitle' => '職務',
	'user_edit_lb_nameplate' => '銘牌',
	'user_edit_lb_phone' => '固話',
	'user_edit_lbl_shortnum' => '短號',
	'user_edit_lb_mobile' => '手機',
	'user_edit_lb_fax' => '傳真',
	'user_edit_lb_email' => '郵箱',
	'user_edit_lb_address' => '地址',
	'user_edit_lb_postal' => '郵編',
	'user_edit_lb_gender' => '性別',
	'user_edit_lb_gender1' => '男',
	'user_edit_lb_gender2' => '女',
	'user_edit_lb_age' => '年齡',
	'user_edit_lb_birthday' => '生日',
	'user_edit_lb_province' => '省份',
	'user_edit_lb_city' => '城市',
	'user_edit_lb_street' => '街道',
	'user_edit_lb_website' => '網頁',
	'user_edit_lb_description' => '個人說明',
	'user_edit_lb_school' => '畢業學校',
	'user_edit_lb_note' => '備註',
	'user_edit_col_mac' => '允許網卡地址(多條以,逗號分隔)',
	'user_edit_col_ip' => '允許IP地址(多條以,逗號分隔,格式192.168.1.1或192.168.1.1-192.168.1.3)',
	'user_edit_power_roles' => '用戶所擁有的角色',
	'user_edit_power_ou' => '允許訪問的組織',
	
	
	//admin/hs/user_list.php
	'user_list_page_title' => '人員管理',
	'user_list_btn_add' => '新增人員',
	'user_list_btn_batch' => '批量操作',
	'user_list_dropdown_properties' => '設置屬性',
	'user_list_dropdown_dept' => '設置部門',
	'user_list_dropdown_role' => '設置角色',
	'user_list_dropdown_pos' => '設置銘牌' ,//
	'user_list_dropdown_label' => '設置標籤',
	'user_list_dropdown_delete' => '刪除',
	'user_list_ph_search' => '查找人員帳號/姓名',
	'user_list_col_loginname' => '帳號',
	'user_list_col_name' => '姓名',
	'user_list_col_sex' => '性別',
	'user_list_col_email' => 'Email',
	'user_list_col_mobile' => '電話',
	'user_list_col_deptinfo' => '部門',
	'user_list_col_job' => '職務',
	'user_list_col_other' => '其他',
	'user_list_col_expiretime' => '到期時間',
	'user_list_col_issuper' => '管理員',
	'user_list_col_disabled' => '禁用',
	'user_list_col_label' => '禁用',
	'user_list_alert' => 'admin帳號不允許此操作',
	
	
	//admin/hs/user_picker.php
	'user_picker_title' => '選擇成員',
	'user_picker_ph_userkey' => '輸入帳號或姓名',
	'user_picker_btn_add' => '添加成員',
	'user_picker_col_name' => '姓名',
	'user_picker_col_account' => '帳號',
	'user_picker_checkbox_reset' => '重置成員',
	'user_picker_col_title' => '名稱',
	'user_picker_col_type' => '類型',
	
	//admin/include/bioace_lis.php
	'bioace_btn_add' => '新增權限',
	'bioace_btn_delete' => '刪除權限',
	'bioace_btn_change' => '修改權限',
	'bioace_col_name' => '名稱',
	'bioace_col_type' => '類型',
	'bioace_col_permission' => '權限',
	'bioace_col_delete' => '刪除',
	
	
	//admin/include/header.php
	'header_hello' => '您好, ',
	'header_home' => '首頁',
	'header_download' => '下載專區',
	'header_changepsw' => '修改密碼',
	'header_exit' => '退出',
	'header_help' => '幫助',
	'header_dropdown_register' => '註冊',
	'header_dropdown_about' => '關於',
	'header_nopermission' => '沒有權限',
	'header_nopermission_operate' => '沒有權限操作此頁面',
	'header_lang' => '語言',
	'header_cn' => '簡體中文',
	'header_hk' => '繁體中文',
	'header_en' => '英語',
	
	//admin/include/header0.php
	'header0_help' => '幫助', //' '
	'header0_dropdown_register' => '註冊',
	'header0_dropdown_about' => '關於',
	
	
	//admin/include/index.php
	'index_companyinfo' => '單位信息: ',
	'index_btn_set' => '設置',
	'index_commonuse' => '常用操作',
	'index_user' => '用戶管理',
	'index_user_des' => '添加，刪除，設置，導入/導出部門及人員信息',
	'index_upgrade' => '升級管理', //'升級管理'
	'index_upgrade_des' => '升級PC、Andriod客戶端',
	'index_server' => '服務控制',
	'index_server_des' => '啟動，停止，重啟各類即時通訊服務',
	'index_service' => '在線客服',
	'index_service_des' => '客戶可以通過網頁與我們的員工交流溝通',
	'index_application' => '應用中心',
	'index_application_des' => '企業第三方管理系統如OA、CRM以及其它業務系統',
	'index_map' => '功能地圖 ',
	
	//admin/lv_manager/chat_list.php
	'lvchat_private_title' => '在線客服 /配置信息',
	
	'transfer_list_title' => '轉接記錄',
	'transfer_list_original' => '原客服',
	'transfer_list_now' => '現客服',
	'transfer_list_userid' => '用戶ID',
	'transfer_list_type' => '類型',
	'transfer_list_date' => '時間',
	'transfer_list_type1' => '轉接',
	'transfer_list_type2' => '搶接',
	'transfer_list_type3' => '自動轉接',
	
	'lvchat_list_title' => '會話管理',
	'lvchat_list_drop_status' => '全部',
	'lvchat_list_drop_status0' => '等待中',
	'lvchat_list_drop_status1' => '交談中',
	'lvchat_list_drop_status2' => '結束',
	'lvchat_list_field_account' => '客服帳號',
	'lvchat_list_field_name' => '訪客姓名',
	'lvchat_list_field_userid' => '用戶ID',
	'lvchat_list_field_chatid' => '會話ID',
	'lvchat_list_field_content' => '內容',
	'lvchat_list_txt_keywords' => '關鍵字',
	'lvchat_list_txt_date' => '會話日期',
	'lvchat_list_chatid' => '會話ID',
	'lvchat_list_account' => '客服帳號',
	'lvchat_list_userid' => '用戶ID',
	'lvchat_list_username' => '姓名',
	'lvchat_list_ip' => 'IP',
	'lvchat_list_area' => '地區 ',
	'lvchat_list_intime' => '進入時間',
	'lvchat_list_connecttime' => '接通時間',
	'lvchat_list_outtime' => '結束時間',
	'lvchat_list_status' => '狀態',
	'lvchat_list_attach' => '附件',
	'lvchat_list_record' => '記錄',
	'lvchat_list_allrecord' => '全部記錄',
	'lvchat_list_blackip' => '黑名單',
	'lvchat_list_return_case0' => '等待中',
	'lvchat_list_return_case1' => '交談中',
	'lvchat_list_return_case2' => '結束',
	'lvchat_list_groupid' => '請選擇入口',
	'lvchat_list_groupname' => '入口',
	'lvchat_list_themeid' => '請選擇主題',
	'lvchat_list_themename' => '主題',
	'lvchat_list_chatlevel' => '請選擇價值',
	'lvchat_list_chatlevelname' => '級別',
	'lvchat_list_chatlevel0' => '未評估',
	'lvchat_list_chatlevel1' => '無價值',
	'lvchat_list_chatlevel2' => '有價值',
	'lvchat_list_isenable' => '請選擇效果',
	'lvchat_list_isenable1' => '無效會話',
	'lvchat_list_isenable2' => '有效會話',
	'lvchat_list_no' => '全部',
	'lvchat_list_not' => '非入口會話',
	'lvchat_list_drp_type0' => '通話量',
	'lvchat_list_drp_type2' => '會話價值',
	'lvchat_list_drp_type1' => '會話主題',
	'lvchat_list_uname' => '名稱',
	'lvchat_list_groupcount' => '總接待量',
	'lvchat_list_percent' => '佔比',
	'lvchat_list_detail' => '詳情',
	'lvchat_list_first_inouttime' => '首次',
	'lvchat_list_inouttime' => '平均',
	'lvchat_list_rate' => '評分',
	'lvchat_list_first_inouttimes' => '首次回复時間',
	'lvchat_list_inouttimes' => '平均回复時間',
	'lvchat_list_chat_times' => '聊天時間',
	'lvchat_list_rates' => '評分',
	'lvchat_list_enable_inoutnum' => '已回復會話量',
	'chart_rate_unit0' => '未評',
	'chart_rate_unit1' => '惡劣',
	'chart_rate_unit2' => '較差',
	'chart_rate_unit3' => '一般',
	'chart_rate_unit4' => '較好',
	'chart_rate_unit5' => '滿意',
	
	//admin/lv_manager/chater_edit.php
	'chater_edit_photo' => '更改照片',
	'chater_edit_lb_account' => '帳號',
	'chater_edit_ph_account' => '帳號',
	'chater_edit_lb_name' => '姓名',
	'chater_edit_ph_name' => '姓名',
	'chater_edit_lb_dept' => '部門',
	'chater_edit_ph_dept' => '部門',
	'chater_edit_lb_job' => '職位',
	'chater_edit_ph_job' => '職位',
	'chater_edit_lb_tel' => '座機',
	'chater_edit_ph_tel' => '座機',
	'chater_edit_lb_mobile' => '手機',
	'chater_edit_ph_mobile' => '手機',
	'chater_edit_lb_reception' => '最大接待量',
	'chater_edit_ph_reception' => '最大接待量',
	'chater_edit_lb_email' => '郵箱',
	'chater_edit_ph_email' => '郵箱',
	'chater_invite_lb_welcome' => '邀請框歡迎語',
	'chater_invite_ph_welcome' => '邀請框歡迎語',
	'chater_edit_lb_welcome' => '歡迎語',
	'chater_edit_ph_welcome' => '歡迎語',
	'chater_edit_lb_cdn_title' => '請輸入CDN加速域名',
	'chater_edit_lb_adlink' => '廣告url',
	'chater_edit_lb_adlink_alert' => '請輸入廣告鏈接url',
	'chater_edit_lb_ad' => '廣告',
	'chater_edit_lb_ad_img' => '廣告圖片',
	'chater_edit_lb_ad_title' => '更改廣告',
	'chater_delete_lb_ad_title' => '清除廣告',
	'chater_edit_lb_status' => '狀態',
	'chater_edit_option_status1' => '正常',
	'chater_edit_option_status0' => '關閉',
	'chater_edit_lb_order' => '排序',
	'chater_edit_ph_order' => '排序',
	'chater_edit_alert' => '用戶不存在!',
	'chater_edit_error_account' => '請輸入帳號',
	'chater_edit_error_name' => '請輸入姓名',
	'chater_edit_error_ord' => '請輸入排序號',
	'chater_edit_end_conversation' => '對話結束',
	'chater_edit_end_conversation0' => '不設置',
	'chater_edit_end_conversation1' => '自動置後',
	'chater_edit_end_conversation2' => '自動移除',
	'chater_edit_lb_endsession' => '結束會話後',
	'chater_edit_lb_endsession_alert' => '從排隊列表中接入新會話',
	'chater_edit_default' => '默認',
	'chater_edit_lb_match' => '匹配方式',
	'chater_edit_option_match0' => '模糊匹配',
	'chater_edit_option_match1' => '精準匹配',
	'chater_edit_lb_receives_reminders' => '客服接收提醒',
	'chater_edit_lb_receives_reminders_alert' => '客服可收到完整會話，不勾選此項，可智能過濾掉大流量的重複諮詢',
	'chater_edit_lb_top_questions' => '熱門問題',
	'chater_edit_lb_top_questions_alert' => '訪客端顯示，點擊熱門問題，自動應答',
	'chater_edit_defaulttargetlanguage' => '手動翻譯為',
	'chater_edit_usertargetlanguage' => '訪客消息自動翻譯為',
	'chater_edit_chatertargetlanguage' => '客服消息自動翻譯為',
	'chater_edit_language_zh' => '簡體中文',
	'chater_edit_language_en' => '英語',
	'chater_edit_language_yue' => '粵語',
	'chater_edit_language_wyw' => '文言文',
	'chater_edit_language_jp' => '日語',
	'chater_edit_language_kor' => '韓語',
	'chater_edit_language_fra' => '法語',
	'chater_edit_language_spa' => '西班牙語',
	'chater_edit_language_th' => '泰語',
	'chater_edit_language_ara' => '阿拉伯語',
	'chater_edit_language_ru' => '俄語',
	'chater_edit_language_pt' => '葡萄牙語',
	'chater_edit_language_de' => '德語',
	'chater_edit_language_it' => '意大利語',
	'chater_edit_language_el' => '希臘語',
	'chater_edit_language_nl' => '荷蘭語',
	'chater_edit_language_pl' => '波蘭語',
	'chater_edit_language_bul' => '保加利亞語',
	'chater_edit_language_est' => '愛沙尼亞語',
	'chater_edit_language_dan' => '丹麥語',
	'chater_edit_language_fin' => '芬蘭語',
	'chater_edit_language_cs' => '捷克語',
	'chater_edit_language_rom' => '羅馬尼亞語',
	'chater_edit_language_slo' => '斯洛文尼亞語',
	'chater_edit_language_swe' => '瑞典語',
	'chater_edit_language_hu' => '匈牙利語',
	'chater_edit_language_cht' => '繁體中文',
	'chater_edit_language_vie' => '越南語',
	
	'user_edit_lb_name' => '姓名',
	'user_edit_ph_name' => '姓名',
	'user_edit_lb_wechat' => '微信',
	'user_edit_ph_wechat' => '微信',
	'user_edit_lb_qq' => 'qq',
	'user_edit_ph_qq' => 'qq',
	'user_edit_lb_remarks' => '備註',
	'user_edit_ph_remarks' => '備註',
	'user_edit_lb_mobile' => '手機',
	'user_edit_ph_mobile' => '手機',
	'user_edit_lb_chater' => '優先接待客服',
	'user_edit_ph_chater' => '請輸入客服賬號',
	'user_edit_lb_email' => '郵箱',
	'user_edit_ph_email' => '郵箱',
	'user_edit_alert' => '客服不存在或被禁用!',
	
	//admin/lv_manager/chater_list.php
	'chater_list_title' => '客服列表',
	'chater_list_add' => '新增客服',
	'chater_list_deleteoperate' => '刪除客服',
	'chater_list_preview' => '預覽',
	'chater_list_generate' => '客服代碼',
	'chater_list_search' => '查找人員帳號/姓名',
	'chater_list_account' => '帳號',
	'chater_list_name' => '姓名',
	'chater_list_dept' => '部門',
	'chater_list_job' => '職位',
	'chater_list_tel' => '座機',
	'chater_list_mobile' => '手機',
	'chater_list_email' => '郵箱',
	'chater_list_reception' => '最大接待量',
	'chater_list_welcome' => '歡迎語',
	'chater_list_top' => '熱門問題',
	'chater_list_status' => '狀態',
	'chater_list_order' => '排序',
	'chater_list_link' => '鏈接',
	'chater_list_js' => '代碼',
	'chater_list_qrcode' => '二維碼',
	'chater_list_dialog' => '會話',
	'chater_list_rate' => '評價',
	'chater_list_edit' => '編輯',
	'chater_list_delete' => '刪除',
	'chater_list_up' => '上移',
	'chater_list_down' => '下移',
	'chater_list_talk' => '交談',
	'chater_list_attributes' => '屬性',
	'chater_list_generate1' => '移動端客服代碼',
	'chater_list_member' => '成員',
	'chater_list_server' => '服務器地址',
	'chater_list_alert_enteripaddress' => '當前服務器在外網上的URL地址,可以是IP或域名',
	'chater_list_copy' => '複製',
	'chater_list_mode' => '模式',
	'chater_list_mode_alert1' => '網站模式(所有客服都是公司員工)',
	'chater_list_mode_alert2' => '商城多用戶模式(每個客服對應一個店鋪)',
	'chater_list_distribution' => '客服分配',
	'chater_list_distribution_alert1' => '智能模式',
	'chater_list_distribution_alert2' => '順序模式',
	'chater_list_guestsession' => '訪客會話',
	'chater_list_guestsession_alert1' => '直接會話',
	'chater_list_guestsession_alert2' => '排隊會話',
	'chater_list_switchtype' => '自動邀請',
	'chater_list_switchtype_alert1' => '邀請會話在顧客訪問網站',
	'chater_list_switchtype_alert2' => '秒後發出',
	'chater_list_websitetype' => '訪客提醒',
	'chater_list_websitetype_alert1' => '訪客提醒',
	'chater_list_websitetype_alert2' => '網站訪客進入通知客服',
	'chater_list_websitetype_alert3' => '訪客打開對話框提醒客服',
	'chater_list_websitetype_alert4' => '網站訪客進入自動與客服會話',
	'chater_list_websitetype_alert5' => '不設定',
	'chater_list_switchweChat' => '公眾號/小程式',
	'chater_list_switchweChat_alert1' => '微信公眾號/小程式',
	'chater_list_switchweChat_alert2' => '通過微信公眾號/小程式推送消息',
	'chater_list_switchBack' => '返回按鈕',
	'chater_list_switchBack_alert1' => '訪客手機端不顯示返回按鈕',
	'chater_list_switchBack_alert2' => '設定禁止顯示客服',
	'chater_list_sendWelcome' => '發送歡迎語',
	'chater_list_sendWelcome_alert1' => '訪客每次打開聊天頁面發送客服歡迎語',
	'chater_list_sendWelcome_alert2' => '設定發送客服',
	'chater_list_switchDomainType' => '切換跳轉功能變數名稱',
	'chater_list_switchDomainType_alert1' => '自動切換跳轉功能變數名稱（當訪客端打不開頁面）',
	'chater_list_rejecttype' => '評價',
	'chater_list_rejecttype_alert1' => '評價',
	'chater_list_rejecttype_alert2' => '聊天結束或關閉強制評價',
	'chater_list_weixintype' => '入口限制',
	'chater_list_weixintype_alert1' => '評價',
	'chater_list_weixintype_alert2' => '只允許從微信打開',
	'chater_list_cdntype' => 'CDN加速',
	'chater_list_cdntype_alert1' => '評價',
	'chater_list_cdntype_alert2' => '手機訪客端js/css靜態資源CDN加速,解決第一次打開慢的問題',
	'chater_list_heartbeat' => '心跳包',
	'chater_list_heartbeat_alert1' => '倍時長(倍數越大，服務器負載越小，已讀/未讀狀態獲取時間越長)',
	'chater_list_showhistory' => '聊天記錄',
	'chater_list_showhistory_alert1' => '訪客端不顯示歷史聊天記錄',
	'chater_list_voicevideo' => '語音視頻',
	'chater_list_voicevideo_alert1' => '訪客端禁止語音/視頻電話',
	'chater_list_history_alert1' => '清除',
	'chater_list_history_alert2' => '小時前的聊天記錄',
	'chater_list_reminder' => '超時提醒',
	'chater_list_reminder_alert1' => '接收到訪客信息後,超過',
	'chater_list_reminder_alert2' => '秒未回复,頭像紅框顯示',
	'chater_list_transfer' => '超時轉接',
	'chater_list_transfer_alert1' => '接收到訪客資訊後，超過',
	'chater_list_transfer_alert2' => '秒未回復，自動轉接到其他客服',
	'chater_list_oldvisitor' => '熟客有效期',
	'chater_list_oldvisitor_alert1' => '在',
	'chater_list_oldvisitor_alert2' => '秒內熟客接入會話尋找原客服聊(限定時間之後接入會話尋找其他客服聊)',
	'chater_list_server_configuration' => '服務器配置',
	'chater_list_weChat_official_account_configuration' => '微信公眾號/小程式配寘',
	'chater_list_advertising_configuration' => '廣告配置',
	'chater_list_domain' => '網頁授權域名',
	'chater_list_appid' => '開發者ID(AppID)',
	'chater_list_sercet' => '開發者密碼(AppSecret)',
	'chater_list_token' => '令牌(Token)',
	'chater_list_moban_id' => '模版消息ID',
	'chater_list_subscribe_id' => '訂閱通知模版ID',
	'chater_list_moban_message1' => '模版消息',
	'chater_list_moban_message2' => '一次性訂閱消息',
	'chater_list_subscribe' => '訂閱消息',
	'chater_list_subscribe1' => '一次性訂閱消息',
	'chater_list_subscribe2' => '訂閱通知',
	'chater_list_subscribe3' => '不推送訂閱通知',
	'chater_list_customer_service_link' => '被動客服鏈接',
	'chater_list_wechat_customer_service_link' => '主動客服鏈接',
	'chater_list_link1' => '例如:http://g.rtcim.com/vendor/wx/?act=openid&redirect_uri=http%3A//g.rtcim.com%3A98/kefu.html,redirect_uri參數為escape加密過的客服鏈接。 ',
	'chater_list_domain_alert' => '請輸入網頁授權域名',
	'chater_list_appid_alert' => '請輸入開發者ID(AppID)',
	'chater_list_sercet_alert' => '請輸入開發者密碼(AppSecret)',
	'chater_list_token_alert' => '請輸入令牌(Token)',
	'chater_list_moban_id_alert' => '請輸入模版消息ID',
	'chater_list_subscribe1_id_alert' => '請輸入一次性訂閱消息模版ID',
	'chater_list_subscribe2_id_alert' => '請輸入訂閱通知模版ID',
	'chater_list_subscribe4_id_alert' => '請輸入訂閱消息模版ID',
	'chater_list_customer_service_link_alert' => '請輸入收到的模版消息/訂閱通知跳轉客服鏈接',
	'chater_list_wechat_customer_service_link_alert' => '請輸入公眾號/小程式自定義選單/訂閱通知客服連結',
	'chater_list_isminiprogram' => '小程式',
	'chater_list_account' => '公眾號',
	
	'chater_list_chatgpt_configuration' => '機器人設定',
	'chater_list_chatgpt_reception' => '默認接待',
	'chater_list_chatgpt_reception1' => '智慧客服',
	'chater_list_chatgpt_reception2' => '人工客服',
	'chater_list_chatgpt_reception3' => '請選擇',
	'chater_list_chatgpt_transfer' => '轉人工/機器人',
	'chater_list_chatgpt_transfer_desc' => '接待過程中，訪客側顯示轉人工/機器人按鈕',
	'chater_list_chatgpt_autotransfer' => '自動轉人工',
	'chater_list_chatgpt_autotransfer_desc' => '機器人未能回答',
	'chater_list_chatgpt_autotransfer_desc1' => '次，自動轉人工',
	'chater_list_chatgpt' => '文心一言',
	'chater_list_chatgpt_desc' => '智慧客服機器人回答訪客消息',
	'chater_list_chatgpt_API_Key' => 'API Key',
	'chater_list_chatgpt_API_Key_desc' => '請輸入文心一言API Key',
	'chater_list_chatgpt_Secret_Key' => 'Secret Key',
	'chater_list_chatgpt_Secret_Key_desc' => '請輸入文心一言Secret Key',
	'chater_list_chatgpt_API_Url' => 'API地址',
	'chater_list_chatgpt_Model' => '默認模型',
	'chater_list_chatgpt_Model1' => 'ERNIE-Bot',
	'chater_list_chatgpt_Model2' => 'ERNIE-Bot-turbo',
	'chater_list_chatgpt_Model3' => 'BLOOMZ-7B',
	'chater_list_chatgpt_Model4' => 'Qianfan-BLOOMZ-7B-compressed',
	'chater_list_chatgpt_Model5' => 'Llama-2-7b-chat',
	'chater_list_chatgpt_Model6' => 'Llama-2-13b-chat',
	'chater_list_chatgpt_Model7' => 'Llama-2-70b-chat',
	'chater_list_chatgpt_Model8' => 'Qianfan-Chinese-Llama-2-7B',
	'chater_list_chatgpt_Model9' => 'Linly-Chinese-LLaMA-2-7B',
	'chater_list_chatgpt_Model10' => 'Linly-Chinese-LLaMA-2-13B',
	'chater_list_chatgpt_Model11' => 'ChatGLM2-6B',
	'chater_list_chatgpt_Model12' => 'ChatGLM2-6B-32K',
	'chater_list_chatgpt_Model13' => 'ChatGLM2-6B-INT4',
	'chater_list_chatgpt_Model14' => 'Falcon-7B',
	'chater_list_chatgpt_Model15' => 'Falcon-40B-Instruct',
	'chater_list_chatgpt_Model16' => 'AquilaChat-7B',
	'chater_list_chatgpt_Model17' => 'RWKV-4-World',
	'chater_list_chatgpt_Model18' => 'RWKV-4-pile-14B',
	'chater_list_chatgpt_Model19' => 'RWKV-Raven-14B',
	'chater_list_chatgpt_Model20' => 'OpenLLaMA-7B',
	'chater_list_chatgpt_Model21' => 'Dolly-12B',
	'chater_list_chatgpt_Model22' => 'MPT-7B-Instruct',
	'chater_list_chatgpt_Model23' => 'MPT-30B-instruct',
	'chater_list_chatgpt_Model24' => 'OA-Pythia-12B-SFT-4',
	'chater_list_chatgpt_Model25' => 'Falcon-180B-Chat',
	'chater_list_chatgpt_Model26' => 'RWKV-5-World',
	'chater_list_chatgpt_Model27' => 'Flan-UL2',
	
	'chater_ro_title' => '入口管理',
	'chater_ro_add' => '添加入口',
	'chater_ro_delete' => '刪除入口',
	'chater_ro_name' => '名稱',
	'chater_ro_desc' => '描述',
	'chater_ro_dt' => '創建時間',
	'chater_ro_status' => '狀態',
	'chater_ro_to_type' => '群聊',
	'chater_ro_order' => '排序',
	'chater_ro_up' => '上移',
	'chater_ro_down' => '下移',
	'chater_ro_attributes' => '屬性',
	'chater_ro_member' => '成員',
	'chater_ro_tree_title' => '選擇成員',
	
	'user_ro_title' => '訪客標籤管理',
	'user_ro_add' => '添加標籤',
	'user_ro_delete' => '刪除標籤',
	'user_ro_name' => '名稱',
	'user_ro_desc' => '描述',
	'user_ro_dt' => '創建時間',
	'user_ro_status' => '狀態',
	'user_ro_order' => '排序',
	'user_ro_up' => '上移',
	'user_ro_down' => '下移',
	'user_ro_attributes' => '屬性',
	
	'chater_theme_title' => '會話主題管理',
	'chater_theme_add' => '添加主題',
	'chater_theme_delete' => '刪除主題',
	'chater_theme_name' => '名稱',
	'chater_theme_desc' => '描述',
	'chater_theme_dt' => '創建時間',
	'chater_theme_status' => '狀態',
	'chater_theme_order' => '排序',
	'chater_theme_up' => '上移',
	'chater_theme_down' => '下移',
	'chater_theme_attributes' => '屬性',
	'chater_theme_ro' => '主題分組',
	'chater_theme_ro1' => '使用主題',
	'chater_theme_ro2' => '歷史主題',	
	
	'chater_domain_title' => '跳轉後的域名',
	'chater_domain_add' => '添加域名',
	'chater_domain_delete' => '刪除域名',
	'chater_domain_name' => '跳轉後的域名地址',
	'chater_domain_desc' => '描述',
	'chater_domain_dt' => '創建時間',
	'chater_domain_status' => '狀態',
	'chater_domain_order' => '排序',
	'chater_domain_name_desc' => '例如http://www.haoqiniao.cn:98或https://www.haoqiniao.cn',
	
	'chater_wechat_title' => '微信公眾號/小程式管理',
	'chater_wechat_add' => '添加公眾號/小程式',
	'chater_wechat_delete' => '删除公眾號/小程式',
	'chater_wechat_upload' => '上傳驗證文件',
	'chater_wechat_dt' => '創建時間',
	'chater_wechat_status' => '狀態',
	
	//admin/lv_manager/file_edit.php
	'file_edit_lb_name' => '鏈接名稱',
	'file_edit_lb_path' => '鏈接路徑',
	'file_edit_attach' => '上傳附件',
	'file_edit_btn_upload' => '上傳',
	
	//admin/lv_manager/file_list.php
	'file_list_title' => '附件管理',
	'file_list_btn_add' => '新增公共文件',
	'file_list_btn_delete' => '刪除文件',
	'file_list_dropdown_type-1' => '--所有類型--',
	'file_list_dropdown_type1' => '訪客發送',
	'file_list_dropdown_type0' => '客服發送',
	'file_list_filed_account' => '客服帳號',
	'file_list_filed_username' => '訪客姓名',
	'file_list_filed_chatid' => '會話ID',
	'file_list_filed_filename' => '文件名',
	'file_list_ph_key' => '關鍵字',
	'file_list_ph_date' => '日期',
	'file_list_table_chatid' => '會話ID',
	'file_list_table_filename' => '文件名',
	'file_list_table_username' => '訪客',
	'file_list_table_chater' => '客服',
	'file_list_table_createdate' => '創建時間',
	'file_list_edit' => '編輯',
	'file_list_delete' => '刪除',
	'file_list_alert' => '下載錯誤',
	
	//admin/lv_manager/link_edit.php
	'link_edit_lb_owner' => '所屬者',
	'link_edit_option' => '--公共--',
	'link_edit_lb_name' => '鏈接名稱',
	'link_edit_lb_path' => '鏈接路徑',
	'link_edit_attach' => '上傳附件',
	'link_edit_btn_upload' => '上傳',
	
	
	//admin/lv_manager/link_list.php
	'link_list_title' => '鏈接管理',
	'link_list_btn_add' => '新增鏈接',
	'link_list_ph_search' => '查找鏈接',
	'link_list_table_name' => '名稱',
	'link_list_table_address' => '地址',
	'link_list_table_owner' => '所屬者',
	'link_list_table_createdate' => '創建時間',
	'link_list_edit' => '編輯',
	'link_list_delete' => '刪除',
	
	//admin/lv_manager/question_edit.php
	'question_edit_lb_subject' => '問題',
	'question_edit_lb_usertext' => '答案',
	'question_edit_lb_usertext_desc' => '請輸入答案',
	
	
	//admin/lv_manager/question_list.php
	'question_list_title' => '問答庫',
	'question_list_btn_add' => '新增問題',
	'question_list_ph_search' => '查找問題',
	'question_list_table_name' => '問題',
	'question_list_table_address' => '答案',
	'question_list_table_createdate' => '創建時間',
	'question_list_edit' => '編輯',
	'question_list_delete' => '刪除',

	'quicktalk_edit_lb_subject' => '標題',
	'quicktalk_edit_lb_usertext' => '內容',
	'quicktalk_edit_lb_usertext_desc' => '請輸入標題',
	
	//admin/lv_manager/question_list.php
	'quicktalk_list_title' => '常用語管理',
	'quicktalk_list_btn_add' => '新增常用語',
	'quicktalk_list_ph_search' => '查找常用語',
	'quicktalk_list_table_name' => '標題',
	'quicktalk_list_table_address' => '內容',
	'quicktalk_list_table_createdate' => '創建時間',
	'quicktalk_list_edit' => '編輯',
	'quicktalk_list_delete' => '刪除',


	//admin/lv_manager/message_list.php
	'message_list_title' => '留言管理',
	'message_list_groupid' => '請選擇來源',
	'message_list_not' => '公共會話',
	'message_list_option_username' => '姓名',
	'message_list_option_phone' => '電話',
	'message_list_option_email' => '郵箱',
	'message_list_option_content' => '內容',
	'message_list_option_userid' => '用戶ID',
	'message_list_ph_key' => '關鍵字',
	'message_list_ph_date' => '留言日期',
	'message_list_table_source' => '來源',
	'message_list_table_username' => '姓名',
	'message_list_table_phone' => '電話',
	'message_list_table_email' => '郵箱',
	'message_list_table_createtime' => '時間',
	'message_list_table_note' => '內容',
	
	//admin/lv_manager/rate_list.php
	'rate_list_title' => '評價管理',
	'rate_list_option_account' => '客服帳號',
	'rate_list_option_username' => '訪客姓名',
	'rate_list_option_userid' => '會話ID',
	'rate_list_ph_key' => '關鍵字',
	'rate_list_ph_date' => '會話日期',
	'rate_list_table_chatid' => '會話ID',
	'rate_list_table_operator' => '客服',
	'rate_list_table_userid' => '用戶ID',
	'rate_list_table_name' => '姓名',
	'rate_list_table_score' => '評分',
	'rate_list_table_des' => '說明',
	'rate_list_table_date' => '時間',
	
	'blackip_list_title' => '黑名單ip記錄',
	'blackip_list_option_account' => '客服帳號',
	'blackip_list_option_username' => '訪客姓名',
	'blackip_list_option_userid' => '會話ID',
	'blackip_list_ph_key' => '關鍵字',
	'blackip_list_ph_date' => '會話日期',
	'blackip_list_table_chatid' => '會話ID',
	'blackip_list_table_operator' => '客服',
	'blackip_list_table_userid' => '用戶ID',
	'blackip_list_table_name' => '姓名',
	'blackip_list_table_score' => '評分',
	'blackip_list_table_des' => '說明',
	'blackip_list_table_date' => '時間',
   

	//admin/lv_manager/user_list.php
	'user_list_title' => '訪客管理',
	'user_list_option_name' => '姓名',
	'user_list_option_phone' => '電話',
	'user_list_option_email' => '郵箱',
	'user_list_ph_key' => '關鍵字',
	'user_list_table_name' => '姓名',
	'user_list_table_phone' => '電話', //'
	'user_list_table_email' => '郵箱',
	'user_list_table_chater' => '優先接待客服',
	'user_list_table_remarks' => '備註',
	'user_list_table_regtime' => '註冊時間',
	'user_list_table_chat' => '交談',
	'user_list_table_message' => '留言',
	'user_list_table_attach' => '附件',
	
	
	//admin/report/attach_list.php
	'attach_list_tittle' => '附件查詢',
	'attach_list_ph_search' => '附件查找',
	'attach_list_table_messageid' => '消息ID',
	'attach_list_table_sender' => '發送者',
	'attach_list_table_recipient' => '接收者',
	'attach_list_table_senddate' => '發送時間',
	'attach_list_table_content' => '消息內容',
	'attach_list_table_filename' => '文件名',
	'attach_list_table_filesize' => '大小',
	'attach_list_table_filetype' => '類型',
	'attach_list_table_fileguid' => '文件ID',
	'attach_type_screenhot' => '截圖',
	'attach_type_file' => '普通文件',
	
	//admin/report/board_list.php
	'board_list_title' => '公告查詢',
	'board_list_option_title' => '標題',
	'board_list_option_creator' => '發送者',
	'board_list_table_title' => '標題',
	'board_list_table_creator' => '發送者',
	'board_list_table_senddate' => '發送日期',
	'board_list_delete' => '刪除',
	
	//admin/report/chat_list.php
	'chat_list_title' => '對話查詢',
	'chat_list_txt_account1' => '帳號1:', //':'
	'chat_list_txt_account2' => '帳號2:', //':'
	'chat_list_txt_account3' => '群組號碼:', //':'
	'chat_list_txt_account4' => '客服帳號:', //':'
	'chat_list_txt_account5' => '訪客帳號:', //':'
	'chat_list_alert_none' => '沒有數據',
	'chat_list_alert_enteraccount' => '請輸入對話人員帳號',
	
	//admin/report/log_list.php
	'log_list_title' => '登錄日誌',
	'log_list_option' => '登錄/退出',
	'log_list_option1' => '登錄',
	'log_list_option2' => '退出',
	'log_list_option3' => '控制臺登錄',
	'log_list_ph_search' => '查找帳號',
	'log_list_table_account' => '帳號',
	'log_list_table_name' => '姓名',
	'log_list_table_date' => '時間',
	'log_list_table_sign' => '登錄/退出',
	'log_list_table_ip' => 'IP地址',
	'log_list_table_mac' => 'MAC地址',
	
	
	//admin/report/msg_list.php
	'msg_list_title' => '消息查詢',
	'msg_list_option_subject' => '標題',
	'msg_list_option_senderaccount' => '發送帳號',
	'msg_list_option_sendername' => '發送姓名',
	'msg_list_table_subject' => '標題',
	'msg_list_table_sender' => '發送者',
	'msg_list_table_receiver' => '接收者',
	'msg_list_table_senddate' => '發送日期',
	'msg_list_table_datapath' => '數據目錄',
	'msg_list_table_sendermac' => 'MAC地址',
	'msg_list_table_senderip' => 'IP地址',
	'msg_list_table_chat' => '進入聊天',
	'msg_list_groupid' => '請選擇群組',
	'msg_list_pid' => '請選擇入口',
	
	
	//admin/report/msg_total.php
	'msg_total_title' => '消息統計',
	'msg_total_option_subject' => '標題',
	'msg_total_option_sender' => '發送者',
	'msg_total_table_subject' => '標題',
	'msg_total_table_sender' => '發送者',
	'msg_total_table_senddate' => '發送日期',
	'msg_total_table_datapath' => '數據目錄',
	'msg_total_table_sendermac' => 'MAC地址',
	'msg_total_table_senderip' => 'IP地址',
	
	
	//admin/report/online_list.php
	'online_list_title' => '在線用戶',
	'online_list_onlineuser' => '在線用戶: ',
	'online_list_totaluser' => '總用戶數: ',
	'online_list_table_account' => '帳號',
	'online_list_table_user' => '用戶',
	'online_list_table_logintime' => '登陸時間',
	'online_list_table_manufacturer' => '品牌',
	'online_list_table_mac' => 'MAC地址',
	'online_list_table_ip' => 'IP地址',
	'online_list_table_version' => '狀態',
	'online_list_table_usericoLine1' => '在線',
	'online_list_table_usericoLine2' => '離開',
	'online_list_table_usericoLine3' => '手機在線',
	
	//admin/report/sms_list.php
	'sms_list_title' => '短信統計',
	'sms_list_btn_batchdel' => '批量刪除',
	'sms_list_table_sender' => '發送者',
	'sms_list_table_content' => '內容',
	'sms_list_table_recipient' => '接收者',
	'sms_list_table_sendtime' => '發送時間',
	'sms_list_table_status' => '狀態',
	'sms_list_delete' => '刪除',
	
	//admin/report/sms_recv_list.php
	'sms_recv_list_title' => '短信接收',
	'sms_recv_list_btn_batchdel' => '批量刪除',
	'sms_recv_list_table_content' => '內容',
	'sms_recv_list_table_recipient' => '接收者',
	'sms_recv_list_table_sendtime' => '發送時間',
	'sms_recv_list_table_status' => '狀態',
	'sms_recv_list_delete' => '刪除',
	
	//admin/set/base.php   
	'base_title' => '基本設置',
	'base_alert_success' => '修改成功。',
	'base_lb_companyname' => '單位名',
	'base_lb_companyid' => '單位ID',
	'base_lb_port' => '端口號',
	'base_lb_directory' => '數據目錄',
	'base_btn_save' => '保存設置',
	
	//admin/set/board_send.php 
	'board_send_title' => '發送公告',
	'board_send_alert_success' => '發送成功。 ',
	'board_send_lb_psw' => '發送密碼',
	'board_send_lb_type' => '發送類型',
	'board_send_lb_onlineuser' => '在線用戶',
	'board_send_lb_alluser' => '全部用戶',
	'board_send_lb_content' => '發送內容',
	'board_send_btn_publish' => '發送公告',
	
	//admin/set/dw.php 
	'dw_title' => '個性化設置',
	'dw_alert_success' => '修改成功。',
	'dw_lb_unify' => '統壹頭像',
	'dw_recommend' => '推薦用95*95像素',
	'dw_clear' => '清除頭像',
	'dw_save' => '保存設置',
	
	
	//admin/set/ios_set.php
	'ios_set_lb_psw' => 'Api主密碼',
	'ios_set_ph_psw' => 'iOS API主密碼',
	
	//admin/set/port_edit.php
	'port_edit_lb_port' => '端口',
	'port_edit_ph_port' => '端口',
	
	
	//admin/set/service.php
	'service_title' => '服務控制',
	'service_btn_launch' => '啟動服務',
	'service_btn_restart' => '重啟服務',
	'service_btn_stop' => '停止服務',
	'service_table_name' => '名稱',
	'service_table_des' => '描述',
	'service_table_portaddress' => '端口地址',
	'service_table_porttype' => '端口類型',
	'service_table_status' => '狀態',
	'service_table_change' => '修改',
	'service_data_messge' => '消息服務器',
	'service_data_video' => '視頻服務器',
	'service_data_doc' => '文檔服務',
	'service_data_file' => '文件服務',
	'service_data_meeting' => '會議服務',
	'service_data_meetingforward' => '會議中轉服務',
	'service_data_main' => '主服務器',
	'service_data_netrelay' => 'p2p傳輸服務',
	'service_data_site' => 'php web服務',
	'service_data_upload' => '上傳服務',
	'service_data_download' => '下載服務',
	'service_data_telnet'=>'遠程服務',
	'service_data_setverpic' => '圖片傳輸服務',
	'service_data_zlchat' => '視頻會議-主服務',
	'service_data_apache' => '視頻會議-web服務',
	'service_data_mysql' => '視頻會議-數據庫服務器',
	
	
	//admin/set/set.php
	'set_title' => '系統設置',
	'set_alert_success' => '設置成功。',
	'set_alert_restart' => '您需要重新啟動服務才能生效',
	'set_alert_restartnow' => '立即重啟',
	'set_legend_server' => '服務端設置',
	'set_legend_client' => '客戶端配置',
	'set_legend_integrate' => '系統集成設置',
	'set_legend_webserver' => 'Web管理端配置',
	'set_checkbox_disable_save' => '禁止服務端保存消息',
	'set_checkbox_enable_permission' => '啟用組織權限控制',
	'set_checkbox_system' => '啟動系統驗證',
	'set_checkbox_verify' => '啟動Active Directory驗證用戶',
	'set_checkbox_disable_bulletin' => '禁止公告',
	'set_checkbox_disable_changepsw' => '禁止客戶端修改密碼',
	'set_checkbox_disable_groupsharefile' => '禁止群共享文件',
	'set_checkbox_disable_creategroup' => '禁止客戶端創建群組',
	'set_checkbox_allow_creategroup_board' => '允許創建經紀群',
	'set_checkbox_search' => '過濾搜索',
	'set_checkbox_delete' => '自動清除',
	'set_checkbox_days' => '天前的消息及文件',
	'set_btn_manually' => '手動清除消息',
	'set_checkbox_record' => '記錄登陸日誌信息',
	'set_checkbox_directory' => '數據存放的目錄',
	'set_checkbox_datasync' => '啟用數據同步推送',
	'set_datasync_url' => '數據同步地址',
	'set_checkbox_disable_saving' => '禁止客戶端保存消息',
	'set_checkbox_disable_hyperlink' => '禁止客戶端的超級鏈接',
	'set_checkbox_disable_invisible' => '禁止客戶端顯示脫機',
	'set_checkbox_allow_p2p' => '允許文件P2P傳輸',
	'set_checkbox_p2p_threshold' => '閥值',
	'set_checkbox_disable_note' => '禁止客戶端顯示對方打開消息的通知',
	'set_checkbox_away' => '支持自動離開功能',
	'set_checkbox_minutes' => '分',
	'set_checkbox_disable_mylink' => '禁止網址收藏功能',
	'set_checkbox_enable_online' => '啟用多設備同時在線',
	'set_checkbox_enable_forwarding' => '啟用音視頻中轉服務',
	'set_checkbox_enable_loginverify' => '啟用第三方登錄驗證（需定制開發）',
	'set_loginverify_url' => '接入第三方應用驗證地址',  
	'set_antserver_access_url' => '接入Server推送地址', 
	'set_push' => 'IOS推送設置',
	'set_btn_setting' => '設置',
	'set_checkbox_transcode' => '上傳視頻自動轉碼',
	'set_checkbox_publicdocuments_file_type' => '公共檔案某些欄目不顯示',
	'set_checkbox_publicdocuments' => '公共檔案/圖片/音樂/視頻/最近更新/搜索結果不顯示',
	'set_checkbox_publicdocuments_file_type_view' => '公共檔案某些欄目無查看許可權不顯示',
	'set_checkbox_publicdocuments_view' => '公共檔案/圖片/音樂/視頻/最近更新/搜索結果如果沒有查看許可權不顯示(啟用後將新增服務器負擔)',
	'set_livechat' => '在線值班',
	'set_openplatform' => 'php7或著以上版本',
	'set_inquirybox' => '雲盤上傳同名檔案彈出詢問框(是否替換)',
	'set_enpmessage' => '數據傳輸加密',
	'set_verifyuserdevice'=>'啟用設備號驗證',
	'set_userapply' => '客戶端申請賬號',      
	'set_userapply0' => '需要管理員審核',  
	'set_userapply1' => '申請後即可使用',  
	'set_userapply2' => '禁止申請',  
	'set_chats' => '服務器保存聊天記錄(啟用後將增加服務器負擔)',  
	'set_logs' => '服務器保存事務日誌(啟用後將增加服務器負擔)',  
	'set_control_computer' => '控制電腦(服務端控制客戶端電腦)',
	'set_lock_screen' => '服務器程序啟動後，自動鎖定界面',      
	'set_offline_information' => '離線信息，轉發到手機短信(必須啟用短信功能)',  
	'set_minimize' => '服務器程序啟動後，自動最小化界面',  
	'set_CheckIM0' => '管理員接收系統消息(例如用戶註冊審核,雲盤/群組文件審核)',
	'set_CheckIM1' => '電腦與手機同時在線，電腦版賬號處於在線狀態，手機版賬號也能收到推送消息', 
	'set_delete_chats' => '服務器自動刪除聊天記錄',  
	'set_delete_chats1' => '15天前的記錄',
	'set_delete_chats2' => '60天前的記錄',
	'set_delete_chats3' => '不刪除',
	'set_delete_offline_files' => '服務器自動刪除離線文件',  
	'set_delete_offline_files1' => '15天前的文件',
	'set_delete_offline_files2' => '60天前的文件',
	'set_delete_offline_files3' => '不刪除',
	'set_message_push' => '手機app消息推送間隔',  
	'set_message_push1' => '秒(越小消息推送越快，但同時對服務器資源損耗越大)',
	'set_delete_server_files' => '當服務器文件達到磁盤',
	'set_delete_server_files1' => '%自動刪除服務器文件(防止磁盤爆滿損壞磁盤)',
	'set_delete_offline_notices' => '自動清除',
	'set_noticeday' => '天前的離線通知',
	'set_chatsday' => '天前的聊天記錄',
	'set_port' => '端口說明',
	'set_port_description' => '基本通信通口:97、98、99、5994、5995、5996、5997(udp)、5998(udp)、6001、6002、6003、6004、6005、6006、6007、6008共16個端口,請確保服務器的端口都已經打開。',
	 
	'set_login_error_count' => '後臺登錄錯誤次數限制為',
	'set_login_error_count_tip' => '0為不限制',
	
	//admin/set/skin_list.php
	'skin_list_title' => '皮膚管理',
	'skin_list_show' => '點擊查看大圖',
	'skin_list_preview' => '預覽',
	  
	//admin/set/server_list.php
	'server_list_title' => '服務器管理(多臺即時通訊服務高可用方案)',
	'server_list_ip' => 'IP',
	'server_list_name' => '名稱',
	'server_init_all' => '同步所有服務器初始化數據',
	
	//admin/set/update.php
	'update_type_pc' => 'PC端',
	'update_type_android' => '安卓端',
	'update_title' => '升級管理',
	'update_alert_success' => '導入成功',
	'update_restart' => '您需要重新啟動服務才能生效',
	'update_alert_restartnow' => '立即重啟',
	'update_lb_version' => '版本號',
	'update_ib_package' => '更新包',
	'update_btn_delpackage' => '刪除更新包',
	'update_lb_uploadpackage' => '上傳更新包',
	'update_btn_upload' => '上傳更新包',
	'update_alert_delsuccess' => '刪除成功',
	'update_alert_selectpackage' => '請選擇更新包',
	
	//admin/set/user_change.php
	'user_change_title'  => '人員數據遷移',
	'user_change_old'    => '用戶原賬號',
	'user_change_new'    => '用戶新賬號',         
	'user_change_btn'    => '確認',
	'user_change_warning'=> '提示：這是修改人員賬號後，遷移原賬號消息，公告等數據到新賬號中。請確認是否要修改人員賬號！！！',
	'user_change_require'=> '賬號不允許為空', 
	  
	//admin/tools/addin_edit.php
	'addin_edit_lb_type' => '插件類型',
	'addin_edit_option0' => '插件包',
	'addin_edit_option1' => '命令插件',
	'addin_edit_option2' => '視圖插件',
	'addin_edit_lb_status' => '狀態',
	'addin_edit_option_normal' => '正常',
	'addin_edit_lb_option_disabled' => '禁用',
	'addin_edit_lb_public' => '是否公開',
	'addin_edit_option_yes' => '是',
	'addin_edit_option_no' => '否',
	'addin_edit_lb_sequence' => '排序',
	
	
	//admin/tools/addin_list.php
	'addin_sms' => '短信插件',
	'addin_list_title' => '插件管理',
	'addin_list_btn_search' => '插件查找',
	'addin_list_btn_import' => '導入插件',
	'addin_list_btn_add' => '新增插件',
	'addin_list_btn_permission' => '設置權限',
	'addin_list_btn_delete' => '刪除插件',
	'addin_list_install' => '安裝系統插件',
	'addin_list_roam' => '消息漫遊',
	'addin_list_bulletin' => '公告查詢',
	'addin_list_operator' => '在線客服',
	'addin_list_option_type' => '選擇類型',
	'addin_list_option_command' => '命令插件',
	'addin_list_option_view' => '視圖插件',
	'addin_list_ph_search' => '插件查找',
	'addin_list_table_type' => '類別',
	'addin_list_table_name' => '名稱',
	'addin_list_table_public' => '公開',
	'addin_list_table_disable' => '禁用',
	'addin_list_table_desc' => '描述',
	'addin_list_table_package' => '插件包',
	'addin_list_table_sequence' => '排序',
	'addin_list_table_edit' => '修改',
	'addin_list_table_permission' => '權限',
	'addin_list_table_del' => '刪除',
	'addin_list_table_up' => '上移',
	'addin_list_table_down' => '下移',
	'addin_list_add' => '新增插件',
	'addin_list_edit' => '修改插件',
	'addin_plug_name' => '插件名稱',
	'addin_plug_displayname' => '顯示的名稱',
	'addin_plug_target' => 'url地址',
	'addin_plug_desc' => '描述',
	'addin_plug_width' => '窗口寬度',
	'addin_plug_width_desc' => '打開迷妳窗口的寬度',
	'addin_plug_height' => '窗口高度',
	'addin_plug_height_desc' => '打開迷妳窗口的高度',
	'addin_plug_param' => '參數',
	'addin_plug_image' => '圖片的地址',
	'addin_plug_site' => '插件類型',
	'addin_plug_site0' => '短信',
	'addin_plug_site1' => '郵箱',
	'addin_plug_site2' => 'Main Menu 主菜單',
	'addin_plug_site3' => '用戶卡片',
	'addin_plug_site4' => '用戶卡片按鈕',
	'addin_plug_site5' => '用戶列表選擇壹個人的右鍵菜單',
	'addin_plug_site6' => '群列表選擇群的右鍵菜單',
	'addin_plug_site7' => '手機Main Menu 主菜單',
	'addin_plug_site8' => '手機用戶更多菜單選項',
	'addin_plug_site9' => '手機群組更多菜單選項',
	'addin_plug_site10' => '消息漫遊',
	'addin_plug_site11' => '消息推送',
	'addin_plug_site12' => '實時音視頻',
	'addin_plug_site13' => '消息郵件推送',
	'addin_plug_site14' => '其他',
	'addin_plug_targettype' => '目標程序打開方式',
	'addin_plug_targettype1' => '在客戶端內部打開',
	'addin_plug_targettype2' => '在瀏覽器打開打開',
	'addin_plug_targettype3' => '其他',
	'addin_plug_bie' => '第三方系統編號',
	'addin_plug_enabled' => '狀態',
	'addin_plug_enabled1' => '正常',
	'addin_plug_enabled0' => '禁用',
	'addin_plug_warning' => '第三方系統編號必須是正整數',
	'addin_plug_warning1' => '系統內置插件不允許此操作',
	'addin_plug_warning2' => '在線文檔插件已關閉',
	
	//admin/tools/client_edit.php
	'client_edit_lb_title' => '上傳客戶端',
	'client_edit_lb_name' => '客戶端名稱',
	'client_edit_ph_name' => '客戶端名稱',
	'client_edit_lb_version' => '版本號',
	'client_edit_ph_version' => '客戶端版本',
	
	
	//admin/tools/client_list.php
	'client_list_lb_title' => '客戶端程序發布',
	'client_list_btn_add' => '新增客戶端',
	'client_list_btn_delete' => '刪除客戶端',
	'client_list_ph_search' => '查找客戶端名稱或版本',
	'client_list_table_name' => '客戶端名稱',
	'client_list_table_version' => '版本',
	'client_list_table_size' => '大小',
	'client_list_table_edit' => '編輯',
	'client_list_table_download' => '下載鏈接',
	'client_list_table_del' => '刪除',
	
	
	
	//admin/tools/dept_picker.php
	'dept_picker_lb_deletedept' => '刪除以前的部門',
	'dept_picker_alert_adduser' => '不能將人員設置到根節點下',
	
	
	//admin/tools/ext_edit.php
	'ext_edit_option_ADSServer' => '文檔服務地址',
	'ext_edit_option_ADSPort' => '文檔服務端口',
	'ext_edit_option_AVServerAddr' => '音視頻服務地址',
	'ext_edit_option_AVServerPort' => '音視頻服務端口',
	'ext_edit_option_FileServerAddr' => '文件服務地址',
	'ext_edit_option_FileServerPort' => '文件服務端口',
	'ext_edit_option_RoamingMessageUrl' => '漫遊消息地址',
	'ext_edit_lb_data' => '數據',
	'ext_edit_lb_type' => '種類',
	
	
	//admin/tools/ext_list.php
	'ext_list_title' => '擴展屬性',
	'ext_list_btn_add_custom' => '自定義擴展',
	'ext_list_btn_add_sys' =>'系統擴展',    
	'ext_list_btn_bulid' => '生成系統配置',
	'ext_list_ph_search' => '屬性查找',
	'ext_list_table_name' => '名稱',
	'ext_list_table_desc' => '描述',
	'ext_list_table_data' => '數據',
	'ext_list_table_edit' => '修改',
	'ext_list_table_del' => '刪除',
	'ext_list_col_ADSServer' => '文檔服務地址',
	'ext_list_col_ADSPort' => '文檔服務端口',
	'ext_list_col_AVServerAddr' => '音視頻服務地址',
	'ext_list_col_AVServerPort' => '音視頻服務端口',
	'ext_list_col_FileServerAddr' => '文件服務地址',
	'ext_list_col_FileServerPort' => '文件服務端口',
	'ext_list_col_RoamingMessageUrl' => '漫遊消息地址',
	'ext_list_add' => '新增屬性',
	'ext_list_change' => '修改屬性',
	
	
	//admin/tools/interface_edit.php
	'interface_edit_lb_name' => '名稱',
	'interface_edit_lb_address' => '地址',
	'interface_edit_lb_public' => '公開',
	'interface_edit_public_yes' => '是',
	'interface_edit_public_no' => '否',
	'interface_edit_lb_status' => '狀態',
	'interface_edit_status0' => '正常',
	'interface_edit_status1' => '禁用',
	'interface_edit_lb_desc' => '描述',
	'interface_edit_lb_sequence' => '排序',
	'interface_edit_lb_type' => '類型',
	'interface_edit_type0' => '全部',
	'interface_edit_type1' => 'PC端應用',
	'interface_edit_type2' => 'Android應用',
	'interface_edit_type3' => 'iOS應用',
	'interface_edit_entername' => '請輸入名稱',
	'interface_edit_enteraddress' => '請輸入地址',
	
	
	//admin/tools/interface_list.php
	'interface_list_title' => '接口管理',
	'interface_list_btn_add' => '新增接口',
	'interface_list_btn_batch' => '批量操作',
	'interface_list_dropdown_permission' => '設置權限',
	'interface_list_dropdown_del' => '刪除',
	'interface_list_ph_search' => '接口查找',
	'interface_list_table_name' => '名稱',
	'interface_list_table_address' => '地址',
	'interface_list_table_type' => '類型',
	'interface_list_table_disable' => '禁用',
	'interface_list_table_sequence' => '排序',
	'interface_list_table_edit' => '修改',
	'interface_list_table_permission' => '權限',
	'interface_list_table_del' => '刪除',
	'interface_list_table_up' => '上移',
	'interface_list_table_down' => '下移',
	'interface_list_type0' => '全部',
	'interface_list_type1' => 'PC端應用',
	'interface_list_type2' => 'Android應用',
	'interface_list_type3' => 'iOS應用',
	'interface_list_add' => '新增接口',
	'interface_list_change' => '修改接口',
	
	
	//admin/tools/sms_account.php
	'sms_account_title' => '短信帳號',
	'sms_account_btn_assign' => '分配',
	'sms_account_table_account' => '帳號',
	'sms_account_table_psw' => '密碼',
	'sms_account_table_dept' => '部門',
	'sms_account_table_edit' => '修改',
	'sms_account_table_del' => '刪除',
	
	
	//admin/tools/sms_account_edit.php
	'sms_account_edit_lb_account' => '發送帳號',
	'sms_account_edit_lb_psw' => '發送密碼',
	'sms_account_edit_lb_dept' => '選擇部門',
	'sms_account_edit_btn_select' => '選擇部門',
	
	'field_online_lasttime' => '最後登錄',
	'field_online_status' => '是否在線',
	
	//admin/tools/view_url.php
	'view_url_link' => '下載鏈接',
	
	'valid_db_connect_error' => '數據庫連接失敗，請檢查連接配置或重新設置連接',
	
	
	'imp_map_warning' => '屬性項用tab鍵分隔,多行間用換行符分開',
	'btn_impmap' => '導入人員映射',
	
	'update_software_upgrade' => '軟件升級',
	'update_product_website' => '產品網址',
	'update_warning' => '軟件不是最新版,請打開www.haoqiniao.cn下載最新版或聯系客服獲取離線升級包.',
	'update_download' => '下載離線升級包',
	
	'set_client_configuration' => '客戶端安裝包配置',
	'set_client_warning' => '生成客戶端安裝包成功。',
	'set_client_download' => '立即下載',
	'set_client_basic_settings' => '基本設置',
	'set_client_WebName' => '公司名稱',
	'set_client_WebNa' => '快捷方式',
	'set_client_WebNa_desc' => '客戶端電腦顯示的軟件快捷方式',
	'set_client_WebRun' => '客戶端啟動時，彈出網站',
	'set_client_logo' => '公司logo',
	'set_client_edit_logo' => '更改logo',
	'set_client_delete_logo' => '清除logo',
	'set_client_banner' => '公司banner',
	'set_client_edit_banner' => '更改banner',
	'set_client_delete_banner' => '清除banner',
	'set_client_pan' => '雲盤logo',
	'set_client_server_connection' => '服務器連接',
	'set_client_ServerIp' => 'IP地址',
	'set_client_ServerIp_desc' => '多個ip以逗號隔開',
	'set_client_Option1' => '連接方式',
	'set_client_Option10' => 'IP地址',
	'set_client_Option11' => '域名',
	'set_client_Option12' => '計算機名稱',
	'set_client_Server_CheckIM1' => '自動登錄',
	'set_client_Server_CheckIM2' => '記住密碼',
	'set_client_software_settings' => '軟件設置',
	'set_client_CheckIM0' => 'Windows系統啟動時,啟用本軟件',
	'set_client_CheckIM1' => '主面板，總顯示前面',
	'set_client_CheckIM2' => '使用大圖標',
	'set_client_CheckIM3' => '應用聲音主題效果',
	'set_client_CheckIM4' => '自動彈出信息窗體',
	'set_client_CheckIM5' => '禁止所有提示（信息）',
	'set_client_CheckIM6' => '文件傳輸完成後,打開所在文件夾',
	'set_client_CheckIM7' => '啟用熱鍵功能',
	'set_client_CheckIM8' => '禁止用戶名片提示',
	'set_client_CheckIM9' => '登錄時更新數據',
	'set_client_CheckIM11' => '合並會話窗口',
	'set_client_CheckIM13' => '截屏時隱藏窗口',
	'set_client_CheckIM14' => '文本模式',
	'set_client_CheckTab5' => '顯示系統郵箱按鈕',
	'set_client_CheckTab6' => '顯示雲盤按鈕',
	'set_client_CheckTab9' => '顯示主菜單按鈕',
	'set_client_CheckTab10' => '顯示高級設置',
	'set_client_CheckTab11' => '顯示所有消息記錄按鈕',
	'set_client_CheckTab12' => '顯示文件助手按鈕',
	'set_client_CheckTab13' => '顯示收藏按鈕',
	'set_client_CheckTab14' => '顯示查找按鈕',
	'set_client_HotKey0' => '提取消息快捷鍵',
	'set_client_HotKey1' => '屏幕截屏快捷鍵',
	
	'msg_list_expired'=> '本功能已過期,請聯繫客服購買授權',
	//admin/tools/keywords_list
	'keywords_type'=>'過濾類型',
	'keywords_content'=>'過濾內容',
	'enable_keyword'=>'啟用敏感詞過濾',
	'enable_customerservicemode'=>'客服模式',
	'keywords_type_one'=> '方案一：過濾詞變*發送',
	'keywords_type_two'=> '方案二：有過濾詞不能發送'
)
;
?>
