<?php
return array(
	'sample' => 'example',
	'url' => 'address',
	'attach' => 'attachment',
	'attach_size' => 'size',
	'download' => 'download',
	'msg_file_error' => 'Message file is deleted',
	'file_error' => 'File does not exist',
	'no_power' => 'no permission',
	'index_service' =>'Service',
	
	'msg_file_error' => 'Message file is deleted',
	'msg_recv_pic' => 'receive new image file',
	'msg_recv_sound' => 'receive new voice file',
	'msg_recv_attach' => 'receive new attachment',
	'msg_recv_chatgpt'  => '[Small touch robot has replied]' ,
	'msg_recv_chatgpt1'  => 'The small touch robot is not turned on, please contact the administrator!' ,
	'msg_recv_chatgpt2'  => 'The API Key of the small touch robot cannot be empty, please contact the administrator!' ,
	'msg_recv_chatgpt12'  => 'The Secret Key of the small touch robot cannot be empty, please contact the administrator!' ,
	'msg_recv_chatgpt13'  => 'The API address of the small touch robot cannot be empty, please contact the administrator!' ,
	
	'viewport_org' => 'Organization',
	'doc_manager_public' => 'public document',
	'customer_service_list' => 'Customer list',
	
	'valid_file_type_error' => 'The file type is incorrect',
	'valid_file_not_exist' => 'File does not exist',
	'valid_upload_size_limit' => 'Upload file cannot exceed [{FileSize}M]',
	'valid_local_limit' => 'Only operate on the server',
	
	'error_db_connect_error' => 'Connection failed! If using the softwares built-in database, please wait for all pop-up plugins to be installed before configuring the database; If using a database already installed on the server, please check if the database information is correct',
	
	'sn_path_error' => 'Configured server path error',
	'sn_activation_error' => 'Activation code error',
	'sn_machine_error' => 'Activation code error [machine code does not match]',
	'ad_connect_fail' => 'AD server connection failed',
	
	'module_doc_manager' => 'shared document',
	
	'grant_exist' => 'User has authorized this department',
	'grant_beyond' => 'Exceeded the number of authorized persons',
	
	'file' => 'file',
	'folder' => 'folder',
	'cloud_isexists' => 'Already exists! ',
	'cloud_authority_error' => 'You dont have permission to download',
	'cloud_download' => 'Download cloud file',
	'cloud_download_leavefile' => 'Download offline file',
	'cloud_download_onlinefile' => 'download online file',
	'cloud_delete_leavefile' => 'Delete offline files',
	'cloud_delete_clotfile' => 'Delete group file',
	'cloud_delete_onlinefile' => 'Delete online documents',
	'cloud_file' => 'cloud disk file',
	'cloud_clotfile' => 'group file',
	'cloud_error' => 'Please do not upload in the root directory',
	'cloud_error1' => 'Please wait for the administrator to pass the review',
	'cloud_error2' => 'You dont have permission to modify',
	'cloud_error3' => 'You dont have permission to delete',
	'cloud_error4' => 'You dont have permission management',
	'cloud_error5' => 'Saved successfully, please wait for the administrator to pass the audit!',
	'cloud_error6' => 'Data does not exist',
	'cloud_error7' => 'You dont have permission to create',
	'cloud_error8' => 'Already exists',
	'cloud_error9' => 'This folder has no files',
	'cloud_error10' => 'There are illegal characters',
	'cloud_revisedfile1' => 'Restore the document to the ',
	'cloud_revisedfile2' => 'version',
	'cloud_create_folder' => 'Create folder',
	'cloud_warning' => 'Modify shared member as',
	'cloud_warning1' => 'file sharing',
	'cloud_warning2' => 'Exit sharing',
	'cloud_warning3' => 'Add shared member',
	'cloud_warning4' => 'Delete shared members',
	'cloud_warning5' => 'Download multiple cloud disk files',
	'cloud_warning6' => 'Download multiple offline files',
	'cloud_warning7' => 'Currently',
	'cloud_warning8' => 'M, the package file size is limited to ',
	'cloud_warning9' => 'files, the number of package files is limited to ',
	'cloud_warning10' => '个',
	'cloud_warning11' => 'File sharing has updates, hurry to see what new content has been added! ',
	'cloud_warning12' => 'You have become',
	'cloud_warning13' => 'A member of the file sharing, hurry to see what good content to put! ',
	'cloud_warning14' => 'You have been removed from this file share! ',
	'cloud_warning15' => 'Exit file sharing! ',
	'cloud_warning16' => 'Uploaded the file, please pass the review! ',
	'cloud_warning17' => 'Please delete the child node first!',
	'cloud_warning18' =>'Failed to move part of the file with duplicate files!',
	
	'docdir_error' => 'Illegal path',
	'docdir_error1' => 'path error',
	
	'fun_error' => 'Illegal login',
	'fun_error1' => 'Re-login',
	
	'import_export_start_time' => 'Start import time',
	'import_export_end_time' => 'Start import time',
	'import_export_warning' => 'AD server connection failed',
	'import_export_warning1' => 'coming in',
	'import_export_warning2' => 'no data',
	'import_export_warning3' => 'The format is incorrect',
	
	'install_warning' => 'Installation completed',
	
	'role_warning' => 'A role created with one click. ',
	
	'class_site_warning' => 'Only on the server, please open ',
	'class_site_warning1' => 'If the page is blank, please use a higher version browser!',
	'class_thumbHandler_warning' => 'The picture does not exist',
	'class_thumbHandler_warning1' => 'The image source is empty',
	'class_thumbHandler_warning2' => 'Font file does not exist',
	'class_thumbHandler_warning3' => 'The image scaling should not be less than 1',
	'class_thumbHandler_warning4' => 'The target width cannot be 0',
	'class_thumbHandler_warning5' => 'The target height cannot be 0',
	'class_thumbHandler_warning6' => 'Watermark text too large',
	'class_thumbHandler_warning7' => 'The watermark image is empty',
	'class_thumbHandler_warning8' => 'The picture border is too large, has exceeded the width of the picture',
	'class_thumbHandler_warning9' => 'The watermark image size is larger than the original image, please narrow the watermark image',
	'class_thumbHandler_warning10' => 'The file does not exist, the file type cannot be obtained!',
	'class_thumbHandler_warning11' => 'Watermark picture is empty',
	
	'class_doc_warning' => 'directory',
	'class_doc_warning1' => 'does not exist',
	'class_doc_warning2' => 'Upload cloud file',
	'class_doc_warning3' => 'Delete cloud file',
	'class_doc_warning4' => 'will',
	'class_doc_warning5' => 'Save to cloud disk',
	'class_doc_warning6' => 'personal document',
	'class_doc_warning7' => 'The filename contains special characters',
	'class_doc_warning8' =>'Cannot upload special files',
	'class_doc_warning9' =>'The folder name contains special characters',
	'class_doc_warning10' => 'File upload failed',
	'class_doc_warning11' => 'Upload and overwrite cloud disk files with the same name',
	'class_doc_warning12' => 'Upload file',
	'class_doc_warning13' => 'Failed due to the file size being too large',
	'class_doc_warning14' => 'Failed, reason directory',
	'class_doc_warning15' => 'Failed to upload special file',
	'class_doc_warning16' => 'Delete cloud disk directory',
	
	'class_grant_warning' => 'No permissions to add users',
	'class_grant_warning1' => 'The number of new users has exceeded, up to',
	'class_grant_warning2' => 'people',
	
	'class_hs_warning' => 'The number of data columns does not match the definition',
	'class_hs_warning1' => 'already exists',
	'class_hs_warning2' => 'no content',
	
	'class_passport_warning' => 'Login server management background',
	'class_passport_warning1' => 'Log in to the cloud',
	'class_passport_warning2' => 'Log in to online customer service',
	
	'class_msgreader_warning' => 'Successfully sent',
	'class_msgreader_warning1' => 'forward',
	'class_msgreader_warning2' => 'View to the cloud disk',
	'class_msgreader_warning3' => 'business card',
	'class_msgreader_warning4' => 'Send a message',
	'class_msgreader_warning5' => 'group of business cards',
	'class_msgreader_warning6' => 'View',
	
	'class_PHPExcel_UppeID' => 'grouping',
	'class_PHPExcel_UserName' => 'account',
	'class_PHPExcel_FcName' => 'name',
	'class_PHPExcel_UserIco' => 'Gender (1 is male, 2 is female)',
	'class_PHPExcel_Effigy' => 'Other',
	'class_PHPExcel_Tel1' => 'phone',
	'class_PHPExcel_Jod' => 'Position',
	'class_PHPExcel_UserPaws' => 'password',
	'class_PHPExcel_ItemIndex' => 'sort number',
	
	'class_PHPExcel_Col_Ro' =>'Common term grouping',
	'class_PHPExcel_Col_Form' =>'common words',
	
	'online_list_table_account' => 'Account',
	'online_list_table_user' => 'user',
	'online_list_table_logintime' => 'login time',
	'online_list_table_mac' => 'MAC address',
	'online_list_table_ip' => 'IP address',
	'online_list_table_version' => 'status',
	'online_list_table_usericoLine1' => 'Online',
	'online_list_table_usericoLine2' => 'Leave',
	'online_list_table_usericoLine3' => 'Mobile online',
	'field_dept' => 'department',
	'user_list_col_sex' => 'gender',
	'user_edit_lb_gender1' => 'Men',
	'user_edit_lb_gender2' => 'female',
	
	'livechat_message0' =>'Customer service {name} is not online, please leave a message',
	'livechat_message1' => 'Customer service {name} is at your service',
	'livechat_message2' => 'user entry',
	'livechat_message3' => 'User has not replied for a long time, the system will automatically end the session later',
	'livechat_message4' => 'System shut down',
	'livechat_message5' => 'Session transferred to {name}',
	'livechat_message6' => 'Cant chat with yourself',
	'livechat_message7' => 'CustomerService',
	'livechat_message8' => 'Me',
	'livechat_message9' =>'unknown',
	'livechat_message10' =>'Not selected',
	'livechat_message11' =>'not evaluated',
	'livechat_message12' =>'no value',
	'livechat_message13' =>'valuable',
	'livechat_message14' =>'Non-entry conversation',
	'livechat_message15' =>'public conversation',
	'livechat_message16' =>'Online visitors',
	'livechat_message17' =>'Enter',
	'livechat_message18' =>'Guest is not online',
	'livechat_message19' =>'Visitor chatting',
	'livechat_message20' =>'The user clicked on a popular question {name}',
	
	'register_alert1' => 'The system has closed the free application account function, please contact the administrator. ',
	'register_alert2' => 'The user account already exists, please use another user account!',
	'register_alert3' => 'Account application',
	'register_alert4' => 'Apply for an account, please pass the review!',
	'register_alert5' => 'Account cannot contain Chinese',
	'register_alert6' =>'Name cannot contain special characters',
	
	'meeting_alert1' => 'People are',
	'meeting_alert2' => 'voice call',
	'meeting_alert3' => 'video call',
	'meeting_alert4' => 'You are on another device, click to go to this machine.',
	
	'lv_chat_file' =>'[FILE]',
	'lv_chat_location' =>'[Location]',
	'lv_chat_pic' =>'[Picture]',
	'lv_chat_expression' =>'[Expression]',
	'lv_chat_video' =>'[Video]',
	'lv_chat_voice' =>'[Voice Message]',
	'lv_chat_link' =>'[LINK]',
	
	// Document log type
	'type_downloadfile' => 'download file',
	'type_editfile' => 'edit file',
	'type_newfile' => 'create file',
	'type_removefile' => 'move file',
	'type_viewfile' => 'View file',
	'type_deletefile' => 'delete file',
	'type_sharefile' => 'share file',
	'type_login' => 'login',
)
;
?>
