<?php
return array(
    'header_password_dialog' => '修改密码',
	'header_download' => '下载客户端',
    'header_logout' => '退出',
    'header_dropdown' => '帮助',
    'header_register' => '注册',
    'header_about' => '关于',
    'header_login_btn' => '登录',
	
    'menu_dir' => '目录',
	'menu_history' => '最近',
	'menu_doc' => '文档',
    'menu_img' => '图片',
	'menu_create' => '创建',
	
	'originalTitle' => '好奇云',
	'icon_folder_public' => '公共文档',
	'icon_folder_person' => '个人文档',
	'icon_recent' => '最近更新',
	'icon_office' => '文档',
	'icon_pic' => '图片',
	'icon_music' => '音乐',
	'icon_video' => '视频',
	'icon_upload' => '上传',
	'icon_upload1' => '上传大文件',
	'icon_upload2' => '上传单文件',
	'icon_download' => '下载',
	'icon_attr' => '详情',
	'icon_edit' => '重命名',
	'icon_delete' => '删除',
	'icon_share' => '分享',
	'icon_reload' => '刷新',
	'icon_set' => '设置权限',
	'icon_doc_edit' => '编辑',
	'icon_qrcode' => '二维码下载',
	'icon_save' => '保存到云盘',
	'icon_folder_create' => '新建目录',
	'icon_move' => '移动到',
	'dropdown-toggle' => '排序',
	'icon_time' => '按时间排序',
	'icon_az' => '按名称排序',
	'icon_thumb' => '显示缩略图',
	'icon_list' => '显示列表',
	'path_node' => '目录',
	'upload_title' => '个文件传输中',
	'icon_warning' => '新建文件夹成功!',
	'icon_warning1' => '暂无文件',
	'icon_warning2' => '请点击左上角的“上传”按钮添加文件',
	'icon_warning3' => '搜索全部文件',
	'icon_warning4' => '输入文件名并按下回车进行搜索',
	
	'pnl_error' => '帐号或密码错误',
	'pnl_error1' => '请先登录再进行操作',
	'txt_loginname' => '帐号',
	'txt_loginname_desc' => '请输入帐号',
	'txt_password' => '密码',
	'txt_password_desc' => '请输入密码',
	'btn_login' => '登录',
	
	'pnl_success' => '密码修改成功，重新登录生效。',
	'old_password' => '旧密码',
	'new_password' => '新密码',
	'confirm_password' => '确认密码',
	
	'btn_save' => '保存',
	'btn_ok' => '确定',
	'btn_cancel' => '取消',
	'btn_close' => '关闭',
	'btn_cloud_save' => '保存到云盘',
	
	'doc_type_name' => '类型',
	'col_name' => '名称',
	'path' => '路径',
	'doc_attribution' => '归属',
	'col_dt_create' => '创建时间',
	'doc_type_file' => '文件',
	'doc_type_folder' => '文件夹',
	
	'share_url' => '链接',
	'copy_share_url' => '复制链接',
	
	'save_to' => '保存到',
	'move_to' => '移动到',
	'doc_move_alert1' => '个文件/文件夹',
	'doc_move_alert2' => '请选择移动到的目录',
	'doc_move_alert3' => '目标地址不能是原来地址',
	
	'txt_folder_name' => '目录名称',

	'addin_alert' => '在线文档插件已关闭',
	
	'set_authority1' => '对谁公开',
	'set_authority10' => '所有人',
	'set_authority11' => '特定成员',
	'set_authority12' => '仅自己可用',
	'set_authority2' => '获得文档的人',
	'set_authority20' => '选定编辑',
	'set_authority21' => '可以编辑',
	'set_title' => '添加可编辑该文档的成员(选中的成员有编辑权限,其他成员只有查看权限)',
	'set_title1' => '设置特定成员',
	'set_userkey' => '输入帐号或姓名',
	'set_addMemberByInput' => '添加成员',
	'set_edit' => '编辑',
	'set_name' => '姓名',
	'set_account' => '帐号',
	'set_authority3' => '发送消息通知',
	'set_authority30' => '忽略',
	'set_authority31' => '通知',
    'menu_sub_ptp_file' => '云盘文档',
    'menu_sub_group_file' => '群组文件',
    'menu_sub_leave_file' => '离线文件',
    'menu_sub_file_alert1' => '我更新了',
	'menu_sub_file_alert2' => '[系统自动发送]',
	
	'doceditor_title' => '在线文档',
	'doceditor_warning' => '当前仅能查看,登录后可获得更多操作权限',
	'doceditor_read' => '(只读)',
	'doceditor_login_btn' => '登录',
	'doceditor_doc_set' => '权限',
	'doceditor_doc_col' => '收藏',
	'doceditor_doc_share' => '分享',
	'doceditor_logout_btn' => '退出',
	'doceditor_file_empty' => '文件不存在',
	'doceditor_file_empty1' => '您没有权限查看',
	'doceditor_edited_document' => '编辑了文档',
	
	'onlinefile_warning' => '该帐号不存在,验证失败!',
	'onlinefile_warning1' => '该帐号被禁用,验证失败!',
	'onlinefile_warning2' => '该帐号未登录,验证失败',
	'onlinefile_warning3' => '验证失败,令牌无效',
	'onlinefile_icon_recent' => '最近',
	'onlinefile_icon_folder_person' => '我创建的',
	'onlinefile_icon_folder_public' => '与我共享',
	'onlinefile_doc_create1' => '新建文档',
	'onlinefile_doc_create2' => '新建表格',
	
	'col_chk_notall' => '全不选',
	'col_chk_all' => '全选',
	'folder_nav_box' => '保存位置:个人文档',
	'btn_return' => '返回上一级',
	
	'download_title1' => '下载专区',
	'download_title2' => '后台管理',
	'download_title3' => '开发文档',
	'download_title4' => '全国统一服务热线',
	'download_title5' => '官方网站',
	'download_title6' => '当前位置',
	'download_title7' => 'PC版-客户端',
	'download_title8' => '系统环境WinNT/2K/XP/vista/7/8/10/11<br />/server 2003/server 2008/server 2012<br />/server 2019/server 2022<br />版本：10.9<br />大小：45 M',
	'download_title9' => '系统环境:Android<br />版本：所有<br />大小：42.8 M<br />',
	'download_title10' => '系统环境:IOS<br />版本：所有<br />大小：52.6 M',
	'download_title11' => '扫一扫下载手机版',
	'download_title12' => 'PC端登录时:<br />点击&quot;网络&quot;，输入<br />IP/域名/计算机名称。',
	'download_title13' => '手机端登录时:点击&quot;网络&quot;，输入外网IP/域名.<br />说明：ios版可以从app store下载，搜索&quot;好奇鸟&quot;',
	'download_title14' => '相关下载',
	'download_title15' => '售后服务',
	'download_title16' => '1、当需要特别手机端安装包时，请和我们联系，例如需要设置默认服务端IP，这样的好处是不需要去告诉公司员工服务端IP是多少，直接让员工输入用户名密码就可以登录了。<br />2、无论产品有没有付费，如果在使用过程中遇到技术问题，请和我们联系。<br />3、如果需要与现有管理系统(例如短信系统、企业邮箱、erp、oa、crm)进行集成，因为开发 好奇鸟插件有一定的专业要求，如果有这方面的需求，请和我们联系。<br />4、如果需要将现有系统(例如OA等)员工信息导入到好奇鸟系统，请和我们联系。<br />',
	'download_title17' => '好奇云盘用户手册.docx',
	'download_title18' => '好奇鸟RTC介绍.ppt',
	'download_title19' => '<em></em>打开APP登录页面<br><em></em>网络选择外网输入域名：',
	'download_title20' => '点击复制域名',
	
	
);
?>