<?php
Return array(

	'time_out_warning' => 'Please log in before proceeding',
	
	
	'menu_sup_org' => 'Organization Management',
	'menu_sup_set' => 'System Tools',
	'menu_sup_ext' => 'Extended Function',
	'menu_sup_report' => 'Query Statistics',
	'menu_sup_doc' => 'Document Management',
	'menu_sup_syncpush' => 'Data Push',
	'menu_sup_platform' => 'Open Platform',
	'menu_sup_duty' => 'Online Duty',
	
	
	'menu_sub_org' => 'Organization Management',
	'menu_sub_user' => 'Personnel Management',
	'menu_sub_role' => 'Role Management',
	'menu_sub_grant' => 'Authorization Management',
	'menu_sub_group' => 'Group Management',
	'menu_sub_pos' => 'Nameplate Management',
	'menu_sub_tag' => 'Tag Management',
	
	
	'menu_sub_service' => 'Service Control',
	'menu_sub_set' => 'System Settings',
	'menu_sub_webserver' => 'Background Setting',
	'menu_sub_update' => 'Upgrade Management',
	'menu_sub_hl' => 'Unit Interconnect',
	'menu_sub_skin' => 'Skin Management',
	'menu_sub_server' => 'Server Management',
	'menu_sub_change' => 'Migration Management',
	
	'menu_sub_addin' => 'Plugin Management',
	'menu_sub_interface' => 'Interface Management',
	'menu_sub_ext' => 'Extension Settings',
	'menu_sub_filter' => 'KeyWords Filter', //'敏感词过滤'
	'menu_sub_client' => 'Program Release',
	'menu_sub_config_fh' => 'Integrated Configuration',
	'menu_sub_sms_account' => 'SMS Account',
	
	'menu_sub_msg' =>'Private Chat Message Query',
	'menu_sub_chatlist' =>'Private Chat Query',
	'menu_sub_groupmsg' =>'Group Chat Message Query',
	'menu_sub_groupchatlist' =>'Group Chat Query',
	'menu_sub_livechatmsg' =>'Customer Service Message Query',
	'menu_sub_livechatlist' =>'Customer Service Inquiry',
	'menu_sub_groupkefumsg' => 'Customer Service Group Chat Message Query',
	'menu_sub_groupkefuchatlist' => 'Customer Service Group Chat Query',
	'menu_sub_attach' =>'Accessories Query',
	'menu_sub_msgtotal' =>'Message Statistics',
	'menu_sub_online' =>'Online User',
	'menu_sub_board' =>'Announcement Information',
	'menu_sub_log' =>'Login Log',
	'menu_sub_sms' =>'SMS Statistics',
	'menu_sub_recsms' =>'SMS Receiving',
	'menu_sub_orgreport' =>'Organization Statistics',
	'menu_sub_livechat_msg' =>'Customer Service Message',
	'menu_sub_public_file' =>'Public Document',
	'menu_sub_person_file' =>'personal Document',
	'menu_sub_group_file' =>'Group File',
	'menu_sub_leave_file' =>'Offline File',
	
	'menu_sub_config' => 'Document Configuration',
	'menu_sub_store' => 'Document Storage',
	'menu_sub_doclog' => 'Document Log',
	
	'menu_sub_syncpush_set' => 'Push Settings',
	'menu_sub_syncpush_org' => 'Push Organization',
	'menu_sub_syncpush_log' => 'Push Log',
	
	'menu_sup_platform_app' => 'Application Management',
	'menu_sup_platform_token' => 'Token View',
	
	'menu_sub_operator' =>'Customer Service Management',
	'menu_sub_entrance' =>'Entrance Management',
	'menu_sub_dialog_analysis' =>'Session Analysis',
	'menu_sub_dialog' =>'Session Management',
	'menu_sub_message' =>'Message Management',
	'menu_sub_livemsg' =>'Message Query',
	'menu_sub_rate' =>'Evaluation Management',
	'menu_sub_transfer' =>'Transfer Record',
	'menu_sub_blackip' =>'Blacklist Ip Record',
	'menu_sub_attachment' =>'Attachment Management',
	'menu_sub_dialog_theme' =>'Session Theme Management',
	'menu_sub_visitor_label' =>'Visitor Label Management',
	'menu_sub_visitor' =>'Visitor Management',
	'menu_sub_link' =>'Link Management',
	'menu_sub_quicktalk' =>'Common Language Management',
	'menu_sub_question' =>'Q&A Library',
	'menu_sub_config_lv' =>'Customer Service Configuration',
	'menu_sub_domain' =>'Domain Name Management',
	'menu_sub_wechat' =>'Official Account/Applet Management',
	
	
	'menu_sub_permission' => 'Authorization Management',
	
	'btn_reset_viewid' => 'Reset People Relationship',
	'btn_autocreate' => 'Automatically Create',
	'btn_set' => 'Settings',
	'btn_login' => 'Login',
	'btn_change' => 'Modify',
	'btn_save' => 'Save',
	'btn_cancel' => 'Cancel',
	'btn_back' => 'Return',
	'btn_add' => 'Add',
	'btn_edit' => 'Edit',
	'btn_delete' => 'Delete',
	'btn_clear' => 'Empty',
	'btn_ok' => 'OK',
	'btn_reg' => 'Register',
	'btn_close' => 'Close',
	'btn_import' => 'Import',
	'btn_export' => 'Export',
	'btn_active' => 'Activate',
	'btn_adddept' => 'Add Department',
	'btn_opdept' => 'Department Operation',
	'btn_editdept' => 'Edit Department',
	'btn_deldept' => 'Delete Department',
	'btn_movedept' => 'Mobile Department',
	'btn_adduser' => 'Add Staff',
	'btn_edituser' => 'Editor',
	'btn_opuser' => 'Personnel Operation',
	'btn_setattr' => 'Set Properties',
	'btn_setdept' => 'Set Department',
	'btn_setpos' => 'Set Nameplate',
	'btn_removeuser' => 'Remove From Department',
	'btn_deluser' => 'Delete People',
	'btn_batchop' => 'Batch Operations',
	'btn_impuser' => 'Import User',
	'btn_impdept' => 'Import Department',
	'btn_impldap' => 'Import Domain User',
	'btn_imprtx' =>'Import Rtx Users',
	'btn_expuser' => 'Export User',
	'btn_expdept' => 'Export Department',
	'btn_exp_alluser' => 'Export All Users',
	'btn_exp_seluser' => 'Export Selected User',
	'btn_expire_clear' => 'Clear Expired Data',
	'btn_imptxt' =>'Import Verification File',
	'btn_doc_set' => 'Permission Settings',
	
	'btn_setpy' => 'Reset Pinyin',
	'btn_setdeptpath' => 'Reset Department Path',
	'btn_setorder' => 'Reset Sort',
	
	'btn_addmember' =>'Add Member',
	'btn_setmember' =>'Set Member',
	'btn_setkefumember' =>'Set To Prohibit Notification To Customer Service',
	'btn_setkefumember1' => 'Set Reminder Customer Service',
	'btn_setkefumember2' => 'Set Prohibit Display Of Customer Service',
	'btn_setkefumember3' => 'Set Display Personnel',
	'btn_setkefumember4' => 'Set Up Sending Customer Service',
	'btn_setpublic' =>'Set Official Account/Applet',
	'btn_setcdn' =>'Setting Instructions',
	
	'btn_reset_tag' => 'Reset Tag',
	'btn_sel_dept' => 'Select Department',
	'btn_addgrant' => 'Add Authorization',
	'btn_addgroup' => 'Add Group',
	'btn_delgroup' => 'Delete Group',
	'btn_settag' => 'Set Label',
	'btn_search' => 'Query',
	
	'txt_to' => 'To',
	'txt_search' => 'Find',
	'txt_index_notice' => 'Arrange From Small To Large',
	'txt_img_tip' => 'Change Picture',
	'txt_order' => 'Arrange From Small To Large',
	'txt_usersearch' => 'Enter Account Number Or Name',
	'txt_loading' => 'Loading...',
	
	
	'label_name' => 'Name',
	'label_content' => 'Content',
	'label_username' => 'Name',
	'label_account' => 'Account',
	'label_pwd' => 'Password',
	'label_desc' => 'Description',
	
	'alert_date' => 'The start date must be less than the end date',
	'alert_delconfirm' => 'Are you sure you want to delete?',
	
	
	
	//Field Name
	'field_id' => 'ID',
	'field_user' => 'User',
	'field_content' => 'Content',
	'field_time' => 'Time',
	'field_name' => 'Name',
	'field_type' => 'Type',
	'field_account' => 'Account',
	'field_username' => 'Name',
	'field_sex' => 'Gender',
	'field_email' => 'Mailbox',
	'field_mobile' => 'Phone',
	'field_dept' => 'Department',
	'field_disabled' => 'Disabled',
	'field_grant' => 'Authorization Scope',
	'field_usercount' => 'Create User Number',
	'field_creator' => 'Creator',
	'field_diskspace' => 'Group Shared Space',
	'field_usedspace' => 'Used Space',
	'field_desc' => 'Description',
	'field_tag' => 'Tag',
	'field_operate' => 'Action',
	'field_icon' => 'Icon',
	'field_index' => 'Serial Number',
	'field_synctime' => 'Synchronization Time',
	'field_dt' => 'Create Time',
	'field_job' => 'Position',
	'field_other' => 'Other',
	
	// admin/sync/push_edit.php April 10, 2015 zwz
	'syncpush_lb_name' => 'Push Name',
	'syncpush_lb_type' => 'Push Type',
	'syncpush_lb_url' => 'Push Address',
	
	
	
	//admin/sync/syncpush_list.php
	'syncpush_list_header' => 'Push Settings',
	'syncpush_list_btn_edit' => 'Add New Push',
	'syncpush_list_btn_delete' => 'Delete Push',
	'syncpush_list_ph_search' => 'Find Name',
	'syncpush_list_col_id' => 'ID',
	'syncpush_list_col_name' => 'Push Name',
	'syncpush_list_col_type' => 'Push Type',
	'syncpush_list_col_disabled' => 'Disabled',
	'syncpush_list_col_creator' => 'Creator',
	'syncpush_list_edit' => 'Edit',
	'syncpush_list_delete' => 'Delete',
	
	'syncpush_org_header' => 'Push Organization Settings',
	'syncpush_org_all' => 'All Push',
	'syncpush_org_increment' => 'Incremental Push',
	
	
	//admin/sync/push_log.php
	'sycnpush_log_header' => 'Push Log',
	'sycnpush_log_col_data' => 'Data',
	'sycnpush_log_col_systemname' => 'System Name',
	'sycnpush_log_col_id' => 'ID',
	'sycnpush_log_col_datatype' => 'Data Type',
	'sycnpush_log_col_optype' => 'Operation Type',
	'sycnpush_log_col_ipaddr' => 'IP',
	'sycnpush_log_col_dt_create' => 'Synchronization Time',
	'sycnpush_log_col_status' => 'Status',
	'sycnpush_log_col_result' => 'Synchronization Result',
	'sycnpush_log_col_dt_feedback' => 'Feedback Time',
	'sycnpush_log_icon_error' => 'Failed',
	'sycnpush_log_icon_success' => 'Success',
	'sycnpush_log_icon_warning' => 'No Feedback',
	'sycnpush_log_type_create' => 'Add',
	'sycnpush_log_type_edit' => 'Update',
	'sycnpush_log_type_delete' => 'Delete',
	'sycnpush_log_type_text' => 'Message',
	'sycnpush_log_type_file' => 'Attachment',
	'sycnpush_log_type_sync' => 'Synchronization',
	'sycnpush_log_type_dept' => 'Department',
	'sycnpush_log_type_user' => 'User',
	'sycnpush_log_type_group' => 'Group',
	'sycnpush_log_type_msg' => 'Message',
	
	//admin/hl/hl_org.php
	'hlorg_header' => 'Unit Interconnect / Organization Management',
	'hlorg_btn_create_dir' => 'Create Directory',
	'hlorg_btn_delete_dir' => 'Delete Directory',
	'hlorg_col_name' => 'Name',
	'hlorg_col_descibe' => 'Description',
	'hlorg_col_address' => 'Port Address',
	'hlorg_col_type' => 'Port Type',
	'hlorg_col_status' => 'Status',
	
	
	// admin/account/login.php
	'browser_notice1' => 'Recommended to use IE9 or FireFox, Chrome browser for a better experience...',
	'browser_notice2' => 'Your IE version is too low, please upgrade IE version, or use Chrome/FireFox browser',
	
	
	'login_error' => 'Account or password error',
	'login_error1' => 'You have exceeded 1% of errors today and have been restricted from logging in! ',
	
	'login_title' => 'Login',
	'login_notice' => 'Default administrator account: admin password is empty, please change the administrator password after login',
	'login_lb_account' => 'Account',
	'login_ph_account' => 'Please enter an account number',
	'login_required_account' => 'Please enter an account number',
	'login_lb_password' => 'password',
	'login_ph_password' => 'Please enter a password',
	'login_required_password' => 'Please enter a password',
	
	'login_lb_verifycode' => 'Verification Code',
	'login_ph_verifycode' => 'Verification Code',
	'login_required_verifycode' => 'Please enter a verification code',
	
	// admin/account/setpassword.php
	'pwd_title' => 'Change Password',
	'pwd_notice' => 'The password was successfully modified and the login again took effect. ',
	'pwd_lb_old' => 'Old Password',
	'pwd_lb_new' => 'New Password',
	'pwd_lb_repeat' => 'Confirm Password',
	
	'doc_private_title' => 'Document Management / Configuration Information',
	'doc_private_notice' => 'Modified Successfully',
	'doc_private_lb_path' => 'Storage Path',
	'doc_private_lb_switch' => 'Allow Personal Documents To Be Saved',
	
	// admin/doc/doc_log.php
	'doc_log_title' => 'Document Management / Document Log',
	
	// admin/doc/doc_tree.php
	'doc_public_title' => 'Document Management / Document Storage',
	'doc_btn_createroot' => 'Add Root Directory',
	'doc_btn_createfolder' => 'Add Directory',
	'doc_btn_editfolder' => 'Modify Directory',
	'doc_btn_delfolder' => 'Delete Directory',
	'doc_btn_addpower' => 'Add Permissions',
	'doc_btn_adduser' => 'Add User',
	'doc_btn_addrole' => 'Add Role',
	'doc_btn_delpower' => 'Delete Permission',
	'doc_btn_batch' => 'Bulk Import',
	'doc_btn_clean' => 'Clean Up Folder',
	'doc_tree_title' => 'Storage Directory',
	'doc_path_title' => 'Directory Attribute',
	'doc_lb_foldername' => 'Directory Name',
	'doc_ph_foldername' => 'Directory Name',
	'doc_lb_folderpath' => 'Directory Path',
	'doc_ph_folderpath' => 'Directory Path',
	
	// Document permission type
	'doc_power_view' => 'Show',
	'doc_power_edit' => 'Check',
	'doc_power_edit1' => 'Edit',
	'doc_power_manage' => 'Move',
	'doc_power_download' => 'Download',
	'doc_power_create' => 'Create',
	'doc_power_delete' => 'Delete',
	'doc_power_rename' => 'Rename',
	'doc_power_sendfile' => 'Share',
	'doc_power_permission' => 'Permission',
	'doc_power_finalized' => 'Fixed version',
	
	// Document log type
	'type_downloadfile' => 'Download File',
	'type_editfile' => 'Edit File',
	'type_newfile' => 'Create File',
	'type_removefile' => 'Move File',
	'type_viewfile' => 'View file',
	'type_deletefile' => 'Delete File',
	'type_sharefile' => 'Share File',
	'type_login' => 'Login',
	
	// Copyright Information
	'about_version' => 'Version Number',
	'about_publishdate' => 'Release Date',
	'about_website' => 'Product URL',
	'about_copyright' => 'Copyright 2015 %1. All rights reserved. ',
	
	// Software registration
	'reg_machinecode' => 'Machine Code',
	'reg_licensenumber' => 'Permission Number',
	'reg_usercount' => 'Total number of users',
	'reg_expiredate' => 'Expiration Time',
	'reg_lb_active' => 'Please enter the activation code',
	
	// Management settings
	'webserver_config_title' => 'Background Settings',
	'webserver_config_antserver' => 'WebServer Message Server Configuration',
	'webserver_config_common' => 'WebServer Common Configuration',
	'webserver_config_added' => 'WebServer Value-Added Configuration',
	'webserver_lb_ant_server' => 'Message Server IP Address',
	'webserver_lb_ant_server_tip' => 'Please use real IP, such as 192.168.0.1, proxy server please use proxy address',
	'webserver_lb_ant_console_tip' => 'Please modify carefully. After modification, please set up a site to point to the data directory and modify the video playback address, otherwise the cloud disk video cannot be played on the web!',
	'webserver_lb_ant_port' => 'Port',
	'webserver_lb_ant_datadir' => 'Data Directory',
	'webserver_lb_ant_consoledir' => 'Console Directory',
	'webserver_lb_ant_video' => 'Video Playback Address',
	'webserver_lb_ant_video_tip' => 'Only after modifying the data directory and setting up a site to point to the data directory can you fill in!for example http://192.168.1.4:94',
	'webserver_lb_export_field' => 'Data Import And Export Format',
	'webserver_lb_push_toket' => 'WebSerivce Token',
	'webserver_lb_api_return_type' => 'WebSerivce Returns The Content Format',
	'webserver_lb_sms_url' => 'SMS Interface Address',
	'webserver_lb_sms_sample' => 'Example: http://192.168.0.1/sms_send.html?mobile={mobile}&content={content}, multiple mobile numbers are separated by commas, and the returned content needs to be in JSON format, such as {" Status":1} or {"status":0,"msg":"error"}',
	'webserver_lb_smtp_info' => 'Mail Sending Information',
	'webserver_lb_smtp_server' => 'SMTP Server Address:',
	'webserver_lb_smtp_port' => 'SMTP Server Port:',
	'webserver_lb_smtp_account' => 'Mailbox Account:',
	'webserver_lb_smtp_password' => 'Mailbox Password:',
	'webserver_lb_back_onlineminute' => 'API login heartbeat duration (timeout is set to exit)',
	'webserver_lb_log_level'=>'WebServer Log Level',
	'webserver_lb_log_level_close'=>'Close',
	'webserver_lb_log_level_debug'=>'Debug',
	'webserver_lb_log_level_info'=>'Info',
	'webserver_lb_log_level_error'=>'Error',
	'webserver_lb_log_level_open'=>'Open',
	'webserver_lb_push_sms' => 'Message Push',
	'webserver_lb_push_email' => 'Mail Push',
	'webserver_lb_push_sms_desc' => 'When the phone does not receive a push message, the system will send a text message to remind the user to open the app to view the message',
	'webserver_lb_push_email_desc' => 'When the phone does not receive a push message, the system will send an email to remind the user to open the app to view the message',
	
	
	// unit interconnection
	'hl_config_title' => 'Unit interconnect <small> (with <i class="warnning">*</i> is required) </small>',
	'hl_config_legend1' => 'Interconnect Information',
	'hl_config_legend2' => 'Central Server (Required)',
	'hl_config_legend3' => 'File Server (Optional)',
	'hl_config_legend4' => 'Audio Video Server (Optional)',
	'hl_lb_unitid' => 'Unit ID',
	'hl_lb_connectpwd' => 'Connection Password',
	'hl_ph_centerport' => 'Default 8899',
	'hl_lb_serverip' => 'Server IP',
	'hl_lb_serverport' => 'Server Port',
	
	
	// Organization staff management
	'org_title' => 'Organization Management',
	'org_ph_search' => 'Enter Account Number Or Name',
	'org_tree_title' => 'Department Management',
	'org_user_title' => 'Person List',
	'dept_lb_path' => 'Superior Department',
	'dept_lb_name' => 'Department Name',
	'dept_ph_name' => 'Department Name',
	'dept_lb_desc' => 'Department Description',
	'dept_ph_desc' => 'Department Description',
	'dept_lb_index' => 'Sort Number',
	'dept_ph_index' => '1000',
	'dept_lb_display' => 'Personal Display',
	'dept_col_style0' => 'State First',
	'dept_col_style1' => 'Ignore Status',
	
	'dept_lb_reset' => 'Delete Previous Department',
	
	// hierarchical management
	'grant_lb_user' => 'Authorized Personnel',
	'grant_lb_tree' => 'Authorized Department',
	'grant_lb_usercount' => 'number of people',
	'grant_notice' => '0 means the number of created users is not limited',
	'grant_title' => 'authorization management',
	'grant_exist' => 'This department has been authorized',
	'grant_beyond' => 'Exceeded the number of authorized persons',
	
	// Group management
	'group_tab_base' => 'Property',
	'group_tab_member' => 'Member',
	'group_tab_board' => 'Group Announcement',
	'group_tab_tag' => 'Tag',
	'group_lb_name' => 'Name',
	'group_ph_name' => '',
	'group_lb_diskspace' => 'Group Space Size',
	'group_ph_diskspace' => '',
	'group_lb_index' => 'Sort Number',
	'group_ph_index' => '1000',
	'group_lb_desc' => 'Description',
	'group_ph_desc' => '',
	'group_tree_title' => 'Select Member',
	'group_title' => 'Group Management',
	'group_ph_search' => 'Find Group',
	'group_ph_portrait' => 'Group Avatar',
	'group_ph_Banned' => 'All Members Banned',
	// Import department
	'imp_lb_filepath' => 'Import File',
	'imp_dept_warning' => 'Please set the import file to UTF-8 encoding to ensure that Chinese is not garbled',
	'imp_dept_link_path' => 'Import [path] format',
	'imp_dept_link_table' => 'Import [table] format',
	
	// Import users
	'imp_user_warning' => 'Please use UTF-8 format to ensure that Chinese is not garbled',
	'imp_user_switch' => 'Quick Import',
	'imp_user_link' => 'Text Import Format',
	
	'imp_txt_warning' =>'Please download the verification file from WeChat official account/applet',
	// Import domain users
	'ldap_lb_domain' => 'Domain Control Server',
	'ldap_ph_domain' => 'Domain Server Domain Name',
	'ldap_lb_admin' => 'Admin Account',
	'ldap_ph_admin' => 'Admin Account',
	'ldap_lb_pwd' => 'Password',
	
	// job nameplate
	'pos_lb_icon' => 'Icon',
	'pos_lb_preview' => 'Preview',
	'pos_lb_index' => 'Serial Number',
	'pos_lb_name' => 'Name',
	'pos_lb_desc' => 'Description',
	'pos_title' => 'Nameplate Management',
	'pos_ph_search' => 'Find The Nameplate',
	
	//Character
	'role_tab_base' => 'Property',
	'role_tab_member' => 'Member',
	'role_tab_power' => 'Basic Permissions',
	'role_tab_org' => 'Organization Permissions',
	'role_tab_ip' => 'Login Settings',
	'role_tab_file' => 'File Management',
	
	'role_tree_title' => 'Select Member',
	'role_ph_search' => 'Enter account number or name',
	
	'role_power_warning' => 'When the role permissions are modified, the role permissions that the employee has are also changed, and you do not need to modify the roles that the employee has. ',
	'role_power_warning1' => 'Extension name is limited to * means that there is no limit to the type of file to be uploaded or sent. Input format: rar; doc; xls',
	'role_power_chk_smscount' => 'Send SMS&nbsp;&nbsp;Maximum Limit',
	'role_power_smscount' => 'Bar/Month',
	'role_power_chk_ptpsize' => 'Upload Personal Documents/Share Files',
	'role_power_ptpsize' => 'Upload Limit',
	'role_power_ptptype' => 'Upload Extension Limit:',
	'role_power_download_ptpsize' => 'Download Personal Document/Shared File',
	'role_power_chk_clotsize' => 'Upload Group File',
	'role_power_download_clotsize' => 'Download Group File',
	'role_power_chk_userssize' => 'Send File',
	'role_power_userssize' => 'Send Maximum Limit',
	'role_power_userstype' => 'Send Extension Name Limit',
	'role_power_download_userssize' => 'Receive File',
	'role_power_download_networks' => 'Do not allow all files to be downloaded on the external network and mobile phone',
	'role_power_other_department' => 'Do not chat with other departments',
	'role_power_this_department' => 'No chat with this department',
	'role_power_unauthorized_control' => 'No permission control (you can see all departments, accounts)',
	'role_power_switch0_department' => 'Do not see the following departments and their accounts',
	'role_power_switch1_department' => 'Only see the following departments and their accounts',
	'role_power_remote_login' => 'remote login',
	'role_power_phone_login' => 'Mobile login',
	'role_power_restrictip' => 'Limit IP',
	'role_power_restrictmac' => 'Restrict MAC',
	'role_power_password' => 'Change password',
	'role_power_sendboard' => 'Publish announcement',
	'role_power_delboard' => 'Allow deletion of announcements',
	'role_power_attachsize' => 'attachment size limit',
	'role_power_broadcast' => 'group number limit',
	'role_power_setattr' => 'Modify personal settings',
	'role_power_setjob' => 'Do not show jobs',
	'role_power_recfile' => 'Prohibit users from receiving attachments',
	'role_power_video' => 'Voice Video',
	'role_power_audio' => 'No voice calls',
	'role_power_signout' => 'No exit group',
	'role_power_logout' => 'Disable client logout',
	'role_power_remote' => 'remote screen and remote control',
	'role_power_ring' => 'Disable client voice prompts',
	'role_power_splashscreen' => 'Stop sending splash screens',
	'role_power_splashscreen' => 'Stop sending splash screens',
	'role_power_signmsg' => 'Stop sending sign-off messages',
	'role_power_showsignature' => 'Prohibit the display of personal signatures',
	'role_power_changephoto' => 'Disable client to modify avatar',
	'role_power_screenshot' => 'Block screen',
	'role_power_set' => 'Modify advanced settings',
	'role_power_setaway' => 'Forbidden stealth',
	'role_power_sendtopmsg' => 'Prohibit sending top messages',
	'role_power_privatechat' => 'Disable the chat feature',
	'role_power_sysview' => 'Show organization structure',
	'role_power_group_create' => 'Create group',
	'role_lb_ipaddr' => 'allowed IP address',
	'role_lb_loginpower' => 'Login permission settings',
	'role_lb_switch0' => 'Forbidden',
	'role_lb_switch1' => 'Allow',
	
	//admin/hs/role_list.php
	'role_list_title' => 'role management',
	'role_list_btn_add' => 'Add role',
	'role_list_btn_member' => 'Set people',
	'role_list_btn_delete' => 'delete role',
	'role_list_btn_set' => 'One-click set role',
	'role_list_ph_search' => 'Find the role',
	'role_list_col_name' => 'name',
	'role_list_col_description' => 'description',
	'role_list_col_creator_name' => 'creator',
	'role_list_col_disabled' => 'disabled',
	'role_list_col_member' => 'personnel',
	'role_list_col_change' => 'Modify',
	'role_list_col_detele' => 'delete',
	'role_list_col_clone' => 'clone',
	'role_list_btn_role' => 'Set the role',
	'role_list_btn_batches' => 'Set the role in batches',
	//admin/hs/role_picker.php
	'role_picker_col_name' => 'name',
	'role_picker_col_description' => 'description',
	'role_picker_default_role' => 'Add user default role',
	
	//admin/hs/tag_edit.php
	'tag_lb_name' => 'tag name',
	'tag_ph_name' => 'tag name',
	
	//admin/hs/tag_list.php
	'tag_list_title' => 'tag management',
	'tag_list_btn_add' => 'Add Category',
	'tag_list_type_edit' => 'Edit',
	'tag_list_type_delete' => 'delete',
	'tag_list_ph_name' => 'Add tags',
	'tag_list_col_user' => 'View people',
	'tag_list_col_group' => 'View group',
	'tag_list_col_edit' => 'Modify label',
	'tag_list_col_delete' => 'delete label',
	
	//admin/hs/tag_picker.php
	'tag_picker_checkbox_reset' => 'Reset tag',
	'tag_picker_alert' => 'Please select the object to be set',
	
	//admin/hs/tag_type_edit.php
	'tag_type_lb_name' => 'type name',
	'tag_type_ph_name' => 'type name',
	
	//admin/hs/user_attr.php
	'user_attr_allowedcard' => 'Allow NIC addresses (multiple, separated by commas)',
	'user_attr_allowedip' => 'Allow IP addresses (multiple, separated by commas)',
	
	//admin/hs/user_edit.php
	'user_edit_tab_base' =>'Basic information',
	'user_edit_tab_work' =>'Business information',
	'user_edit_tab_self' =>'Personal Information',
	'user_edit_tab_login' =>'Login Information',
	'user_edit_tab_power' =>'Role And Authority',
	'user_edit_account' =>'Account',
	'user_edit_username' =>'Name',
	'user_edit_psw' =>'Password',
	'user_edit_show_password' =>'Show Password',
	'user_edit_sequence' =>'Sequence Number',
	'user_expiration_time' =>'Validity Period',
	'user_expiration_tip' =>'Set the expiration time of the current department and all department personnel under it',
	'user_expiration_set' =>'Long-term Effective',
	'user_edit_order' =>'The bigger the sort number, the more in the front',
	'user_edit_checkbox_admin' =>'Administrator',
	'user_edit_checkbox_disabled' =>'Disable Account',
	'user_edit_lb_jobtitle' =>'Job Title',
	'user_edit_lb_nameplate' =>'Nameplate',
	'user_edit_lb_phone' =>'Fixed Phone',
	'user_edit_lbl_shortnum' =>'Shortnum',
	'user_edit_lb_mobile' =>'Mobile',
	'user_edit_lb_fax' =>'Fax',
	'user_edit_lb_email' =>'Mailbox',
	'user_edit_lb_address' =>'Address',
	'user_edit_lb_postal' =>'Postal Code',
	'user_edit_lb_gender' =>'Gender',
	'user_edit_lb_gender1' =>'Male',
	'user_edit_lb_gender2' =>'Female',
	'user_edit_lb_age' =>'Age',
	'user_edit_lb_birthday' =>'Birthday',
	'user_edit_lb_province' =>'Province',
	'user_edit_lb_city' =>'City',
	'user_edit_lb_street' =>'Street',
	'user_edit_lb_website' =>'Webpage',
	'user_edit_lb_description' =>'Personal Description',
	'user_edit_lb_school' =>'Graduation School',
	'user_edit_lb_note' =>'Notes',
	'user_edit_col_mac' =>'Allow network card addresses (multiple entries are separated by commas)',
	'user_edit_col_ip' =>'Allow IP addresses (multiple entries are separated by commas, format 192.168.1.1 or 192.168.1.1-192.168.1.3)',
	'user_edit_power_roles' =>'Roles Owned By The User',
	'user_edit_power_ou' =>'Organizations Allowed To Access',
	
	
	//admin/hs/user_list.php
	'user_list_page_title' =>'Personnel Management',
	'user_list_btn_add' =>'Add New Person',
	'user_list_btn_batch' =>'Batch Operation',
	'user_list_dropdown_properties' =>'Set Properties',
	'user_list_dropdown_dept' =>'Set The Department',
	'user_list_dropdown_role' =>'Set Role',
	'user_list_dropdown_pos' =>'Set Nameplate' ,//
	'user_list_dropdown_label' =>'Set Label',
	'user_list_dropdown_delete' =>'Delete',
	'user_list_ph_search' =>'Find Personnel Account/Name',
	'user_list_col_loginname' =>'Account',
	'user_list_col_name' =>'Name',
	'user_list_col_sex' =>'Sex',
	'user_list_col_email' =>'Email',
	'user_list_col_mobile' =>'Phone',
	'user_list_col_deptinfo' =>'Department',
	'user_list_col_job' =>'Job',
	'user_list_col_other' =>'Other',
	'user_list_col_expiretime' =>'Expiration Time',
	'user_list_col_issuper' =>'Administrator',
	'user_list_col_disabled' =>'Disabled',
	'user_list_col_label' =>'Disable',
	'user_list_alert' =>'admin account does not allow this operation',
	
	
	//admin/hs/user_picker.php
	'user_picker_title' => 'Select Member',
	'user_picker_ph_userkey' => 'Enter Account Number Or Name',
	'user_picker_btn_add' => 'Add Member',
	'user_picker_col_name' => 'Name',
	'user_picker_col_account' => 'Account',
	'user_picker_checkbox_reset' => 'Reset Member',
	'user_picker_col_title' => 'Name',
	'user_picker_col_type' => 'Type',
	
	//admin/include/bioace_lis.php
	'bioace_btn_add' => 'Add Permissions',
	'bioace_btn_delete' => 'Delete Permission',
	'bioace_btn_change' => 'Modify Permissions',
	'bioace_col_name' => 'Name',
	'bioace_col_type' => 'Type',
	'bioace_col_permission' => 'Permission',
	'bioace_col_delete' => 'Delete',
	
	
	//admin/include/header.php
	'header_hello' => 'Hello, ',
	'header_home' => 'Home',
	'header_download' => 'Download Area',
	'header_changepsw' => 'Change Password',
	'header_exit' => 'Exit',
	'header_help' => 'Help',
	'header_dropdown_register' => 'Register',
	'header_dropdown_about' => 'About',
	'header_nopermission' => 'No Permission',
	'header_nopermission_operate' => 'There is no permission to operate this page',
	'header_lang' => 'Language',
	'header_cn' => 'Simplified Chinese',
	'header_hk' => 'Traditional Chinese',
	'header_en' => 'English',
	
	//admin/include/header0.php
	'header0_help' => 'Help', //' '
	'header0_dropdown_register' => 'Register',
	'header0_dropdown_about' => 'About',
	
	
	//admin/include/index.php
	'index_companyinfo' => 'Unit Information: ',
	'index_btn_set' => 'Settings',
	'index_commonuse' => 'Common Operations',
	'index_user' => 'User Management',
	'index_user_des' => 'Add, delete, set, import/export department and personnel information',
	'index_upgrade' => 'Upgrade Management', // 'Upgrade Management'
	'index_upgrade_des' => 'Upgrade PC, Android Client',
	'index_server' => 'Service Control',
	'index_server_des' => 'Start, stop, restart all kinds of instant messaging services',
	'index_service' => 'Online Customer Service',
	'index_service_des' => 'Customers can communicate with our employees through the web',
	'index_application' => 'App Center',
	'index_application_des' => 'Enterprise third-party management systems such as OA, CRM and other business systems',
	'index_map' => 'Function Map',
	
	//admin/lv_manager/chat_list.php
	'lvchat_private_title' => 'Online Customer Service / Configuration Information',
	
	'transfer_list_title' =>'Transfer Record',
	'transfer_list_original' =>'Original Customer Service',
	'transfer_list_now' =>'Now Customer Service',
	'transfer_list_userid' =>'User ID',
	'transfer_list_type' =>'Type',
	'transfer_list_date' =>'Time',
	'transfer_list_type1' =>'Transfer',
	'transfer_list_type2' =>'Grab The Connection',
	'transfer_list_type3' => 'Automatic Transfer',
	
	'lvchat_list_title' =>'Session Management',
	'lvchat_list_drop_status' =>'All',
	'lvchat_list_drop_status0' =>'Waiting',
	'lvchat_list_drop_status1' =>'Talking',
	'lvchat_list_drop_status2' =>'End',
	'lvchat_list_field_account' =>'Customer Service Account',
	'lvchat_list_field_name' =>'Visitor Name',
	'lvchat_list_field_userid' =>'User ID',
	'lvchat_list_field_chatid' =>'Session ID',
	'lvchat_list_field_content' =>'Content',
	'lvchat_list_txt_keywords' =>'Keywords',
	'lvchat_list_txt_date' =>'Session Date',
	'lvchat_list_chatid' =>'Session ID',
	'lvchat_list_account' =>'Customer Service Account',
	'lvchat_list_userid' =>'User ID',
	'lvchat_list_username' =>'Name',
	'lvchat_list_ip' =>'IP',
	'lvchat_list_area' =>'Area',
	'lvchat_list_intime' =>'Enter Time',
	'lvchat_list_connecttime' =>'Connect Time',
	'lvchat_list_outtime' =>'End Time',
	'lvchat_list_status' =>'Status',
	'lvchat_list_attach' =>'Attachment',
	'lvchat_list_record' =>'Record',
	'lvchat_list_allrecord' =>'All Records',
	'lvchat_list_blackip' =>'Blacklist',
	'lvchat_list_return_case0' =>'Waiting',
	'lvchat_list_return_case1' =>'In Conversation',
	'lvchat_list_return_case2' =>'End',
	'lvchat_list_groupid' =>'Please Select The Entrance',
	'lvchat_list_groupname' =>'Entrance',
	'lvchat_list_themeid' =>'Please Choose A Theme',
	'lvchat_list_themename' =>'Theme',
	'lvchat_list_chatlevel' =>'Please Select The Value',
	'lvchat_list_chatlevelname' =>'Level',
	'lvchat_list_chatlevel0' =>'Not Evaluated',
	'lvchat_list_chatlevel1' =>'No Value',
	'lvchat_list_chatlevel2' =>'Valuable',
	'lvchat_list_isenable' =>'Please Select The Effect',
	'lvchat_list_isenable1' =>'Invalid Session',
	'lvchat_list_isenable2' =>'Valid Session',
	'lvchat_list_no' =>'All',
	'lvchat_list_not' =>'Non-Entry Session',
	'lvchat_list_drp_type0' =>'Call Volume',
	'lvchat_list_drp_type2' =>'Session Value',
	'lvchat_list_drp_type1' =>'Session Topic',
	'lvchat_list_uname' =>'Name',
	'lvchat_list_groupcount' =>'Total Reception',
	'lvchat_list_percent' =>'Percentage',
	'lvchat_list_detail' =>'Details',
	'lvchat_list_first_inouttime' =>'First Time',
	'lvchat_list_inouttime' =>'Average',
	'lvchat_list_rate' =>'Rating',
	'lvchat_list_first_inouttimes' =>'First Reply Time',
	'lvchat_list_inouttimes' =>'Average Response Time',
	'lvchat_list_chat_times' =>'Chat Time',
	'lvchat_list_rates' =>'Rates',
	'lvchat_list_enable_inoutnum' =>'The Number Of Replied Conversations',
	'chart_rate_unit0' =>'Unrated',
	'chart_rate_unit1' =>'Bad',
	'chart_rate_unit2' =>'Bad',
	'chart_rate_unit3' =>'General',
	'chart_rate_unit4' =>'Better',
	'chart_rate_unit5' =>'Satisfied',
	
	//admin/lv_manager/chater_edit.php
	'chater_edit_photo' =>'Change Photo',
	'chater_edit_lb_account' =>'Account',
	'chater_edit_ph_account' =>'Account',
	'chater_edit_lb_name' =>'Name',
	'chater_edit_ph_name' =>'Name',
	'chater_edit_lb_dept' =>'Department',
	'chater_edit_ph_dept' =>'Department',
	'chater_edit_lb_job' =>'Job',
	'chater_edit_ph_job' =>'Job',
	'chater_edit_lb_tel' =>'Landline',
	'chater_edit_ph_tel' =>'Landline',
	'chater_edit_lb_mobile' =>'Mobile',
	'chater_edit_ph_mobile' =>'Mobile',
	'chater_edit_lb_reception' =>'Maximum Reception',
	'chater_edit_ph_reception' =>'Maximum Reception',
	'chater_edit_lb_email' =>'Mailbox',
	'chater_edit_ph_email' =>'Mailbox',
	'chater_invite_lb_welcome' =>'Invitation Box Welcome Message',
	'chater_invite_ph_welcome' =>'Invitation Box Welcome Message',
	'chater_edit_lb_welcome' =>'Welcome',
	'chater_edit_ph_welcome' =>'Welcome',
	'chater_edit_lb_cdn_title' =>'Please Enter The CDN Acceleration Domain Name',
	'chater_edit_lb_adlink' =>'Ad URL',
	'chater_edit_lb_adlink_alert' =>'Please Enter The Ad Link URL',
	'chater_edit_lb_ad' =>'Advertising',
	'chater_edit_lb_ad_img' =>'Ad Image',
	'chater_edit_lb_ad_title' =>'Change Ad',
	'chater_delete_lb_ad_title' =>'Clear Ads',
	'chater_edit_lb_status' =>'Status',
	'chater_edit_option_status1' =>'Normal',
	'chater_edit_option_status0' =>'Close',
	'chater_edit_lb_order' =>'Order',
	'chater_edit_ph_order' =>'Order',
	'chater_edit_alert' =>'User Does Not Exist!',
	'chater_edit_error_account' =>'Please Enter The Account Number',
	'chater_edit_error_name' =>'Please Enter Your Name',
	'chater_edit_error_ord' =>'Please Enter The Sort Number',
	'chater_edit_end_conversation' =>'Conversation End',
	'chater_edit_end_conversation0' =>'Not Set',
	'chater_edit_end_conversation1' =>'Automatically Set Back',
	'chater_edit_end_conversation2' =>'Automatic Removal',
	'chater_edit_lb_endsession' => 'After The End Session',
	'chater_edit_lb_endsession_alert' => 'Access A New Session From The Queue List',
	'chater_edit_default' => 'Default',
	'chater_edit_lb_match' => 'Match Method',
	'chater_edit_option_match0' => 'Fuzzy Match',
	'chater_edit_option_match1' => 'Exact Match',
	'chater_edit_lb_receives_reminders' => 'Customer Service Receives Reminders',
	'chater_edit_lb_receives_reminders_alert' => 'Customer service can receive a complete session, if you do not check this option, you can intelligently filter out repeated consultations with large traffic',
	'chater_edit_lb_top_questions' => 'Top Questions',
	'chater_edit_lb_top_questions_alert' => 'visitor display, click on popular questions, automatic answer',
	'chater_edit_defaulttargetlanguage' => 'Manual Translation To',
	'chater_edit_usertargetlanguage' => 'Visitor messages are automatically translated into',
	'chater_edit_chatertargetlanguage' => 'Customer service messages are automatically translated into',
	'chater_edit_language_zh' => 'Simplified Chinese',
	'chater_edit_language_en' => 'English',
	'chater_edit_language_yue' => 'Cantonese',
	'chater_edit_language_wyw' => 'Classical Chinese',
	'chater_edit_language_jp' => 'Japanese',
	'chater_edit_language_kor' => 'Korean',
	'chater_edit_language_fra' => 'French',
	'chater_edit_language_spa' => 'Spanish',
	'chater_edit_language_th' => 'Thai',
	'chater_edit_language_ara' => 'Arabic',
	'chater_edit_language_ru' => 'Russian',
	'chater_edit_language_pt' => 'Portuguese',
	'chater_edit_language_de' => 'German',
	'chater_edit_language_it' => 'Italian',
	'chater_edit_language_el' => 'Greek',
	'chater_edit_language_nl' => 'Dutch',
	'chater_edit_language_pl' => 'Polish',
	'chater_edit_language_bul' => 'Bulgarian',
	'chater_edit_language_est' => 'Estonian',
	'chater_edit_language_dan' => 'Danish',
	'chater_edit_language_fin' => 'Finnish',
	'chater_edit_language_cs' => 'Czech',
	'chater_edit_language_rom' => 'Romania',
	'chater_edit_language_slo' => 'Slovenian',
	'chater_edit_language_swe' => 'Swedish',
	'chater_edit_language_hu' => 'Hungarian',
	'chater_edit_language_cht' => 'Traditional Chinese',
	'chater_edit_language_vie' => 'Vietnamese',
	
	'user_edit_lb_name' =>'Name',
	'user_edit_ph_name' =>'Name',
	'user_edit_lb_wechat' =>'WeChat',
	'user_edit_ph_wechat' =>'WeChat',
	'user_edit_lb_qq' =>'QQ',
	'user_edit_ph_qq' =>'QQ',
	'user_edit_lb_remarks' =>'Remarks',
	'user_edit_ph_remarks' =>'Remarks',
	'user_edit_lb_mobile' =>'Mobile',
	'user_edit_ph_mobile' =>'Mobile',
	'user_edit_lb_chater' =>'Priority reception customer service',
	'user_edit_ph_chater' =>'Please enter the customer service account number',
	'user_edit_lb_email' =>'Mailbox',
	'user_edit_ph_email' =>'Email',
	'user_edit_alert' =>'Customer service does not exist or is disabled!',
	
	//admin/lv_manager/chater_list.php
	'chater_list_title' =>'Customer Service List',
	'chater_list_add' =>'Add Customer Service',
	'chater_list_deleteoperate' =>'Delete Customer Service',
	'chater_list_preview' =>'Preview',
	'chater_list_generate' =>'Customer Service Code',
	'chater_list_search' =>'Find Personnel Account/Name',
	'chater_list_account' =>'Account',
	'chater_list_name' =>'Name',
	'chater_list_dept' =>'Department',
	'chater_list_job' =>'Job',
	'chater_list_tel' =>'Landline',
	'chater_list_mobile' =>'Mobile',
	'chater_list_email' =>'Mailbox',
	'chater_list_reception' =>'Maximum Reception',
	'chater_list_welcome' =>'Welcome',
	'chater_list_top' => 'Hot Questions',
	'chater_list_status' =>'Status',
	'chater_list_order' =>'Sort',
	'chater_list_link' =>'Link',
	'chater_list_js' =>'Code',
	'chater_list_qrcode' =>'QR Code',
	'chater_list_dialog' =>'Session',
	'chater_list_rate' =>'Evaluation',
	'chater_list_edit' =>'Edit',
	'chater_list_delete' =>'Delete',
	'chater_list_up' =>'Move Up',
	'chater_list_down' =>'Move Down',
	'chater_list_talk' =>'Talk',
	'chater_list_attributes' =>'Attributes',
	'chater_list_generate1' =>'Mobile Customer Service Code',
	'chater_list_member' =>'Member',
	'chater_list_server' =>'Server Address',
	'chater_list_alert_enteripaddress' =>'The URL address of the current server on the Internet, which can be an IP or a domain name',
	'chater_list_copy' =>'Copy',
	'chater_list_mode' =>'Mode',
	'chater_list_mode_alert1' =>'Website mode (all customer services are company employees)',
	'chater_list_mode_alert2' =>'Mall multi-user mode (each customer service corresponds to a store)',
	'chater_list_distribution' =>'Customer Service Distribution',
	'chater_list_distribution_alert1' =>'Smart Mode',
	'chater_list_distribution_alert2' =>'Sequence mode',
	'chater_list_guestsession' => 'guest session',
	'chater_list_guestsession_alert1' => 'direct session',
	'chater_list_guestsession_alert2' => 'queue session',
	'chater_list_switchtype' =>'Auto invite',
	'chater_list_switchtype_alert1' =>'Invite a conversation to visit the website in the customer',
	'chater_list_switchtype_alert2' =>'Send in seconds',
	'chater_list_websitetype' =>'Visitor reminder',
	'chater_list_websitetype_alert1' =>'visitor reminder',
	'chater_list_websitetype_alert2' =>'Website visitors enter to notify customer service',
	'chater_list_websitetype_alert3' => 'Visitors open a dialog box to remind customer service',
	'chater_list_websitetype_alert4' => 'Website visitors enter an automatic conversation with customer service',
	'chater_list_websitetype_alert5' => 'Not set',
	'chater_list_switchweChat' =>'official account/applet',
	'chater_list_switchweChat_alert1' =>'WeChat official account/applet',
	'chater_list_switchweChat_alert2' =>'Push messages through WeChat official account/applet',
	'chater_list_switchBack' => 'Return button',
	'chater_list_switchBack_alert1' => 'The visitors mobile phone does not display a return button',
	'chater_list_switchBack_alert2' => 'Set to disable the display of customer service',
	'chater_list_sendWelcome' => 'Send a welcome message',
	'chater_list_sendWelcome_alert1' => 'Visitors send customer service welcome messages every time they open a chat page',
	'chater_list_sendWelcome_alert2' => 'Set sending to customer service',
	'chater_list_switchDomainType' => 'Switch to jump domain name',
	'chater_list_switchDomainType_alert1' => 'Automatically switch to redirect domain names (when the visitor cannot open the page)',
	'chater_list_rejecttype' =>'evaluation',
	'chater_list_rejecttype_alert1' =>'evaluation',
	'chater_list_rejecttype_alert2' =>'chat end or close mandatory evaluation',
	'chater_list_weixintype' =>'Entrance limit',
	'chater_list_weixintype_alert1' =>'evaluation',
	'chater_list_weixintype_alert2' =>'Only allow to open from WeChat',
	'chater_list_cdntype' =>'CDN acceleration',
	'chater_list_cdntype_alert1' =>'evaluation',
	'chater_list_cdntype_alert2' =>'Mobile guest js/css static resource CDN acceleration to solve the problem of slow opening for the first time',
	'chater_list_heartbeat' => 'Heartbeat',
	'chater_list_heartbeat_alert1' => 'Time multiplied (the larger the multiple, the smaller the server load, and the longer the read/unread status acquisition time)',
	'chater_list_showhistory' =>'Chat history',
	'chater_list_showhistory_alert1' =>'Visitors do not display historical chat records',
	'chater_list_voicevideo' =>'Voice video',
	'chater_list_voicevideo_alert1' =>'Voice/video calls are prohibited on the guest side',
	'chater_list_history_alert1' => 'Clear',
	'chater_list_history_alert2' => 'Chat records an hour ago',
	'chater_list_reminder' =>'Timeout reminder',
	'chater_list_reminder_alert1' =>'After receiving visitor information, exceed',
	'chater_list_reminder_alert2' =>'No reply in seconds, the avatar is displayed in a red frame',
	'chater_list_transfer' => 'timeout transfer',
	'chater_list_transfer_alert1' => 'After receiving visitor information, exceeding',
	'chater_list_transfer_alert2' => 'If there is no reply in seconds, automatically transfer to other customer service',
	'chater_list_oldvisitor' =>'Valid visitor expiration date',
	'chater_list_oldvisitor_alert1' =>'in',
	'chater_list_oldvisitor_alert2' =>'Looking for the original customer service chat for the regular customer accessing the session within seconds (the access session after a limited time to find other customer service chats)',
	'chater_list_server_configuration' =>'Server configuration',
	'chater_list_weChat_official_account_configuration' =>'WeChat official account/applet configuration',
	'chater_list_advertising_configuration' =>'Advertising configuration',
	'chater_list_domain' =>'Webpage authorized domain name',
	'chater_list_appid' =>'Developer ID (AppID)',
	'chater_list_sercet' =>'Developer password (AppSecret)',
	'chater_list_token' =>'Token (Token)',
	'chater_list_moban_id' =>'Template message ID',
	'chater_list_subscribe_id' =>'Subscribe notification template ID',
	'chater_list_moban_message1' =>'template message',
	'chater_list_moban_message2' =>'One-time subscription message',
	'chater_list_subscribe' =>'Subscribe to news',
	'chater_list_subscribe1' =>'One-time subscription message',
	'chater_list_subscribe2' =>'Subscribe to notifications',
	'chater_list_subscribe3' =>'Do not push subscription notifications',
	'chater_list_customer_service_link' =>'Passive customer service link',
	'chater_list_wechat_customer_service_link' =>'Active customer service link',
	'chater_list_link1' =>'For example: http://g.rtcim.com/vendor/wx/?act=openid&redirect_uri=http%3A//g.rtcim.com%3A98/kefu.html, the redirect_uri parameter is escape encrypted Customer service link. ',
	'chater_list_domain_alert' =>'Please enter the webpage authorized domain name',
	'chater_list_appid_alert' =>'Please enter the developer ID (AppID)',
	'chater_list_sercet_alert' =>'Please enter the developer password (AppSecret)',
	'chater_list_token_alert' =>'Please enter a token (Token)',
	'chater_list_moban_id_alert' =>'Please enter the template message ID',
	'chater_list_subscribe1_id_alert' =>'Please enter a one-time subscription message template ID',
	'chater_list_subscribe2_id_alert' =>'Please enter the subscription notification template ID',
	'chater_list_subscribe4_id_alert' => 'Please enter the template message/subscription notification received to redirect to the customer service link',
	'chater_list_customer_service_link_alert' =>'Please enter the received template message/subscribe notification to jump to the customer service link',
	'chater_list_wechat_customer_service_link_alert' =>'Please enter the official account/applet custom menu/subscription notification customer service link',
	'chater_list_isminiprogram' => 'Mini program',
	'chater_list_account' => 'official account',
	
	'chater_list_chatgpt_configuration' => 'Robot Settings',
	'chater_list_chatgpt_reception' => 'Default Reception',
	'chater_list_chatgpt_reception1' => 'Intelligent Customer Service',
	'chater_list_chatgpt_reception2' => 'Manual Customer Service',
	'chater_list_chatgpt_reception3' => 'Please Select',
	'chater_list_chatgpt_transfer' => 'Transfer to Manual/Robot',
	'chater_list_chatgpt_transfer_desc' => 'During the reception process, the visitor side displays the switch to manual/robot button',
	'chater_list_chatgpt_autotransfer' => 'Automatic transfer to manual',
	'chater_list_chatgpt_autotransfer_desc' => 'The robot failed to answer',
	'chater_list_chatgpt_autotransfer_desc1' => 'times, automatic to manual',
	'chater_list_chatgpt' => 'ERNIE Bot',
	'chater_list_chatgpt_desc' => 'Intelligent customer service robots answer visitor messages',
	'chater_list_chatgpt_API_Key' => 'API Key',
	'chater_list_chatgpt_API_Key_desc' => 'Please enter the ERNIE Bot API Key',
	'chater_list_chatgpt_Secret_Key' => 'Secret Key',
	'chater_list_chatgpt_Secret_Key_desc' => 'Please enter ERNIE Bot Secret Key',
	'chater_list_chatgpt_API_Url' => 'API Address',
	'chater_list_chatgpt_Model' => 'Default Model',
	'chater_list_chatgpt_Model1' => 'ERNIE-Bot',
	'chater_list_chatgpt_Model2' => 'ERNIE-Bot-turbo',
	'chater_list_chatgpt_Model3' => 'BLOOMZ-7B',
	'chater_list_chatgpt_Model4' => 'Qianfan-BLOOMZ-7B-compressed',
	'chater_list_chatgpt_Model5' => 'Llama-2-7b-chat',
	'chater_list_chatgpt_Model6' => 'Llama-2-13b-chat',
	'chater_list_chatgpt_Model7' => 'Llama-2-70b-chat',
	'chater_list_chatgpt_Model8' => 'Qianfan-Chinese-Llama-2-7B',
	'chater_list_chatgpt_Model9' => 'Linly-Chinese-LLaMA-2-7B',
	'chater_list_chatgpt_Model10' => 'Linly-Chinese-LLaMA-2-13B',
	'chater_list_chatgpt_Model11' => 'ChatGLM2-6B',
	'chater_list_chatgpt_Model12' => 'ChatGLM2-6B-32K',
	'chater_list_chatgpt_Model13' => 'ChatGLM2-6B-INT4',
	'chater_list_chatgpt_Model14' => 'Falcon-7B',
	'chater_list_chatgpt_Model15' => 'Falcon-40B-Instruct',
	'chater_list_chatgpt_Model16' => 'AquilaChat-7B',
	'chater_list_chatgpt_Model17' => 'RWKV-4-World',
	'chater_list_chatgpt_Model18' => 'RWKV-4-pile-14B',
	'chater_list_chatgpt_Model19' => 'RWKV-Raven-14B',
	'chater_list_chatgpt_Model20' => 'OpenLLaMA-7B',
	'chater_list_chatgpt_Model21' => 'Dolly-12B',
	'chater_list_chatgpt_Model22' => 'MPT-7B-Instruct',
	'chater_list_chatgpt_Model23' => 'MPT-30B-instruct',
	'chater_list_chatgpt_Model24' => 'OA-Pythia-12B-SFT-4',
	'chater_list_chatgpt_Model25' => 'Falcon-180B-Chat',
	'chater_list_chatgpt_Model26' => 'RWKV-5-World',
	'chater_list_chatgpt_Model27' => 'Flan-UL2',
	
	'chater_ro_title' => 'Entry Management',
	'chater_ro_add' => 'Add Entry',
	'chater_ro_delete' => 'Delete Entry',
	'chater_ro_name' => 'Name',
	'chater_ro_desc' => 'Description',
	'chater_ro_dt' => 'Create Time',
	'chater_ro_status' => 'Status',
	'chater_ro_to_type' => 'Group Chat',
	'chater_ro_order' => 'Sort',
	'chater_ro_up' => 'Upward',
	'chater_ro_down' => 'Down',
	'chater_ro_attributes' => 'Property',
	'chater_ro_member' => 'Member',
	'chater_ro_tree_title' => 'Select Member',
	
	'user_ro_title' => 'Guest Tag Management',
	'user_ro_add' => 'Add Tag',
	'user_ro_delete' => 'Delete Label',
	'user_ro_name' => 'Name',
	'user_ro_desc' => 'Description',
	'user_ro_dt' => 'Creation Time',
	'user_ro_status' => 'Status',
	'user_ro_order' => 'Sort',
	'user_ro_up' => 'Move Up',
	'user_ro_down' => 'Down Move',
	'user_ro_attributes' => 'Attributes',
	
	'chater_theme_title' =>'Session Theme Management',
	'chater_theme_add' =>'Add Theme',
	'chater_theme_delete' =>'Delete Theme',
	'chater_theme_name' =>'Name',
	'chater_theme_desc' =>'Description',
	'chater_theme_dt' =>'Creation Time',
	'chater_theme_status' =>'Status',
	'chater_theme_order' =>'Order',
	'chater_theme_up' =>'Move Up',
	'chater_theme_down' =>'Move Down',
	'chater_theme_attributes' =>'Attributes',
	'chater_theme_ro' =>'Theme Grouping',
	'chater_theme_ro1' =>'Use Theme',
	'chater_theme_ro2' =>'History Theme',
	
	'chater_domain_title' =>'Domain Name After The Jump',
	'chater_domain_add' =>'Add Domain Name',
	'chater_domain_delete' =>'Delete Domain Name',
	'chater_domain_name' =>'Domain Name Address After The Jump',
	'chater_domain_desc' =>'Description',
	'chater_domain_dt' =>'Creation Time',
	'chater_domain_status' =>'Status',
	'chater_domain_order' =>'Order',
	'chater_domain_name_desc' =>'e.g. http://www.haoqiniao.cn:98 or https://www.haoqiniao.cn',
	
	'chater_wechat_title' =>'WeChat Official Account/Applet Management',
	'chater_wechat_add' =>'Add Official Account/Applet',
	'chater_wechat_delete' =>'Delete Official Account/Applet',
	'chater_wechat_upload' =>'Upload Verification File',
	'chater_wechat_dt' =>'Creation Time',
	'chater_wechat_status' =>'Status',
	
	//admin/lv_manager/file_edit.php
	'file_edit_lb_name' => 'Link Name',
	'file_edit_lb_path' => 'Link Path',
	'file_edit_attach' => 'Upload Attachment',
	'file_edit_btn_upload' => 'Upload',
	
	//admin/lv_manager/file_list.php
	'file_list_title' => 'Attachment Management',
	'file_list_btn_add' => 'Add Public File',
	'file_list_btn_delete' => 'Delete File',
	'file_list_dropdown_type-1' => '--All Types--',
	'file_list_dropdown_type1' => 'Visitor Send',
	'file_list_dropdown_type0' => 'Customer Service',
	'file_list_filed_account' => 'Customer Account',
	'file_list_filed_username' => 'Visitor Name',
	'file_list_filed_chatid' => 'Session ID',
	'file_list_filed_filename' => 'Filename',
	'file_list_ph_key' => 'Keyword',
	'file_list_ph_date' => 'Date',
	'file_list_table_chatid' => 'Session ID',
	'file_list_table_filename' => 'Filename',
	'file_list_table_username' => 'Guest',
	'file_list_table_chater' => 'Customer Service',
	'file_list_table_createdate' => 'Create Time',
	'file_list_edit' => 'Edit',
	'file_list_delete' => 'Delete',
	'file_list_alert' => 'Download Error',
	
	//admin/lv_manager/link_edit.php
	'link_edit_lb_owner' => 'Owner',
	'link_edit_option' => '--Public--',
	'link_edit_lb_name' => 'Link Name',
	'link_edit_lb_path' => 'Link Path',
	'link_edit_attach' => 'Upload Attachment',
	'link_edit_btn_upload' => 'Upload',
	
	
	//admin/lv_manager/link_list.php
	'link_list_title' => 'Link Management',
	'link_list_btn_add' => 'Add Link',
	'link_list_ph_search' => 'Find Links',
	'link_list_table_name' => 'Name',
	'link_list_table_address' => 'Address',
	'link_list_table_owner' => 'Owner',
	'link_list_table_createdate' => 'Create Time',
	'link_list_edit' => 'Edit',
	'link_list_delete' => 'Delete',
	
	//admin/lv_manager/question_edit.php
	'question_edit_lb_subject' => 'Question',
	'question_edit_lb_usertext' => 'Answer',
	'question_edit_lb_usertext_desc' => 'Please enter an answer',
	
	
	//admin/lv_manager/question_list.php
	'question_list_title' => 'Q&A Library',
	'question_list_btn_add' => 'Add Question',
	'question_list_ph_search' => 'Find Questions',
	'question_list_table_name' => 'Question',
	'question_list_table_address' => 'Answer',
	'question_list_table_createdate' => 'Creation Time',
	'question_list_edit' => 'Edit',
	'question_list_delete' => 'Delete',
	
	'quicktalk_edit_lb_subject' => 'Title',
	'quicktalk_edit_lb_usertext' => 'Content',
	'quicktalk_edit_lb_usertext_desc' => 'Please enter a title',
	
	//admin/lv_manager/question_list.php
	'quicktalk_list_title' => 'Common Language Management',
	'quicktalk_list_btn_add' => 'New Common Words',
	'quicktalk_list_ph_search' => 'Find Common Words',
	'quicktalk_list_table_name' => 'Title',
	'quicktalk_list_table_address' => 'Content',
	'quicktalk_list_table_createdate' => 'Create Time',
	'quicktalk_list_edit' => 'Edit',
	'quicktalk_list_delete' => 'Delete',
	
	
	//admin/lv_manager/message_list.php
	'message_list_title' =>'Message Management',
	'message_list_groupid' =>'Please Select The Source',
	'message_list_not' =>'Public Conversation',
	'message_list_option_username' =>'Name',
	'message_list_option_phone' =>'Phone',
	'message_list_option_email' =>'Mailbox',
	'message_list_option_content' =>'Content',
	'message_list_option_userid' =>'User ID',
	'message_list_ph_key' =>'Keyword',
	'message_list_ph_date' =>'Message Date',
	'message_list_table_source' =>'Source',
	'message_list_table_username' =>'Name',
	'message_list_table_phone' =>'Phone',
	'message_list_table_email' =>'Mailbox',
	'message_list_table_createtime' =>'Time',
	'message_list_table_note' =>'Content',
	
	//admin/lv_manager/rate_list.php
	'rate_list_title' => 'Evaluation Management',
	'rate_list_option_account' => 'Customer Account',
	'rate_list_option_username' => 'Visitor Name',
	'rate_list_option_userid' => 'Visitor ID',
	'rate_list_ph_key' => 'Keyword',
	'rate_list_ph_date' => 'Session Date',
	'rate_list_table_chatid' => 'Session ID',
	'rate_list_table_operator' => 'Customer Service',
	'rate_list_table_userid' => 'User ID',
	'rate_list_table_name' => 'Name',
	'rate_list_table_score' => 'Score',
	'rate_list_table_des' => 'Description',
	'rate_list_table_date' => 'Time',
	
	'blackip_list_title' =>'Blacklist IP Record',
	'blackip_list_option_account' =>'Customer Service Account',
	'blackip_list_option_username' =>'Visitor Name',
	'blackip_list_option_userid' =>'Visitor ID',
	'blackip_list_ph_key' =>'Keyword',
	'blackip_list_ph_date' =>'Session Date',
	'blackip_list_table_chatid' =>'Session ID',
	'blackip_list_table_operator' =>'Customer Service',
	'blackip_list_table_userid' =>'User ID',
	'blackip_list_table_name' =>'Name',
	'blackip_list_table_score' =>'Score',
	'blackip_list_table_des' =>'Description',
	'blackip_list_table_date' =>'Time',
	
	
	//admin/lv_manager/user_list.php
	'user_list_title' => 'Guest Management',
	'user_list_option_name' => 'Name',
	'user_list_option_phone' => 'Telephone',
	'user_list_option_email' => 'Mailbox',
	'user_list_ph_key' => 'Keyword',
	'user_list_table_name' => 'Name',
	'user_list_table_phone' => 'Phone', //'
	'user_list_table_email' => 'Mailbox',
	'user_list_table_chater' =>'Priority Reception Customer Service',
	'user_list_table_remarks' =>'Remarks',
	'user_list_table_regtime' => 'Registration Time',
	'user_list_table_chat' => 'Talk',
	'user_list_table_message' => 'Message',
	'user_list_table_attach' => 'Attachment',
	
	
	//admin/report/attach_list.php
	'attach_list_tittle' => 'Attachment Query',
	'attach_list_ph_search' => 'Attachment Lookup',
	'attach_list_table_messageid' => 'Message ID',
	'attach_list_table_sender' => 'Sender',
	'attach_list_table_recipient' => 'Recipient',
	'attach_list_table_senddate' => 'Send Time',
	'attach_list_table_content' => 'Message Content',
	'attach_list_table_filename' => 'Filename',
	'attach_list_table_filesize' => 'Size',
	'attach_list_table_filetype' => 'Type',
	'attach_list_table_fileguid' => 'File ID',
	'attach_type_screenhot' => 'Screenshot',
	'attach_type_file' => 'Plain File',
	
	//admin/report/board_list.php
	'board_list_title' => 'Announcement Query',
	'board_list_option_title' => 'Title',
	'board_list_option_creator' => 'Sender',
	'board_list_table_title' => 'Title',
	'board_list_table_creator' => 'Sender',
	'board_list_table_senddate' => 'Send Date',
	'board_list_delete' => 'Delete',
	
	//admin/report/chat_list.php
	'chat_list_title' =>'Dialog Query',
	'chat_list_txt_account1' =>'Account 1:', //':'
	'chat_list_txt_account2' =>'Account 2:', //':'
	'chat_list_txt_account3' =>'Group Number:', //':'
	'chat_list_txt_account4' =>'Customer Service Account:', //':'
	'chat_list_txt_account5' =>'Guest Account:', //':'
	'chat_list_alert_none' =>'No Data',
	'chat_list_alert_enteraccount' =>'Please enter the account number of the conversation person',
	
	//admin/report/log_list.php
	'log_list_title' => 'Login Log',
	'log_list_option' => 'Login/Exit',
	'log_list_option1' => 'Login',
	'log_list_option2' => 'Exit',
	'log_list_option3' => 'Console Login',
	'log_list_ph_search' => 'Find Account Number',
	'log_list_table_account' => 'Account',
	'log_list_table_name' => 'Name',
	'log_list_table_date' => 'Time',
	'log_list_table_sign' => 'Login/Exit',
	'log_list_table_ip' => 'IP Address',
	'log_list_table_mac' => 'MAC Address',
	
	
	//admin/report/msg_list.php
	'msg_list_title' => 'Message Query',
	'msg_list_option_subject' => 'Title',
	'msg_list_option_senderaccount' => 'Send Account',
	'msg_list_option_sendername' => 'Send Name',
	'msg_list_table_subject' => 'Title',
	'msg_list_table_sender' => 'Sender',
	'msg_list_table_receiver' => 'Receiver',
	'msg_list_table_senddate' => 'Send Date',
	'msg_list_table_datapath' => 'Data Directory',
	'msg_list_table_sendermac' => 'MAC Address',
	'msg_list_table_senderip' => 'IP Address',
	'msg_list_table_chat' => 'Enter Chat',
	'msg_list_groupid' => 'Please Select A Group',
	'msg_list_pid' => 'Please Select An Entry',
	
	//admin/report/msg_total.php
	'msg_total_title' => 'Message Statistics',
	'msg_total_option_subject' => 'Title',
	'msg_total_option_sender' => 'Sender',
	'msg_total_table_subject' => 'Title',
	'msg_total_table_sender' => 'Sender',
	'msg_total_table_senddate' => 'Send Date',
	'msg_total_table_datapath' => 'Data Directory',
	'msg_total_table_sendermac' => 'MAC Address',
	'msg_total_table_senderip' => 'IP Address',
	
	
	//admin/report/online_list.php
	'online_list_title' => 'Online User',
	'online_list_onlineuser' => 'Online User: ',
	'online_list_totaluser' => 'Total Number Of Users: ',
	'online_list_table_account' => 'Account',
	'online_list_table_user' => 'User',
	'online_list_table_logintime' => 'Login Time',
	'online_list_table_manufacturer' => 'Brand',
	'online_list_table_mac' => 'MAC Address',
	'online_list_table_ip' => 'IP Address',
	'online_list_table_version' => 'Status',
	'online_list_table_usericoLine1' => 'Online',
	'online_list_table_usericoLine2' => 'Leave',
	'online_list_table_usericoLine3' => 'Mobile Online',
	
	//admin/report/sms_list.php
	'sms_list_title' => 'SMS Statistics',
	'sms_list_btn_batchdel' => 'Bulk Delete',
	'sms_list_table_sender' => 'Sender',
	'sms_list_table_content' => 'Content',
	'sms_list_table_recipient' => 'Recipient',
	'sms_list_table_sendtime' => 'Send Time',
	'sms_list_table_status' => 'Status',
	'sms_list_delete' => 'Delete',
	
	//admin/report/sms_recv_list.php
	'sms_recv_list_title' => 'SMS Receive',
	'sms_recv_list_btn_batchdel' => 'Bulk Delete',
	'sms_recv_list_table_content' => 'Content',
	'sms_recv_list_table_recipient' => 'Recipient',
	'sms_recv_list_table_sendtime' => 'Send Time',
	'sms_recv_list_table_status' => 'Status',
	'sms_recv_list_delete' => 'Delete',
	
	//admin/set/base.php
	'base_title' => 'Basic Settings',
	'base_alert_success' => 'Successfully Modified.',
	'base_lb_companyname' => 'Unit Name',
	'base_lb_companyid' => 'Unit ID',
	'base_lb_port' => 'Port Number',
	'base_lb_directory' => 'Data Directory',
	'base_btn_save' => 'Save Settings',
	
	//admin/set/board_send.php
	'board_send_title' => 'Send Announcement',
	'board_send_alert_success' => 'Successful. ',
	'board_send_lb_psw' => 'Send Password',
	'board_send_lb_type' => 'Send Type',
	'board_send_lb_onlineuser' => 'Online User',
	'board_send_lb_alluser' => 'All Users',
	'board_send_lb_content' => 'Send Content',
	'board_send_btn_publish' => 'Send Announcement',
	
	//admin/set/dw.php
	'dw_title' => 'Personalization',
	'dw_alert_success' => 'The modification was successful. ',
	'dw_lb_unify' => 'Unified Avatar',
	'dw_recommend' => 'Recommended With 95*95 Pixels',
	'dw_clear' => 'Clear Avatar',
	'dw_save' => 'Save Settings',
	
	
	//admin/set/ios_set.php
	'ios_set_lb_psw' => 'Api Master Password',
	'ios_set_ph_psw' => 'iOS API Master Password',
	
	//admin/set/port_edit.php
	'port_edit_lb_port' => 'Port',
	'port_edit_ph_port' => 'Port',
	
	
	//admin/set/service.php
	'service_title' => 'Service Control',
	'service_btn_launch' => 'Start Service',
	'service_btn_restart' => 'Restart Service',
	'service_btn_stop' => 'Stop Service',
	'service_table_name' => 'Name',
	'service_table_des' => 'Description',
	'service_table_portaddress' => 'Port Address',
	'service_table_porttype' => 'Port Type',
	'service_table_status' => 'Status',
	'service_table_change' => 'Modify',
	'service_data_messge' => 'Message Server',
	'service_data_video' => 'Video Server',
	'service_data_doc' => 'Document Service',
	'service_data_file' => 'File Service',
	'service_data_meeting' => 'Conference Service',
	'service_data_meetingforward' => 'Conference Transfer Service',
	'service_data_main' => 'Master Server',
	'service_data_netrelay' => 'P2p Transport Service',
	'service_data_site' => 'Php Web Service',
	'service_data_upload' => 'Upload Service',
	'service_data_download' => 'Download Service',
	'service_data_telnet'=>'Remote Service',
	'service_data_setverpic' => 'Image Transfer Service',
	'service_data_zlchat' => 'Video Conferencing - Main Service',
	'service_data_apache' => 'Video Conferencing-Web Service',
	'service_data_mysql' => 'Video Conferencing - Database Server',
	
	
	//admin/set/set.php
	'set_title' => 'System Settings',
	'set_alert_success' => 'Setting success. ',
	'set_alert_restart' => 'You need to restart the service to take effect',
	'set_alert_restartnow' => 'Restart now',
	'set_legend_server' => 'server settings',
	'set_legend_client' => 'Client Configuration',
	'set_legend_integrate' => 'System Integration Settings',
	'set_legend_webserver' => 'Web Manager Configuration',
	'set_checkbox_disable_save' => 'Disable the server to save messages',
	'set_checkbox_enable_permission' => 'Enable organization permission control',
	'set_checkbox_system' => 'Start system verification',
	'set_checkbox_verify' => 'Start users through Active Directory',
	'set_checkbox_disable_bulletin' => 'Forbidden announcement',
	'set_checkbox_disable_changepsw' => 'Disable client to change password',
	'set_checkbox_disable_groupsharefile' => 'Disallow group sharing files',
	'set_checkbox_disable_creategroup' => 'Disable client creation of groups',
	'set_checkbox_allow_creategroup_board' => 'Allow creation of brokerage group',
	'set_checkbox_search' => 'Filter search',
	'set_checkbox_delete' => 'auto clear',
	'set_checkbox_days' => 'Pre-day messages and files',
	'set_btn_manually' => 'Manually clear messages',
	'set_checkbox_record' => 'record login log information',
	'set_checkbox_directory' => 'directory of data storage',
	'set_checkbox_datasync' => 'Enable data sync push',
	'set_datasync_url' => 'data sync address',
	'set_checkbox_disable_saving' => 'Forbid client to save messages',
	'set_checkbox_disable_hyperlink' => 'Disable clients hyperlink',
	'set_checkbox_disable_invisible' => 'Disable client to show offline',
	'set_checkbox_allow_p2p' => 'Allow file P2P transfer',
	'set_checkbox_p2p_threshold' => 'threshold',
	'set_checkbox_disable_note' => 'Disable the client to display the notification of the other party opening the message',
	'set_checkbox_away' => 'Support for automatic leave function',
	'set_checkbox_minutes' => 'minute',
	'set_checkbox_disable_mylink' => 'Disable URL collection feature',
	'set_checkbox_enable_online' => 'Enable multi-device simultaneous online',
	'set_checkbox_enable_forwarding' => 'Enable audio and video relay service',
	'set_checkbox_enable_loginverify' => 'Enable third-party login verification (requires custom development)',
	'set_loginverify_url' => 'Access third-party application verification address',
	'set_antserver_access_url' => 'Access Server push address',
	'set_push' => 'IOS push settings',
	'set_btn_setting' => 'Settings',
	'set_checkbox_transcode' => 'Automatic transcoding of uploaded videos',
	'set_checkbox_publicdocuments_file_type' => 'Some columns in public documents are not displayed',
	'set_checkbox_publicdocuments' => 'Public documents/images/music/videos/recent updates/search results not displayed',
	'set_checkbox_publicdocuments_file_type_view' => 'Some columns of public documents are not displayed without viewing permission',
	'set_checkbox_publicdocuments_view' => 'Public documents/images/music/videos/recent updates/search results will not be displayed without viewing permission(enabling will increase server burden)',
	'set_livechat' => 'Online duty',
	'set_openplatform' => 'PHP 7 or higher version',
	'set_inquirybox' => 'Cloud disk uploads a file with the same name and pops up a question box (do you want to replace it)',
	'set_enpmessage' => 'Data Transfer Encryption',
	'set_verifyuserdevice'=>'Enable device number verification',//'启用设备号验证'
	'set_userapply' => 'Client application account',
	'set_userapply0' => 'requires administrator review',
	'set_userapply1' => 'After applying, you can use',
	'set_userapply2' => 'Prohibit application',
	'set_chats' => 'The server saves the chat history (it will increase the server load when enabled)',
	'set_logs' => 'The server saves the transaction log (which will increase the server load when enabled)',
	'set_control_computer' => 'Control computer (server control client computer)',
	'set_lock_screen' => 'Automatically lock the interface after the server program starts',
	'set_offline_information' => 'Offline information, forwarded to SMS (must enable SMS)',
	'set_minimize' => 'Automatically minimize the interface after the server program starts',
	'set_CheckIM0' => 'The administrator receives system messages (eg user registration audit, cloud disk / group file audit)',
	'set_CheckIM1' => 'The computer and the mobile phone are online at the same time, the computer version account is online, and the mobile version account can also receive the push message',
	'set_delete_chats' => 'Server automatically deletes chat history',
	'set_delete_chats1' => 'records 15 days ago',
	'set_delete_chats2' => 'records 60 days ago',
	'set_delete_chats3' => 'Do not delete',
	'set_delete_offline_files' => 'Server automatically deletes offline files',
	'set_delete_offline_files1' => 'files 15 days ago',
	'set_delete_offline_files2' => 'files 60 days ago',
	'set_delete_offline_files3' => 'Do not delete',
	'set_message_push' => 'Mobile app message push interval',  
	'set_message_push1' => 'seconds (the smaller the value, the faster the message push, but at the same time, the greater the server resource consumption)',
	'set_delete_server_files' =>'When the server files reach the disk',
	'set_delete_server_files1' =>'% Automatically delete server files (to prevent full disk from damaging the disk)',
	'set_delete_offline_notices' => 'auto clear',
	'set_noticeday' => 'Offline notifications before the day',
	'set_chatsday' =>'Chat history one day ago',
	'set_port' => 'port description',
	'set_port_description' => 'Basic communication ports: 97, 98, 99, 5994, 5995, 5996, 5997 (udp), 5998 (udp), 6001, 6002, 6003, 6004, 6005, 6006, 6007, 6008, a total of 16 ports, please ensure the server The ports are already open.',
	
	'set_login_error_count' => 'The number of background login errors is limited to ',
	'set_login_error_count_tip' => '0 is not restricted',
	
	//admin/set/skin_list.php
	'skin_list_title' => 'Skin Management',
	'skin_list_show' => 'Click To View Larger Image',
	'skin_list_preview' => 'Preview',
	
	//admin/set/server_list.php
	'server_list_title' => 'Server Management (Multiple Instant Messaging Service High Availability Solution)',
	'server_list_ip' => 'IP',
	'server_list_name' => 'Name',
	'server_init_all' => 'Synchronize All Server Initialization Data',
	
	//admin/set/update.php
	'update_type_pc' => 'PC Side',
	'update_type_android' => 'Android',
	'update_title' => 'Upgrade Management',
	'update_alert_success' => 'Imported Successfully',
	'update_restart' => 'You need to restart the service to take effect',
	'update_alert_restartnow' => 'Restart Now',
	'update_lb_version' => 'Version Number',
	'update_ib_package' => 'Update Package',
	'update_btn_delpackage' => 'Delete Update Package',
	'update_lb_uploadpackage' => 'Upload Update Package',
	'update_btn_upload' => 'Upload Update Package',
	'update_alert_delsuccess' => 'Delete Successfully',
	'update_alert_selectpackage' => 'Please select update package',
	
	//admin/set/user_change.php
	'user_change_title' => 'Personnel Data Migration',
	'user_change_old' => 'User Original Account',
	'user_change_new' => 'User New Account',
	'user_change_btn' => 'Confirm',
	'user_change_warning'=> 'Prompt: This is to modify the personnel account, migrate the original account message, announcement and other data to the new account. Please confirm if you want to modify the staff account! ! ! ',
	'user_change_require'=> 'The account is not allowed to be empty',
	
	//admin/tools/addin_edit.php
	'addin_edit_lb_type' => 'Plugin Type',
	'addin_edit_option0' => 'Plugin Package',
	'addin_edit_option1' => 'Command Plugin',
	'addin_edit_option2' => 'View Plugin',
	'addin_edit_lb_status' => 'Status',
	'addin_edit_option_normal' => 'Normal',
	'addin_edit_lb_option_disabled' => 'Disabled',
	'addin_edit_lb_public' => 'Do you want to make it public',
	'addin_edit_option_yes' => 'Yes',
	'addin_edit_option_no' => 'No',
	'addin_edit_lb_sequence' => 'Sort',
	
	
	//admin/tools/addin_list.php
	'addin_sms' => 'SMS Plugin',
	'addin_list_title' => 'Plugin Management',
	'addin_list_btn_search' => 'Plugin Lookup',
	'addin_list_btn_import' => 'Import Plugin',
	'addin_list_btn_add' => 'Add A Plugin',
	'addin_list_btn_permission' => 'Set Permissions',
	'addin_list_btn_delete' => 'Delete Plugin',
	'addin_list_install' => 'Install System Plugin',
	'addin_list_roam' => 'Message Roaming',
	'addin_list_bulletin' => 'Announcement Query',
	'addin_list_operator' => 'Online Customer Service',
	'addin_list_option_type' => 'Select Type',
	'addin_list_option_command' => 'Command Plugin',
	'addin_list_option_view' => 'View Plugin',
	'addin_list_ph_search' => 'Plugin Lookup',
	'addin_list_table_type' => 'Category',
	'addin_list_table_name' => 'Name',
	'addin_list_table_public' => 'Public',
	'addin_list_table_disable' => 'Disabled',
	'addin_list_table_desc' => 'Description',
	'addin_list_table_package' => 'Plugin Package',
	'addin_list_table_sequence' => 'Sort',
	'addin_list_table_edit' => 'Modify',
	'addin_list_table_permission' => 'Permission',
	'addin_list_table_del' => 'Delete',
	'addin_list_table_up' => 'Upward',
	'addin_list_table_down' => 'Down',
	'addin_list_add' => 'Add A Plugin',
	'addin_list_edit' => 'Modify Plugin',
	'addin_plug_name' => 'Plugin Name',
	'addin_plug_displayname' => 'Displayed Name',
	'addin_plug_target' => 'URL Address',
	'addin_plug_desc' => 'Description',
	'addin_plug_width' => 'Window Width',
	'addin_plug_width_desc' => 'Open the width of the mini window',
	'addin_plug_height' => 'Window Height',
	'addin_plug_height_desc' => 'Open the height of the mini window',
	'addin_plug_param' => 'Parameters',
	'addin_plug_image' => 'Address Of The Picture',
	'addin_plug_site' => 'Plugin Type',
	'addin_plug_site0' => 'SMS',
	'addin_plug_site1' => 'Mailbox',
	'addin_plug_site2' => 'Main Menu',
	'addin_plug_site3' => 'User Card',
	'addin_plug_site4' => 'User Card Button',
	'addin_plug_site5' => 'User List Selects A Persons Right-Click Menu',
	'addin_plug_site6' => 'Group List Select Groups Right-Click Menu',
	'addin_plug_site7' => 'Mobile Main Menu Main Menu',
	'addin_plug_site7' => 'Mobile Main Menu Main Menu',
	'addin_plug_site8' => 'Mobile User More Menu Options',
	'addin_plug_site9' => 'Mobile Group More Menu Options',
	'addin_plug_site10' => 'Message Roaming',
	'addin_plug_site11' => 'Message Push',
	'addin_plug_site12' => 'Real-Time Audio And Video',
	'addin_plug_site13' => 'Message Mail Push',
	'addin_plug_site14' => 'Other',
	'addin_plug_targettype' => 'Target Program Open Method',
	'addin_plug_targettype1' => 'Open Inside The Client',
	'addin_plug_targettype2' => 'Open In Browser',
	'addin_plug_targettype3' => 'Other',
	'addin_plug_bie' => 'Third-Party System Number',
	'addin_plug_enabled' => 'Status',
	'addin_plug_enabled1' => 'Normal',
	'addin_plug_enabled0' => 'Disabled',
	'addin_plug_warning' => 'The third-party system number must be a positive integer',
	'addin_plug_warning1' => 'The system built-in plugin does not allow this operation',
	'addin_plug_warning2' => 'Online documentation plugin is off',
	
	//admin/tools/client_edit.php
	'client_edit_lb_title' => 'Upload Client',
	'client_edit_lb_name' => 'Client Name',
	'client_edit_ph_name' => 'Client Name',
	'client_edit_lb_version' => 'Version Number',
	'client_edit_ph_version' => 'Client Version',
	
	
	//admin/tools/client_list.php
	'client_list_lb_title' => 'Client Program Release',
	'client_list_btn_add' => 'Add Client',
	'client_list_btn_delete' => 'Delete Client',
	'client_list_ph_search' => 'Find Client Name Or Version',
	'client_list_table_name' => 'Client Name',
	'client_list_table_version' => 'Version',
	'client_list_table_size' => 'Size',
	'client_list_table_edit' => 'Edit',
	'client_list_table_download' => 'Download Link',
	'client_list_table_del' => 'Delete',
	
	
	
	//admin/tools/dept_picker.php
	'dept_picker_lb_deletedept' => 'Delete Previous Department',
	'dept_picker_alert_adduser' => 'Cannot set the person to the root node',
	
	
	//admin/tools/ext_edit.php
	'ext_edit_option_ADSServer' => 'Document Service Address',
	'ext_edit_option_ADSPort' => 'Document Service Port',
	'ext_edit_option_AVServerAddr' => 'Audio Video Service Address',
	'ext_edit_option_AVServerPort' => 'Audio Video Service Port',
	'ext_edit_option_FileServerAddr' => 'File Service Address',
	'ext_edit_option_FileServerPort' => 'File Service Port',
	'ext_edit_option_RoamingMessageUrl' => 'Roaming Message Address',
	'ext_edit_lb_data' => 'Data',
	'ext_edit_lb_type' => 'Category',
	
	
	//admin/tools/ext_list.php
	'ext_list_title' => 'Extended Attribute',
	'ext_list_btn_add_custom' => 'Custom Extension',
	'ext_list_btn_add_sys' => 'System Extension',
	'ext_list_btn_bulid' => 'Generate System Configuration',
	'ext_list_ph_search' => 'Property Lookup',
	'ext_list_table_name' => 'Name',
	'ext_list_table_desc' => 'Description',
	'ext_list_table_data' => 'Data',
	'ext_list_table_edit' => 'Modify',
	'ext_list_table_del' => 'Delete',
	'ext_list_col_ADSServer' => 'Document Service Address',
	'ext_list_col_ADSPort' => 'Document Service Port',
	'ext_list_col_AVServerAddr' => 'Audio Video Service Address',
	'ext_list_col_AVServerPort' => 'Audio Video Service Port',
	'ext_list_col_FileServerAddr' => 'File Service Address',
	'ext_list_col_FileServerPort' => 'File Service Port',
	'ext_list_col_RoamingMessageUrl' => 'Roaming Message Address',
	'ext_list_add' => 'Add Attribute',
	'ext_list_change' => 'Modify Attribute',
	
	
	//admin/tools/interface_edit.php
	'interface_edit_lb_name' => 'Name',
	'interface_edit_lb_address' => 'Address',
	'interface_edit_lb_public' => 'Public',
	'interface_edit_public_yes' => 'Yes',
	'interface_edit_public_no' => 'No',
	'interface_edit_lb_status' => 'Status',
	'interface_edit_status0' => 'Normal',
	'interface_edit_status1' => 'Disabled',
	'interface_edit_lb_desc' => 'Description',
	'interface_edit_lb_sequence' => 'Sort',
	'interface_edit_lb_type' => 'Type',
	'interface_edit_type0' => 'All',
	'interface_edit_type1' => 'PC-Side Application',
	'interface_edit_type2' => 'Android App',
	'interface_edit_type3' => 'iOS App',
	'interface_edit_entername' => 'Please enter a name',
	'interface_edit_enteraddress' => 'Please enter the address',
	
	
	//admin/tools/interface_list.php
	'interface_list_title' => 'Interface Management',
	'interface_list_btn_add' => 'Add Interface',
	'interface_list_btn_batch' => 'Batch Operations',
	'interface_list_dropdown_permission' => 'Set Permissions',
	'interface_list_dropdown_del' => 'Delete',
	'interface_list_ph_search' => 'Interface Lookup',
	'interface_list_table_name' => 'Name',
	'interface_list_table_address' => 'Address',
	'interface_list_table_type' => 'Type',
	'interface_list_table_disable' => 'Disabled',
	'interface_list_table_sequence' => 'Sort',
	'interface_list_table_edit' => 'Modify',
	'interface_list_table_permission' => 'Permission',
	'interface_list_table_del' => 'Delete',
	'interface_list_table_up' => 'Upward',
	'interface_list_table_down' => 'Down',
	'interface_list_type0' => 'All',
	'interface_list_type1' => 'PC-Side Application',
	'interface_list_type2' => 'Android App',
	'interface_list_type3' => 'iOS App',
	'interface_list_add' => 'Add Interface',
	'interface_list_change' => 'Modify Interface',
	
	
	//admin/tools/sms_account.php
	'sms_account_title' => 'SMS Account',
	'sms_account_btn_assign' => 'Assign',
	'sms_account_table_account' => 'Account',
	'sms_account_table_psw' => 'Password',
	'sms_account_table_dept' => 'Department',
	'sms_account_table_edit' => 'Modify',
	'sms_account_table_del' => 'Delete',
	
	
	//admin/tools/sms_account_edit.php
	'sms_account_edit_lb_account' => 'Send Account',
	'sms_account_edit_lb_psw' => 'Send Password',
	'sms_account_edit_lb_dept' => 'Select Department',
	'sms_account_edit_btn_select' => 'Select Department',
	
	'field_online_lasttime' => 'Last Login',
	'field_online_status' => 'Whether Online',
	
	//admin/tools/view_url.php
	'view_url_link' => 'Download Link',
	
	'valid_db_connect_error' => 'Database connection failed, please check connection configuration or reset connection',
	
	
	'imp_map_warning' => 'The attribute items are separated by tabs, and multiple lines are separated by line breaks',
	'btn_impmap' => 'Import Person Mapping',
	
	'update_software_upgrade' => 'Software Upgrade',
	'update_product_website' => 'Product URL',
	'update_warning' => 'The software is not the latest version, please open www.haoqiniao.cn to download the latest version or contact customer service to get offline upgrade package.',
	'update_download' => 'Download Offline Upgrade Package',
	
	'set_client_configuration' => 'Client Installation Package Configuration',
	'set_client_warning' => 'Generate the client installation package successfully. ',
	'set_client_download' => 'Download Now',
	'set_client_basic_settings' => 'Basic Settings',
	'set_client_WebName' => 'Company Name',
	'set_client_WebNa' => 'Shortcut',
	'set_client_WebNa_desc' => 'software shortcuts displayed on the client computer',
	'set_client_WebRun' => 'The Website Pops Up When The Client Starts',
	'set_client_logo' => 'Company Logo',
	'set_client_edit_logo' => 'Change Logo',
	'set_client_delete_logo' => 'Clear Logo',
	'set_client_banner' => 'Company Banner',
	'set_client_edit_banner' => 'Change Banner',
	'set_client_delete_banner' => 'Clear Banner',
	'set_client_pan' => 'Cloud Disk Logo',
	'set_client_server_connection' => 'Server Connection',
	'set_client_ServerIp' => 'IP Address',
	'set_client_ServerIp_desc' => 'Multiple Ips Separated By Commas',
	'set_client_Option1' => 'Connection Method',
	'set_client_Option10' => 'IP Address',
	'set_client_Option11' => 'Domain Name',
	'set_client_Option12' => 'Computer Name',
	'set_client_Server_CheckIM1' => 'Automatic Login',
	'set_client_Server_CheckIM2' => 'Remember Password',
	'set_client_software_settings' => 'Software Settings',
	'set_client_CheckIM0' => 'When The Windows System Starts, Enable This Software',
	'set_client_CheckIM1' => 'Main Panel, Always Showing Front',
	'set_client_CheckIM2' => 'Use Large Icon',
	'set_client_CheckIM3' => 'Apply Sound Theme Effect',
	'set_client_CheckIM4' => 'Auto Pop Up Message Form',
	'set_client_CheckIM5' => 'Disable All Prompts (Information)',
	'set_client_CheckIM6' => 'After The File Transfer Is Complete, Open The Folder',
	'set_client_CheckIM7' => 'Enable Hotkey Function',
	'set_client_CheckIM8' => 'Prohibit User Business Card Tips',
	'set_client_CheckIM9' => 'Update Data When Logging In',
	'set_client_CheckIM11' => 'Merge Session Window',
	'set_client_CheckIM13' => 'Hide The Window When Screenshots',
	'set_client_CheckIM14' => 'Text Mode',
	'set_client_CheckTab5' => 'Show System Mailbox Button',
	'set_client_CheckTab6' => 'Show Cloud Button',
	'set_client_CheckTab9' => 'Show Main Menu Button',
	'set_client_CheckTab10' => 'Show Advanced Settings',
	'set_client_CheckTab11' => 'Show All Message Record Buttons',
	'set_client_CheckTab12' => 'Show File Helper Button',
	'set_client_CheckTab13' => 'Show Favorite Button',
	'set_client_CheckTab14' => 'Show Search Button',
	'set_client_HotKey0' => 'Extract Message Shortcuts',
	'set_client_HotKey1' => 'Screen Screenshot Shortcut',
	
	'msg_list_expired' =>'This function has expired, please contact customer service to purchase authorization',
	//admin/tools/keywords_list
	'keywords_type'=>'Filter_type',//'过滤类型'
	'keywords_content'=>'Filter_content',//'过滤内容'
	'enable_keyword'=>'Filter keywords',  //'启用敏感词过滤'
	'enable_customerservicemode'=>'Customer Service Mode',
	'keywords_type_one'=> 'Scheme one: filter word change * send',//'方案一：过滤词变*发送'
	'keywords_type_two'=> 'Program two: there is a filter word can not be sent',//'方案二：有过滤词不能发
)
;
?>
