<?php
return array(

    'time_out_warning' => '请先登录再进行操作',
	

    'menu_sup_org' => '组织管理',
    'menu_sup_set' => '系统工具',
    'menu_sup_ext' => '扩展功能',
    'menu_sup_report' => '查询统计',
    'menu_sup_doc' => '文档管理',
    'menu_sup_syncpush' => '数据推送',
	'menu_sup_platform' => '开放平台', 
	'menu_sup_duty' => '在线值班',


    'menu_sub_org' => '组织管理',
    'menu_sub_user' => '人员管理',
    'menu_sub_role' => '角色管理',
    'menu_sub_grant' => '授权管理',
    'menu_sub_group' => '群组管理',
    'menu_sub_pos' => '铭牌管理',
    'menu_sub_tag' => '标签管理',


    'menu_sub_service' => '服务控制',
    'menu_sub_set' => '系统设置',
	'menu_sub_webserver' => '后台设置',
    'menu_sub_update' => '升级管理 ',
    'menu_sub_hl' => '单位互联',
    'menu_sub_skin' => '皮肤管理',
	'menu_sub_server' => '服务器管理',
    'menu_sub_change' => '迁移管理',
		
    'menu_sub_addin' => '插件管理',
    'menu_sub_interface' => '接口管理',
    'menu_sub_ext' => '扩展设置',
	'menu_sub_filter' => '敏感词过滤',
    'menu_sub_client' => '程序发布',
    'menu_sub_config_fh' => '集成配置',
    'menu_sub_sms_account' => '短信帐号',

    'menu_sub_msg' => '私聊消息查询',
    'menu_sub_chatlist' => '私聊查询',
    'menu_sub_groupmsg' => '群聊消息查询',
    'menu_sub_groupchatlist' => '群聊查询',
    'menu_sub_livechatmsg' => '客服消息查询',
    'menu_sub_livechatlist' => '客服查询',
    'menu_sub_groupkefumsg' => '客服群聊消息查询',
    'menu_sub_groupkefuchatlist' => '客服群聊查询',
    'menu_sub_attach' => '附件查询',
    'menu_sub_msgtotal' => '消息统计',
    'menu_sub_online' => '在线用户',
    'menu_sub_board' => '公告信息',
    'menu_sub_log' => '登录日志',
    'menu_sub_sms' => '短信统计',
	'menu_sub_recsms' => '短信接收',
	'menu_sub_orgreport' => '组织统计',
	'menu_sub_livechat_msg' => '客服消息',
    'menu_sub_public_file' => '公共文档',
    'menu_sub_person_file' => '个人文档',
    'menu_sub_group_file' => '群组文件',
    'menu_sub_leave_file' => '离线文件',

    'menu_sub_config' => '文档配置',
    'menu_sub_store' => '文档存储',
    'menu_sub_doclog' => '文档日志',
	
    'menu_sub_syncpush_set' => '推送设置',
	'menu_sub_syncpush_org' => '推送组织',
    'menu_sub_syncpush_log' => '推送日志',
	
	'menu_sup_platform_app' => '应用管理', 
	'menu_sup_platform_token' => '令牌查看', 
	
    'menu_sub_operator' => '客服管理',
	'menu_sub_entrance' => '入口管理',
    'menu_sub_dialog_analysis' => '会话分析',
    'menu_sub_dialog' => '会话管理',
    'menu_sub_message' => '留言管理',
	'menu_sub_livemsg' => '留言查询',
    'menu_sub_rate' => '评价管理',
	'menu_sub_transfer' => '转接记录',
    'menu_sub_blackip' => '黑名单ip记录',
    'menu_sub_attachment' => '附件管理',
	'menu_sub_dialog_theme' => '会话主题管理',
    'menu_sub_visitor_label' => '访客标签管理',
    'menu_sub_visitor' => '访客管理',
    'menu_sub_link' => '链接管理',
	'menu_sub_quicktalk' => '常用语管理',
	'menu_sub_question' => '问答库',
	'menu_sub_config_lv' => '客服配置',
	'menu_sub_domain' => '域名管理',
	'menu_sub_wechat' => '公众号/小程序管理',
	
	'menu_sub_permission' => '授权管理',
	
	'btn_reset_viewid' => '重置人员关系',
	'btn_autocreate' => '自动创建',
	'btn_set' => '设置',
    'btn_login' => '登录',
    'btn_change' => '修改',
    'btn_save' => '保存',
    'btn_cancel' => '取消',
    'btn_back' => '返回',
    'btn_add' => '新增',
	'btn_edit' => '编辑',
    'btn_delete' => '删除',
	'btn_clear' => '清空',
    'btn_ok' => '确定',
    'btn_reg' => '注册',
    'btn_close' => '关闭',
	'btn_import' => '导入',
	'btn_export' => '导出',
    'btn_active' => '激活',
    'btn_adddept' => '新增部门',
    'btn_opdept' => '部门操作',
    'btn_editdept' => '编辑部门',
    'btn_deldept' => '删除部门',
    'btn_movedept' => '移动部门',
    'btn_adduser' => '新增人员',
    'btn_edituser' => '编辑人员',
    'btn_opuser' => '人员操作',
    'btn_setattr' => '设置属性',
    'btn_setdept' => '设置部门',
	'btn_setpos' => '设置铭牌',
    'btn_removeuser' => '从部门移出',
    'btn_deluser' => '删除人员',
    'btn_batchop' => '批量操作',
    'btn_impuser' => '导入用户',
    'btn_impdept' => '导入部门',
    'btn_impldap' => '导入域用户',
	'btn_imprtx' => '导入rtx用户',
    'btn_expuser' => '导出用户',
    'btn_expdept' => '导出部门',
    'btn_exp_alluser' => '导出全部用户',
    'btn_exp_seluser' => '导出选中用户',
	'btn_expire_clear' => '清除过期数据',
	'btn_imptxt' => '导入验证文件',
	'btn_doc_set' => '权限设置',

    'btn_setpy' => '重置拼音',
    'btn_setdeptpath' => '重置部门路径',
    'btn_setorder' => '重置排序',

    'btn_addmember' => '添加成员',
    'btn_setmember' => '设置成员',
	'btn_setkefumember' => '设置禁止通知客服',
	'btn_setkefumember1' => '设置提醒客服',
	'btn_setkefumember2' => '设置禁止显示客服',
	'btn_setkefumember3' => '设置显示人员',
	'btn_setkefumember4' => '设置发送客服',
	'btn_setpublic' => '设置公众号/小程序',
	'btn_setcdn' => '设置说明',

    'btn_reset_tag' => '重置标签',
    'btn_sel_dept' => '选择部门',
    'btn_addgrant' => '新增授权',
    'btn_addgroup' => '新增群组',
    'btn_delgroup' => '删除群组',
    'btn_settag' => '设置标签',
	'btn_search' => '查询',
	
    'txt_to' => '至',
    'txt_search' => '查找',
    'txt_index_notice' => '从小到大进行排列',
    'txt_img_tip' => '更改图片',
    'txt_order' => '从小到大进行排列',
    'txt_usersearch' => '输入帐号或姓名',
    'txt_loading' => '正在加载中...',


    'label_name' => '名称',
	'label_content' => '内容',
	'label_username' => '姓名',
    'label_account' => '帐号',
    'label_pwd' => '密码',
    'label_desc' => '描述',
	
	'alert_date' => '开始日期必须小于结束日期',
	'alert_delconfirm' => '你确定要删除吗?',
	
	

    //字段名称
    'field_id' => 'ID',
    'field_user' => '用户',
    'field_content' => '内容',
    'field_time' => '时间',
    'field_name' => '名称',
    'field_type' => '类型',
    'field_account' => '帐号',
    'field_username' => '姓名',
    'field_sex' => '性别',
    'field_email' => '邮箱',
    'field_mobile' => '手机',
    'field_dept' => '部门',
    'field_disabled' => '禁用',
    'field_grant' => '授权范围',
    'field_usercount' => '创建用户数',
    'field_creator' => '创建者',
    'field_diskspace' => '群共享空间',
    'field_usedspace' => '已用空间',
    'field_desc' => '描述',
    'field_tag' => '标签',
    'field_operate' => '操作',
	'field_icon' => '图标',
    'field_index' => '序号',
	'field_synctime' => '同步时间',
    'field_dt' => '创建时间',
    'field_job' => '职务',
    'field_other' => '其他',
	
	// admin/sync/push_edit.php 2015年4月10日  zwz
	'syncpush_lb_name' => '推送名称',
	'syncpush_lb_type' => '推送类型',
	'syncpush_lb_url' => '推送地址',

	
    
	//admin/sync/syncpush_list.php
	'syncpush_list_header' => '推送设置',
	'syncpush_list_btn_edit' => '新增推送',
	'syncpush_list_btn_delete' => '删除推送',
	'syncpush_list_ph_search' => '查找名称',
	'syncpush_list_col_id' => 'ID',
	'syncpush_list_col_name' => '推送名称',
	'syncpush_list_col_type' => '推送类型',
	'syncpush_list_col_disabled' => '禁用',
	'syncpush_list_col_creator' => '创建者',
	'syncpush_list_edit' => '编辑',
	'syncpush_list_delete' => '删除',
	
	'syncpush_org_header' => '推送组织设置',
	'syncpush_org_all' => '全部推送',
	'syncpush_org_increment' => '增量推送',
	
	
	//admin/sync/push_log.php
	'sycnpush_log_header' => '推送日志',
	'sycnpush_log_col_data' => '数据',
	'sycnpush_log_col_systemname' => '系统名称',
	'sycnpush_log_col_id' => 'ID',
	'sycnpush_log_col_datatype' => '数据类型',
	'sycnpush_log_col_optype' => '操作类型',
	'sycnpush_log_col_ipaddr' => 'IP',
	'sycnpush_log_col_dt_create' => '同步时间',
	'sycnpush_log_col_status' => '状态',
	'sycnpush_log_col_result' => '同步结果',
	'sycnpush_log_col_dt_feedback' => '反馈时间',
	'sycnpush_log_icon_error' => '失败',
	'sycnpush_log_icon_success' => '成功',
	'sycnpush_log_icon_warning' => '未反馈',
	'sycnpush_log_type_create' => '新增',
	'sycnpush_log_type_edit' => '更新',
	'sycnpush_log_type_delete' => '删除',
	'sycnpush_log_type_text' => '消息',
	'sycnpush_log_type_file' => '附件',
	'sycnpush_log_type_sync' => '同步',
	'sycnpush_log_type_dept' => '部门',
	'sycnpush_log_type_user' => '用户',
	'sycnpush_log_type_group' => '群组',
	'sycnpush_log_type_msg' => '消息',
	
	//admin/hl/hl_org.php
	'hlorg_header' => '单位互联 / 组织管理',
	'hlorg_btn_create_dir' => '创建目录',
	'hlorg_btn_delete_dir' => '删除目录',
	'hlorg_col_name' => '名称',
	'hlorg_col_descibe' => '描述',
	'hlorg_col_address' => '端口地址',
	'hlorg_col_type' => '端口类型',
	'hlorg_col_status' => '状态',
	
	
    // admin/account/login.php
    'browser_notice1' => '建议使用IE9或FireFox、Chrome浏览器，获得更好的体验...',
    'browser_notice2' => '你的IE版本过低，请升级IE版本，或用Chrome/FireFox浏览器',


    'login_error' => '帐号或密码错误',
    'login_error1' => '您今天的错误次数超过%1次，已被限制登录！',

    'login_title' => '登录',
    'login_notice' => '默认管理员帐号：admin 密码为空，请在登录后修改管理员密码',
    'login_lb_account' => '帐号',
    'login_ph_account' => '请输入帐号',
    'login_required_account' => '请输入帐号',
    'login_lb_password' => '密码',
    'login_ph_password' => '请输入密码',
    'login_required_password' => '请输入密码',

    'login_lb_verifycode' => '验证码',
    'login_ph_verifycode' => '验证码',
    'login_required_verifycode' => '请输入验证码',

    // admin/account/setpassword.php
    'pwd_title' => '修改密码',
    'pwd_notice' => '密码修改成功，重新登录生效。',
    'pwd_lb_old' => '旧密码',
    'pwd_lb_new' => '新密码',
    'pwd_lb_repeat' => '确认密码',

    'doc_private_title' => '文档管理 /配置信息',
    'doc_private_notice' => '修改成功',
    'doc_private_lb_path' => '存储路径',
    'doc_private_lb_switch' => '允许保存个人文档',

    // admin/doc/doc_log.php
    'doc_log_title' => '文档管理 /文档日志',

    // admin/doc/doc_tree.php
    'doc_public_title' => '文档管理 /文档存储',
    'doc_btn_createroot' => '新增根目录',
    'doc_btn_createfolder' => '新增目录',
    'doc_btn_editfolder' => '修改目录',
    'doc_btn_delfolder' => '删除目录',
    'doc_btn_addpower' => '添加权限',
    'doc_btn_adduser' => '添加用户',
    'doc_btn_addrole' => '添加角色',
    'doc_btn_delpower' => '删除权限',
	'doc_btn_batch' => '批量导入',
	'doc_btn_clean' => '清理文件夹',
    'doc_tree_title' => '存储目录',
    'doc_path_title' => '目录属性',
    'doc_lb_foldername' => '目录名称',
    'doc_ph_foldername' => '目录名称',
    'doc_lb_folderpath' => '目录路径',
    'doc_ph_folderpath' => '目录路径',

    // 文档权限类型
    'doc_power_view' => '显示',
    'doc_power_edit' => '查看',
    'doc_power_edit1' => '编辑',
    'doc_power_manage' => '移动',
    'doc_power_download' => '下载',
    'doc_power_create' => '创建',
    'doc_power_delete' => '删除',
    'doc_power_rename' => '重命名',
    'doc_power_sendfile' => '分享',
	'doc_power_permission' => '权限',
    'doc_power_finalized' => '定版',

    // 文档日志类型
    'type_downloadfile' => '下载文件',
    'type_editfile' => '编辑文件',
    'type_newfile' => '创建文件',
    'type_removefile' => '移动文件',
    'type_viewfile' => '查看文件',
    'type_deletefile' => '删除文件',
    'type_sharefile' => '共享文件',
    'type_login' => '登录',
	
    // 版权信息
    'about_version' => '版本号',
    'about_publishdate' => '发布日期',
    'about_website' => '产品网址',
    'about_copyright' => '版权所有2015 %1. 保留所有权利。',

    // 软件注册
    'reg_machinecode' => '机器码',
    'reg_licensenumber' => '许可数',
    'reg_usercount' => '总用户数',
    'reg_expiredate' => '到期时间',
    'reg_lb_active' => '请输入激活码',
	
	//管理端设置
	'webserver_config_title' => '后台设置',
	'webserver_config_antserver' => 'WebServer消息服务器配置',
	'webserver_config_common' => 'WebServer常用配置',
	'webserver_config_added' => 'WebServer增值配置',
	'webserver_lb_ant_server' => '消息服务器IP地址',
	'webserver_lb_ant_server_tip' => '请用真实IP，如192.168.0.1,代理服务器请用代理地址',
	'webserver_lb_ant_console_tip' => '请谨慎修改,修改后请搭建一个站点指向数据目录并修改视频播放地址,否则云盘视频无法网页播放!',
	'webserver_lb_ant_port' => '端口',
	'webserver_lb_ant_datadir' => '数据目录',
	'webserver_lb_ant_consoledir' => '控制台目录',
	'webserver_lb_ant_video' => '视频播放地址',
	'webserver_lb_ant_video_tip' => '修改数据目录后,并搭建一个站点指向数据目录后才需要填写!例如http://192.168.1.4:94',
	'webserver_lb_export_field' => '数据导入导出格式',
	'webserver_lb_push_toket' => 'WebSerivce令牌',
	'webserver_lb_api_return_type' => 'WebSerivce 返回内容格式',
	'webserver_lb_sms_url' => '短信接口地址',
	'webserver_lb_sms_sample' => '例:http://192.168.0.1/sms_send.html?mobile={mobile}&content={content},多个手机号用,逗号分隔,返回的内容需JSON格式,如{"status":1} 或{"status":0,"msg":"error"}',
	'webserver_lb_smtp_info' => '邮件发送信息',
	'webserver_lb_smtp_server' => 'SMTP服务器地址：',
	'webserver_lb_smtp_port' => 'SMTP服务器端口：',
	'webserver_lb_smtp_account' => '邮箱帐号：',
	'webserver_lb_smtp_password' => '邮箱密码：',
	'webserver_lb_back_onlineminute' => 'API 登录心跳时长(超时设为退出)',
	'webserver_lb_log_level'=>'WebServer日志级别',
	'webserver_lb_log_level_close'=>'关闭',
	'webserver_lb_log_level_debug'=>'debug',
	'webserver_lb_log_level_info'=>'info',
	'webserver_lb_log_level_error'=>'error',
	'webserver_lb_log_level_open'=>'开启',
	'webserver_lb_push_sms' => '消息短信推送',
	'webserver_lb_push_email' => '消息邮件推送',
	'webserver_lb_push_sms_desc' => '当手机没有收到推送消息,系统会发短信提醒用户打开app查看消息',
	'webserver_lb_push_email_desc' => '当手机没有收到推送消息,系统会发邮件提醒用户打开app查看消息',
		
	
    // 单位互联
    'hl_config_title' => '单位互联<small>（带<i class="warnning">*</i>号为必填项 ）</small>',
    'hl_config_legend1' => '互联信息',
    'hl_config_legend2' => '中心服务器(必选)',
    'hl_config_legend3' => '文件服务器(可选)',
    'hl_config_legend4' => '音视频服务器(可选)',
    'hl_lb_unitid' => '单位ID',
    'hl_lb_connectpwd' => '连接密码',
    'hl_ph_centerport' => '默认 8899',
    'hl_lb_serverip' => '服务器IP',
    'hl_lb_serverport' => '服务器端口',


    // 组织人员管理
    'org_title' => '组织管理',
    'org_ph_search' => '输入帐号或姓名',
    'org_tree_title' => '部门管理',
    'org_user_title' => '人员列表',
    'dept_lb_path' => '上级部门',
    'dept_lb_name' => '部门名称',
    'dept_ph_name' => '部门名称',
    'dept_lb_desc' => '部门描述',
    'dept_ph_desc' => '部门描述',
    'dept_lb_index' => '排序号',
    'dept_ph_index' => '1000',
	'dept_lb_display' => '人员显示',
	'dept_col_style0' => '状态优先',
	'dept_col_style1' => '忽略状态',

    'dept_lb_reset' => '删除以前的部门',

    //分级管理
    'grant_lb_user' => '授权人员',
    'grant_lb_tree' => '授权部门',
    'grant_lb_usercount' => '人员数量',
    'grant_notice' => '0 表示创建用户数不限制',
    'grant_title' => '授权管理',
	'grant_exist' => '此部门已经授权过',
    'grant_beyond' => '超出授权人数',

    //群组管理
    'group_tab_base' => '属性',
    'group_tab_member' => '成员',
    'group_tab_board' => '群公告' ,
    'group_tab_tag' => '标签',
    'group_lb_name' => '名称',
    'group_ph_name' => '',
    'group_lb_diskspace' => '群空间大小',
    'group_ph_diskspace' => '',
    'group_lb_index' => '排序号',
    'group_ph_index' => '1000',
    'group_lb_desc' => '描述',
    'group_ph_desc' => '',
    'group_tree_title' => '选择成员',
    'group_title' => '群组管理',
    'group_ph_search' => '查找群组',
    'group_ph_portrait' => '群头像',
    'group_ph_Banned' => '全员禁言',
    //导入部门
    'imp_lb_filepath' => '导入文件',
    'imp_dept_warning' => '请设置导入文件为UTF-8编码,以确保中文不乱码',
    'imp_dept_link_path' => '导入【路径】格式',
    'imp_dept_link_table' => '导入【表格】格式',

    //导入用户
    'imp_user_warning' => '请使用UTF-8格式,以确保中文不乱码',
    'imp_user_switch' => '快速导入',
    'imp_user_link' => '文本导入格式',
	
	'imp_txt_warning' => '请从微信公众号/小程序下载验证文件',
    //导入域用户
    'ldap_lb_domain' => '域控服务器',
    'ldap_ph_domain' => '域服务器域名',
    'ldap_lb_admin' => '管理员帐号',
    'ldap_ph_admin' => '管理员帐号',
    'ldap_lb_pwd' => '密码',

    //职位铭牌
    'pos_lb_icon' => '图标',
    'pos_lb_preview' => '预览',
    'pos_lb_index' => '序号',
    'pos_lb_name' => '名称',
    'pos_lb_desc' => '描述',
    'pos_title' => '铭牌管理',
    'pos_ph_search' => '查找铭牌',

    //角色
    'role_tab_base' => '属性',
    'role_tab_member' => '成员',
    'role_tab_power' => '基本权限',
    'role_tab_org' => '组织权限',
    'role_tab_ip' => '登录设置',
    'role_tab_file' => '文件管理',

    'role_tree_title' => '选择成员',
    'role_ph_search' => '输入帐号或姓名',

    'role_power_warning' => '当修改角色权限后，员工所拥有的角色权限也随之改变，您无需修改员工所拥有的角色。',
	'role_power_warning1' => '拓展名限制为*表示上传或发送文件类型无限制，输入格式:rar;doc;xls',
	'role_power_chk_smscount' => '发送短信&nbsp;&nbsp;最多限制',
	'role_power_smscount' => '条/月',
	'role_power_chk_ptpsize' => '上传个人文档/共享文件',
	'role_power_ptpsize' => '上传最大限制',
	'role_power_ptptype' => '上传拓展名限制：',
	'role_power_download_ptpsize' => '下载个人文档/共享文件',
	'role_power_chk_clotsize' => '上传群组文件',
	'role_power_download_clotsize' => '下载群组文件',
	'role_power_chk_userssize' => '发送文件',
	'role_power_userssize' => '发送最大限制',
	'role_power_userstype' => '发送拓展名限制：',
	'role_power_download_userssize' => '接收文件',
	'role_power_download_networks' => '禁止在外网和手机下载所有文件',
	'role_power_other_department' => '禁止与其他部门聊天',
	'role_power_this_department' => '禁止与本部门聊天',
	'role_power_unauthorized_control' => '无权限控制(可以看到所有部门、账号)',
	'role_power_switch0_department' => '禁止看到以下部门及其所属账号',
	'role_power_switch1_department' => '只允许看到以下部门及其所属账号',
	'role_power_remote_login' => '远程登陆',
	'role_power_phone_login' => '手机登陆',
	'role_power_restrictip' => '限制IP',
	'role_power_restrictmac' => '限制MAC',
	'role_power_password' => '修改密码',
    'role_power_sendboard' => '发布公告',
    'role_power_delboard' => '允许删除公告',
    'role_power_attachsize' => '附件大小限制',
    'role_power_broadcast' => '群发个数限制',
    'role_power_setattr' => '修改个人设置',
    'role_power_setjob' => '禁止显示职务',
    'role_power_recfile' => '禁止用户接收附件',
    'role_power_video' => '语音视频',
    'role_power_audio' => '禁止语音通话',
    'role_power_signout' => '禁止退出群组',
    'role_power_logout' => '禁止客户端注销',
    'role_power_remote' => '远程屏幕和远程控制',
    'role_power_ring' => '禁止客户端声音提示',
    'role_power_splashscreen' => '禁止发送闪屏',
    'role_power_signmsg' => '禁止发送签收消息',
    'role_power_showsignature' => '禁止显示个人签名',
    'role_power_changephoto' => '禁止客户端修改头像',
    'role_power_screenshot' => '禁止截屏',
    'role_power_set' => '修改高级设置',
    'role_power_setaway' => '禁止隐身',
    'role_power_sendtopmsg' => '禁止发送置顶消息',
    'role_power_privatechat' => '禁止密聊功能',
    'role_power_sysview' => '显示组织架构',
    'role_power_group_create' => '创建群组',
    'role_lb_ipaddr' => '允许的IP地址',
    'role_lb_loginpower' => '登陆权限设置',
    'role_lb_switch0' => '禁止',
    'role_lb_switch1' => '允许',
	
	//admin/hs/role_list.php
    'role_list_title' => '角色管理',
    'role_list_btn_add' => '新增角色',
    'role_list_btn_member' => '设置人员',
	'role_list_btn_delete' => '删除角色',
	'role_list_btn_set' => '一键设置角色',
	'role_list_ph_search' => '查找角色',
	'role_list_col_name' => '名称',
	'role_list_col_description' => '描述',
    'role_list_col_creator_name' => '创建者',
	'role_list_col_disabled' => '禁用',
	'role_list_col_member' => '人员',
	'role_list_col_change' => '修改',
	'role_list_col_detele' => '删除',
	'role_list_col_clone' => '克隆',
	'role_list_btn_role' => '设置角色',
	'role_list_btn_batches' => '批量设置角色',
	//admin/hs/role_picker.php
	'role_picker_col_name' => '名称',
	'role_picker_col_description' => '描述',
	'role_picker_default_role' => '新增用户默认角色',
	
	//admin/hs/tag_edit.php
	'tag_lb_name' => '标签名称',
	'tag_ph_name' => '标签名称',
	
	//admin/hs/tag_list.php
	'tag_list_title' => '标签管理',
	'tag_list_btn_add' => '新增分类',
	'tag_list_type_edit' => '编辑',
    'tag_list_type_delete' => '删除',
    'tag_list_ph_name' => '添加标签',
    'tag_list_col_user' => '查看人员',
	'tag_list_col_group' => '查看群组',
	'tag_list_col_edit' => '修改标签',
	'tag_list_col_delete' => '删除标签',
	
	//admin/hs/tag_picker.php
	'tag_picker_checkbox_reset' => '重置标签',
	'tag_picker_alert' => '请选择要设置的对象',
	
	//admin/hs/tag_type_edit.php
	'tag_type_lb_name' => '类型名称',
	'tag_type_ph_name' => '类型名称',
	
	//admin/hs/user_attr.php
	'user_attr_allowedcard' => '允许网卡地址(多条以,逗号分隔)',
	'user_attr_allowedip' => '允许IP地址(多条以,逗号分隔)',
	
	//admin/hs/user_edit.php
	'user_edit_tab_base' => '基本信息',
	'user_edit_tab_work' => '业务信息',
	'user_edit_tab_self' => '个人信息',
	'user_edit_tab_login' => '登录信息',
	'user_edit_tab_power' => '角色与权限',
	'user_edit_account' => '帐号',
	'user_edit_username' => '姓名',
	'user_edit_psw' => '密码',
	'user_edit_show_password' => '显示密码',
	'user_edit_sequence' => '排序号',
    'user_expiration_time' => '有效期',
    'user_expiration_tip' => '设置当前部门及下属所有部门人员的过期时间',
    'user_expiration_set' => '长期有效',
	'user_edit_order' => '排序号越大，越排前面',
	'user_edit_checkbox_admin' => '管理员',
	'user_edit_checkbox_disabled' => '禁用帐号',
	'user_edit_lb_jobtitle' => '职务',
	'user_edit_lb_nameplate' => '铭牌',
	'user_edit_lb_phone' => '固话',
	'user_edit_lbl_shortnum' => '短号',
	'user_edit_lb_mobile' => '手机',
	'user_edit_lb_fax' => '传真',
	'user_edit_lb_email' => '邮箱',
	'user_edit_lb_address' => '地址',
	'user_edit_lb_postal' => '邮编',
	'user_edit_lb_gender' => '性别',
	'user_edit_lb_gender1' => '男',
	'user_edit_lb_gender2' => '女',
	'user_edit_lb_age' => '年龄',
	'user_edit_lb_birthday' => '生日',
	'user_edit_lb_province' => '省份',
	'user_edit_lb_city' => '城市',
	'user_edit_lb_street' => '街道',
	'user_edit_lb_website' => '网页',
	'user_edit_lb_description' => '个人说明',
	'user_edit_lb_school' => '毕业学校',
	'user_edit_lb_note' => '备注',
	'user_edit_col_mac' => '允许网卡地址(多条以,逗号分隔)',
	'user_edit_col_ip' => '允许IP地址(多条以,逗号分隔,格式192.168.1.1或192.168.1.1-192.168.1.3)',
	'user_edit_power_roles' => '用户所拥有的角色',
	'user_edit_power_ou' => '允许访问的组织',
	
	
   //admin/hs/user_list.php
   'user_list_page_title' => '人员管理',
   'user_list_btn_add' => '新增人员',
   'user_list_btn_batch' => '批量操作',
   'user_list_dropdown_properties' => '设置属性',
   'user_list_dropdown_dept' => '设置部门',
   'user_list_dropdown_role' => '设置角色',
   'user_list_dropdown_pos' => '设置铭牌' ,//
   'user_list_dropdown_label' => '设置标签',
   'user_list_dropdown_delete' => '删除',
   'user_list_ph_search' => '查找人员帐号/姓名',
   'user_list_col_loginname' => '帐号',
   'user_list_col_name' => '姓名',
   'user_list_col_sex' => '性别',
   'user_list_col_email' => 'Email',
   'user_list_col_mobile' => '电话',
   'user_list_col_deptinfo' => '部门',
   'user_list_col_job' => '职务',
   'user_list_col_other' => '其他',
   'user_list_col_expiretime' => '到期时间',
   'user_list_col_issuper' => '管理员',
   'user_list_col_disabled' => '禁用',
   'user_list_col_label' => '禁用',
   'user_list_alert' => 'admin帐号不允许此操作',
   
   
  //admin/hs/user_picker.php
   'user_picker_title' => '选择成员',
   'user_picker_ph_userkey' => '输入帐号或姓名',
   'user_picker_btn_add' => '添加成员',
   'user_picker_col_name' => '姓名',
   'user_picker_col_account' => '帐号',
   'user_picker_checkbox_reset' => '重置成员',
   'user_picker_col_title' => '名称',
   'user_picker_col_type' => '类型',
   
   //admin/include/bioace_lis.php
   'bioace_btn_add' => '新增权限',
   'bioace_btn_delete' => '删除权限',
   'bioace_btn_change' => '修改权限',
   'bioace_col_name' => '名称',
   'bioace_col_type' => '类型',
   'bioace_col_permission' => '权限',
   'bioace_col_delete' => '删除',
   
   
   //admin/include/header.php
   'header_hello' => '您好, ',
   'header_home' => '首页',
   'header_download' => '下载专区',
   'header_changepsw' => '修改密码',
   'header_exit' => '退出',
   'header_help' => '帮助',
   'header_dropdown_register' => '注册',
   'header_dropdown_about' => '关于',
   'header_nopermission' => '没有权限',
   'header_nopermission_operate' => '没有权限操作此页面',
   'header_lang' => '语言',
   'header_cn' => '简体中文',
   'header_hk' => '繁体中文',
   'header_en' => '英语',
   
   //admin/include/header0.php
   'header0_help' => '帮助', //' '
   'header0_dropdown_register' => '注册',
   'header0_dropdown_about' => '关于',
   
   
   //admin/include/index.php
   'index_companyinfo' => '单位信息: ',
   'index_btn_set' => '设置',
   'index_commonuse' => '常用操作',
   'index_user' => '用户管理',
   'index_user_des' => '添加，删除，设置，导入/导出部门及人员信息',
   'index_upgrade' => '升级管理', //'升级管理'
   'index_upgrade_des' => '升级PC、Andriod客户端',
   'index_server' => '服务控制',
   'index_server_des' => '启动，停止，重启各类即时通讯服务',
   'index_service' => '在线客服',
   'index_service_des' => '客户可以通过网页与我们的员工交流沟通',
   'index_application' => '应用中心',
   'index_application_des' => '企业第三方管理系统如OA、CRM以及其它业务系统',
   'index_map' => '功能地图 ',
   
   //admin/lv_manager/chat_list.php
   'lvchat_private_title' => '在线客服 /配置信息',
   
   'transfer_list_title' => '转接记录',
   'transfer_list_original' => '原客服',
   'transfer_list_now' => '现客服',
   'transfer_list_userid' => '用户ID',
   'transfer_list_type' => '类型',
   'transfer_list_date' => '时间',
   'transfer_list_type1' => '转接',
   'transfer_list_type2' => '抢接',
   'transfer_list_type3' => '自动转接',
   
   'lvchat_list_title' => '会话管理',
   'lvchat_list_drop_status' => '全部',
   'lvchat_list_drop_status0' => '等待中',
   'lvchat_list_drop_status1' => '交谈中',
   'lvchat_list_drop_status2' => '结束',
   'lvchat_list_field_account' => '客服帐号',
   'lvchat_list_field_name' => '访客姓名',
   'lvchat_list_field_userid' => '用户ID',
   'lvchat_list_field_chatid' => '会话ID',
   'lvchat_list_field_content' => '内容',
   'lvchat_list_txt_keywords' => '关键字',
   'lvchat_list_txt_date' => '会话日期',
   'lvchat_list_chatid' => '会话ID',
   'lvchat_list_account' => '客服帐号',
   'lvchat_list_userid' => '用户ID',
   'lvchat_list_username' => '姓名',
   'lvchat_list_ip' => 'IP',
   'lvchat_list_area' => '地区 ',
   'lvchat_list_intime' => '进入时间',
   'lvchat_list_connecttime' => '接通时间',
   'lvchat_list_outtime' => '结束时间',
   'lvchat_list_status' => '状态',
   'lvchat_list_attach' => '附件',
   'lvchat_list_record' => '记录',
   'lvchat_list_allrecord' => '全部记录',
   'lvchat_list_blackip' => '黑名单',
   'lvchat_list_return_case0' => '等待中',
   'lvchat_list_return_case1' => '交谈中',
   'lvchat_list_return_case2' => '结束',
   'lvchat_list_groupid' => '请选择入口',
   'lvchat_list_groupname' => '入口',
   'lvchat_list_themeid' => '请选择主题',
   'lvchat_list_themename' => '主题',
   'lvchat_list_chatlevel' => '请选择价值',
   'lvchat_list_chatlevelname' => '级别',
   'lvchat_list_chatlevel0' => '未评估',
   'lvchat_list_chatlevel1' => '无价值',
   'lvchat_list_chatlevel2' => '有价值',
   'lvchat_list_isenable' => '请选择效果',
   'lvchat_list_isenable1' => '无效会话',
   'lvchat_list_isenable2' => '有效会话',
   'lvchat_list_no' => '全部',
   'lvchat_list_not' => '非入口会话',
   'lvchat_list_drp_type0' => '通话量',
   'lvchat_list_drp_type2' => '会话价值',
   'lvchat_list_drp_type1' => '会话主题',
   'lvchat_list_uname' => '名称',
   'lvchat_list_groupcount' => '总接待量',
   'lvchat_list_percent' => '占比',
   'lvchat_list_detail' => '详情',
   'lvchat_list_first_inouttime' => '首次',
   'lvchat_list_inouttime' => '平均',
   'lvchat_list_rate' => '评分',
   'lvchat_list_first_inouttimes' => '首次回复时间',
   'lvchat_list_inouttimes' => '平均回复时间',
   'lvchat_list_chat_times' => '聊天时间',
   'lvchat_list_rates' => '评分',
   'lvchat_list_enable_inoutnum' => '已回复会话量',
    'chart_rate_unit0' => '未评', 
	'chart_rate_unit1' => '恶劣', 
	'chart_rate_unit2' => '较差', 
	'chart_rate_unit3' => '一般', 
	'chart_rate_unit4' => '较好', 
	'chart_rate_unit5' => '满意',
   
   //admin/lv_manager/chater_edit.php
   'chater_edit_photo' => '更改照片',
   'chater_edit_lb_account' => '帐号',
   'chater_edit_ph_account' => '帐号',
   'chater_edit_lb_name' => '姓名',
   'chater_edit_ph_name' => '姓名',
   'chater_edit_lb_dept' => '部门',
   'chater_edit_ph_dept' => '部门',
   'chater_edit_lb_job' => '职位',
   'chater_edit_ph_job' => '职位',
   'chater_edit_lb_tel' => '座机',
   'chater_edit_ph_tel' => '座机',
   'chater_edit_lb_mobile' => '手机',
   'chater_edit_ph_mobile' => '手机',
   'chater_edit_lb_reception' => '最大接待量',
   'chater_edit_ph_reception' => '最大接待量',
   'chater_edit_lb_email' => '邮箱',
   'chater_edit_ph_email' => '邮箱',
   'chater_invite_lb_welcome' => '邀请框欢迎语',
   'chater_invite_ph_welcome' => '邀请框欢迎语',
   'chater_edit_lb_welcome' => '欢迎语',
   'chater_edit_ph_welcome' => '欢迎语',
   'chater_edit_lb_cdn_title' => '请输入CDN加速域名',
   'chater_edit_lb_adlink' => '广告url',
   'chater_edit_lb_adlink_alert' => '请输入广告链接url',
   'chater_edit_lb_ad' => '广告',
   'chater_edit_lb_ad_img' => '广告图片',
   'chater_edit_lb_ad_title' => '更改广告',
   'chater_delete_lb_ad_title' => '清除广告',
   'chater_edit_lb_status' => '状态',
   'chater_edit_option_status1' => '正常',
   'chater_edit_option_status0' => '关闭',
   'chater_edit_lb_order' => '排序',
   'chater_edit_ph_order' => '排序',
   'chater_edit_alert' => '用户不存在!',
   'chater_edit_error_account' => '请输入帐号',
   'chater_edit_error_name' => '请输入姓名',
   'chater_edit_error_ord' => '请输入排序号',
   'chater_edit_end_conversation' => '对话结束',
   'chater_edit_end_conversation0' => '不设置',
   'chater_edit_end_conversation1' => '自动置后',
   'chater_edit_end_conversation2' => '自动移除',
   'chater_edit_lb_endsession' => '结束会话后',
   'chater_edit_lb_endsession_alert' => '从排队列表中接入新会话',
   'chater_edit_default' => '默认',
   'chater_edit_lb_match' => '匹配方式',
   'chater_edit_option_match0' => '模糊匹配',
   'chater_edit_option_match1' => '精准匹配',
   'chater_edit_lb_receives_reminders' => '客服接收提醒',
   'chater_edit_lb_receives_reminders_alert' => '客服可收到完整会话，不勾选此项，可智能过滤掉大流量的重复咨询',
   'chater_edit_lb_top_questions' => '热门问题',
   'chater_edit_lb_top_questions_alert' => '访客端显示，点击热门问题，自动应答',
   'chater_edit_defaulttargetlanguage' => '手动翻译为',
   'chater_edit_usertargetlanguage' => '访客消息自动翻译为',
   'chater_edit_chatertargetlanguage' => '客服消息自动翻译为',
   'chater_edit_language_zh' => '简体中文',
   'chater_edit_language_en' => '英语',
   'chater_edit_language_yue' => '粤语',
   'chater_edit_language_wyw' => '文言文',
   'chater_edit_language_jp' => '日语',
   'chater_edit_language_kor' => '韩语',
   'chater_edit_language_fra' => '法语',
   'chater_edit_language_spa' => '西班牙语',
   'chater_edit_language_th' => '泰语',
   'chater_edit_language_ara' => '阿拉伯语',
   'chater_edit_language_ru' => '俄语',
   'chater_edit_language_pt' => '葡萄牙语',
   'chater_edit_language_de' => '德语',
   'chater_edit_language_it' => '意大利语',
   'chater_edit_language_el' => '希腊语',
   'chater_edit_language_nl' => '荷兰语',
   'chater_edit_language_pl' => '波兰语',
   'chater_edit_language_bul' => '保加利亚语',
   'chater_edit_language_est' => '爱沙尼亚语',
   'chater_edit_language_dan' => '丹麦语',
   'chater_edit_language_fin' => '芬兰语',
   'chater_edit_language_cs' => '捷克语',
   'chater_edit_language_rom' => '罗马尼亚语',
   'chater_edit_language_slo' => '斯洛文尼亚语',
   'chater_edit_language_swe' => '瑞典语',
   'chater_edit_language_hu' => '匈牙利语',
   'chater_edit_language_cht' => '繁体中文',
   'chater_edit_language_vie' => '越南语',
   
   'user_edit_lb_name' => '姓名',
   'user_edit_ph_name' => '姓名',
   'user_edit_lb_wechat' => '微信',
   'user_edit_ph_wechat' => '微信',
   'user_edit_lb_qq' => 'qq',
   'user_edit_ph_qq' => 'qq',
   'user_edit_lb_remarks' => '备注',
   'user_edit_ph_remarks' => '备注',
   'user_edit_lb_mobile' => '手机',
   'user_edit_ph_mobile' => '手机',
   'user_edit_lb_chater' => '优先接待客服',
   'user_edit_ph_chater' => '请输入客服账号',
   'user_edit_lb_email' => '邮箱',
   'user_edit_ph_email' => '邮箱',
   'user_edit_alert' => '客服不存在或被禁用!',
   
   //admin/lv_manager/chater_list.php
	'chater_list_title' => '客服列表',
	'chater_list_add' => '新增客服',
	'chater_list_deleteoperate' => '删除客服',
	'chater_list_preview' => '预览',
	'chater_list_generate' => '客服代码',
	'chater_list_search' => '查找人员帐号/姓名',
	'chater_list_account' => '帐号',
	'chater_list_name' => '姓名',
	'chater_list_dept' => '部门',
	'chater_list_job' => '职位',
	'chater_list_tel' => '座机',
	'chater_list_mobile' => '手机',
	'chater_list_email' => '邮箱',
	'chater_list_reception' => '最大接待量',
	'chater_list_welcome' => '欢迎语',
	'chater_list_top' => '热门问题',
	'chater_list_status' => '状态',
	'chater_list_order' => '排序',
	'chater_list_link' => '链接',
	'chater_list_js' => '代码',
	'chater_list_qrcode' => '二维码',
	'chater_list_dialog' => '会话',
	'chater_list_rate' => '评价',
	'chater_list_edit' => '编辑',
	'chater_list_delete' => '删除',
	'chater_list_up' => '上移',
	'chater_list_down' => '下移',
	'chater_list_talk' => '交谈',
	'chater_list_attributes' => '属性',
	'chater_list_generate1' => '移动端客服代码',
	'chater_list_member' => '成员',
	'chater_list_server' => '服务器地址',
	'chater_list_alert_enteripaddress' => '当前服务器在外网上的URL地址,可以是IP或域名',
	'chater_list_copy' => '复制',
	'chater_list_mode' => '模式',
	'chater_list_mode_alert1' => '网站模式(所有客服都是公司员工)',
	'chater_list_mode_alert2' => '商城多用户模式(每个客服对应一个店铺)',
	'chater_list_distribution' => '客服分配',
	'chater_list_distribution_alert1' => '智能模式',
	'chater_list_distribution_alert2' => '顺序模式',
	'chater_list_guestsession' => '访客会话',
	'chater_list_guestsession_alert1' => '直接会话',
	'chater_list_guestsession_alert2' => '排队会话',
	'chater_list_switchtype' => '自动邀请',
	'chater_list_switchtype_alert1' => '邀请会话在顾客访问网站',
	'chater_list_switchtype_alert2' => '秒后发出',
	'chater_list_websitetype' => '访客提醒',
	'chater_list_websitetype_alert1' => '访客提醒',
	'chater_list_websitetype_alert2' => '网站访客进入通知客服',
	'chater_list_websitetype_alert3' => '访客打开对话框提醒客服',
	'chater_list_websitetype_alert4' => '网站访客进入自动与客服会话',
	'chater_list_websitetype_alert5' => '不设置',
	'chater_list_switchweChat' => '公众号/小程序',
	'chater_list_switchweChat_alert1' => '微信公众号/小程序',
	'chater_list_switchweChat_alert2' => '通过微信公众号/小程序推送消息',
	'chater_list_switchBack' => '返回按钮',
	'chater_list_switchBack_alert1' => '访客手机端不显示返回按钮',
	'chater_list_switchBack_alert2' => '设置禁止显示客服',
	'chater_list_sendWelcome' => '发送欢迎语',
	'chater_list_sendWelcome_alert1' => '访客每次打开聊天页面发送客服欢迎语',
	'chater_list_sendWelcome_alert2' => '设置发送客服',
	'chater_list_switchDomainType' => '切换跳转域名',
	'chater_list_switchDomainType_alert1' => '自动切换跳转域名(当访客端打不开页面)',
	'chater_list_rejecttype' => '评价',
	'chater_list_rejecttype_alert1' => '评价',
	'chater_list_rejecttype_alert2' => '聊天结束或关闭强制评价',
	'chater_list_weixintype' => '入口限制',
	'chater_list_weixintype_alert1' => '评价',
	'chater_list_weixintype_alert2' => '只允许从微信打开',
	'chater_list_cdntype' => 'CDN加速',
	'chater_list_cdntype_alert1' => '评价',
	'chater_list_cdntype_alert2' => '手机访客端js/css静态资源CDN加速,解决第一次打开慢的问题',
	'chater_list_heartbeat' => '心跳包',
	'chater_list_heartbeat_alert1' => '倍时长(倍数越大,服务器负载越小,已读/未读状态获取时间越长)',
	'chater_list_showhistory' => '聊天记录',
	'chater_list_showhistory_alert1' => '访客端不显示历史聊天记录',
	'chater_list_voicevideo' => '语音视频',
	'chater_list_voicevideo_alert1' => '访客端禁止语音/视频电话',
	'chater_list_history_alert1' => '清除',
	'chater_list_history_alert2' => '小时前的聊天记录',
	'chater_list_reminder' => '超时提醒',
	'chater_list_reminder_alert1' => '接收到访客信息后,超过',
	'chater_list_reminder_alert2' => '秒未回复,头像红框显示',
	'chater_list_transfer' => '超时转接',
	'chater_list_transfer_alert1' => '接收到访客信息后,超过',
	'chater_list_transfer_alert2' => '秒未回复,自动转接到其他客服',
	'chater_list_oldvisitor' => '熟客有效期',
	'chater_list_oldvisitor_alert1' => '在',
	'chater_list_oldvisitor_alert2' => '秒内熟客接入会话寻找原客服聊(限定时间之后接入会话寻找其他客服聊)',
	'chater_list_server_configuration' => '服务器配置',
	'chater_list_weChat_official_account_configuration' => '微信公众号/小程序配置',
	'chater_list_advertising_configuration' => '广告配置',
	'chater_list_domain' => '网页授权域名',
	'chater_list_appid' => '开发者ID(AppID)',
	'chater_list_sercet' => '开发者密码(AppSecret)',
	'chater_list_token' => '令牌(Token)',
	'chater_list_moban_id' => '模版消息ID',
	'chater_list_subscribe_id' => '订阅通知模版ID',
	'chater_list_moban_message1' => '模版消息',
	'chater_list_moban_message2' => '一次性订阅消息',
	'chater_list_subscribe' => '订阅消息',
	'chater_list_subscribe1' => '一次性订阅消息',
	'chater_list_subscribe2' => '订阅通知',
	'chater_list_subscribe3' => '不推送订阅通知',
	'chater_list_customer_service_link' => '被动客服链接',
	'chater_list_wechat_customer_service_link' => '主动客服链接',
	'chater_list_link1' => '例如:http://g.rtcim.com/vendor/wx/?act=openid&redirect_uri=http%3A//g.rtcim.com%3A98/kefu.html,redirect_uri参数为escape加密过的客服链接。',
	'chater_list_domain_alert' => '请输入网页授权域名',
	'chater_list_appid_alert' => '请输入开发者ID(AppID)',
	'chater_list_sercet_alert' => '请输入开发者密码(AppSecret)',
	'chater_list_token_alert' => '请输入令牌(Token)',
	'chater_list_moban_id_alert' => '请输入模版消息ID',
	'chater_list_subscribe1_id_alert' => '请输入一次性订阅消息模版ID',
	'chater_list_subscribe2_id_alert' => '请输入订阅通知模版ID',
	'chater_list_subscribe4_id_alert' => '请输入订阅消息模版ID',
	'chater_list_customer_service_link_alert' => '请输入收到的模版消息/订阅通知跳转客服链接',
	'chater_list_wechat_customer_service_link_alert' => '请输入公众号/小程序自定义菜单/订阅通知客服链接',
	'chater_list_isminiprogram' => '小程序',
	'chater_list_account' => '公众号',

	'chater_list_chatgpt_configuration' => '机器人设置',
	'chater_list_chatgpt_reception' => '默认接待',
	'chater_list_chatgpt_reception1' => '智能客服',
	'chater_list_chatgpt_reception2' => '人工客服',
	'chater_list_chatgpt_reception3' => '请选择',
	'chater_list_chatgpt_transfer' => '转人工/机器人',
	'chater_list_chatgpt_transfer_desc' => '接待过程中,访客侧显示转人工/机器人按钮',
	'chater_list_chatgpt_autotransfer' => '自动转人工',
	'chater_list_chatgpt_autotransfer_desc' => '机器人未能回答',
	'chater_list_chatgpt_autotransfer_desc1' => '次,自动转人工',
	'chater_list_chatgpt' => '文心一言',
	'chater_list_chatgpt_desc' => '智能客服机器人回答访客消息',
	'chater_list_chatgpt_API_Key' => 'API Key',
	'chater_list_chatgpt_API_Key_desc' => '请输入文心一言API Key',
	'chater_list_chatgpt_Secret_Key' => 'Secret Key',
	'chater_list_chatgpt_Secret_Key_desc' => '请输入文心一言Secret Key',
	'chater_list_chatgpt_API_Url' => 'API地址',
	'chater_list_chatgpt_Model' => '默认模型',
	'chater_list_chatgpt_Model1' => 'ERNIE-Bot',
	'chater_list_chatgpt_Model2' => 'ERNIE-Bot-turbo',
	'chater_list_chatgpt_Model3' => 'BLOOMZ-7B',
	'chater_list_chatgpt_Model4' => 'Qianfan-BLOOMZ-7B-compressed',
	'chater_list_chatgpt_Model5' => 'Llama-2-7b-chat',
	'chater_list_chatgpt_Model6' => 'Llama-2-13b-chat',
	'chater_list_chatgpt_Model7' => 'Llama-2-70b-chat',
	'chater_list_chatgpt_Model8' => 'Qianfan-Chinese-Llama-2-7B',
	'chater_list_chatgpt_Model9' => 'Linly-Chinese-LLaMA-2-7B',
	'chater_list_chatgpt_Model10' => 'Linly-Chinese-LLaMA-2-13B',
	'chater_list_chatgpt_Model11' => 'ChatGLM2-6B',
	'chater_list_chatgpt_Model12' => 'ChatGLM2-6B-32K',
	'chater_list_chatgpt_Model13' => 'ChatGLM2-6B-INT4',
	'chater_list_chatgpt_Model14' => 'Falcon-7B',
	'chater_list_chatgpt_Model15' => 'Falcon-40B-Instruct',
	'chater_list_chatgpt_Model16' => 'AquilaChat-7B',
	'chater_list_chatgpt_Model17' => 'RWKV-4-World',
	'chater_list_chatgpt_Model18' => 'RWKV-4-pile-14B',
	'chater_list_chatgpt_Model19' => 'RWKV-Raven-14B',
	'chater_list_chatgpt_Model20' => 'OpenLLaMA-7B',
	'chater_list_chatgpt_Model21' => 'Dolly-12B',
	'chater_list_chatgpt_Model22' => 'MPT-7B-Instruct',
	'chater_list_chatgpt_Model23' => 'MPT-30B-instruct',
	'chater_list_chatgpt_Model24' => 'OA-Pythia-12B-SFT-4',
	'chater_list_chatgpt_Model25' => 'Falcon-180B-Chat',
	'chater_list_chatgpt_Model26' => 'RWKV-5-World',
	'chater_list_chatgpt_Model27' => 'Flan-UL2',
	
	'chater_list_baidu_translate_configuration' => '百度翻译配置',
	'chater_list_baidu_translate' => '百度翻译',
	'chater_list_baidu_translate_desc' => '客服端会话中翻译消息',
	'chater_list_baidu_translate_appid' => '百度翻译(APP ID)',
	'chater_list_baidu_translate_appid_desc' => '请输入百度翻译APP ID',
	'chater_list_baidu_translate_key' => '百度翻译(密钥)',
	'chater_list_baidu_translate_key_desc' => '请输入百度翻译密钥',
   
   'chater_ro_title' => '入口管理',
   'chater_ro_add' => '添加入口',
   'chater_ro_delete' => '删除入口',
   'chater_ro_name' => '名称',
   'chater_ro_desc' => '描述',
   'chater_ro_dt' => '创建时间',
   'chater_ro_status' => '状态',
   'chater_ro_to_type' => '群聊',
   'chater_ro_order' => '排序',
   'chater_ro_up' => '上移',
   'chater_ro_down' => '下移',
   'chater_ro_attributes' => '属性',
   'chater_ro_member' => '成员',
   'chater_ro_tree_title' => '选择成员',
	
	'user_ro_title' => '访客标签管理',
	'user_ro_add' => '添加标签',
	'user_ro_delete' => '删除标签',
	'user_ro_name' => '名称',
	'user_ro_desc' => '描述',
	'user_ro_dt' => '创建时间',
	'user_ro_status' => '状态',
	'user_ro_order' => '排序',
	'user_ro_up' => '上移',
	'user_ro_down' => '下移',
	'user_ro_attributes' => '属性',
	
	'chater_theme_title' => '会话主题管理',
	'chater_theme_add' => '添加主题',
	'chater_theme_delete' => '删除主题',
	'chater_theme_name' => '名称',
	'chater_theme_desc' => '描述',
	'chater_theme_dt' => '创建时间',
	'chater_theme_status' => '状态',
	'chater_theme_order' => '排序',
	'chater_theme_up' => '上移',
	'chater_theme_down' => '下移',
	'chater_theme_attributes' => '属性',
   	'chater_theme_ro' => '主题分组',
	'chater_theme_ro1' => '使用主题',
	'chater_theme_ro2' => '历史主题',
	
	'chater_domain_title' => '跳转后的域名',
	'chater_domain_add' => '添加域名',
	'chater_domain_delete' => '删除域名',
	'chater_domain_name' => '跳转后的域名地址',
	'chater_domain_desc' => '描述',
	'chater_domain_dt' => '创建时间',
	'chater_domain_status' => '状态',
	'chater_domain_order' => '排序',
	'chater_domain_name_desc' => '例如http://www.haoqiniao.cn:98或https://www.haoqiniao.cn',
	
	'chater_wechat_title' => '微信公众号/小程序管理',
	'chater_wechat_add' => '添加公众号/小程序',
	'chater_wechat_delete' => '删除公众号/小程序',
	'chater_wechat_upload' => '上传验证文件',
	'chater_wechat_dt' => '创建时间',
	'chater_wechat_status' => '状态',

   //admin/lv_manager/file_edit.php
   'file_edit_lb_name' => '链接名称',
   'file_edit_lb_path' => '链接路径',
   'file_edit_attach' => '上传附件',
   'file_edit_btn_upload' => '上传',
   
   //admin/lv_manager/file_list.php
   'file_list_title' => '附件管理',
   'file_list_btn_add' => '新增公共文件',
   'file_list_btn_delete' => '删除文件',
   'file_list_dropdown_type-1' => '--所有类型--',
   'file_list_dropdown_type1' => '访客发送',
   'file_list_dropdown_type0' => '客服发送',
   'file_list_filed_account' => '客服帐号',
   'file_list_filed_username' => '访客姓名',
   'file_list_filed_chatid' => '会话ID',
   'file_list_filed_filename' => '文件名',
   'file_list_ph_key' => '关键字',
   'file_list_ph_date' => '日期',
   'file_list_table_chatid' => '会话ID',
   'file_list_table_filename' => '文件名',
   'file_list_table_username' => '访客',
   'file_list_table_chater' => '客服',
   'file_list_table_createdate' => '创建时间',
   'file_list_edit' => '编辑',
   'file_list_delete' => '删除',
   'file_list_alert' => '下载错误',
   
    //admin/lv_manager/link_edit.php
   'link_edit_lb_owner' => '所属者',
   'link_edit_option' => '--公共--',
   'link_edit_lb_name' => '链接名称',
   'link_edit_lb_path' => '链接路径',
   'link_edit_attach' => '上传附件',
   'link_edit_btn_upload' => '上传',
   
   
    //admin/lv_manager/link_list.php
   'link_list_title' => '链接管理',
   'link_list_btn_add' => '新增链接',
   'link_list_ph_search' => '查找链接',
   'link_list_table_name' => '名称',
   'link_list_table_address' => '地址',
   'link_list_table_owner' => '所属者',
   'link_list_table_createdate' => '创建时间',
   'link_list_edit' => '编辑',
   'link_list_delete' => '删除',
   
	//admin/lv_manager/question_edit.php
	'question_edit_lb_subject' => '问题',
	'question_edit_lb_usertext' => '答案',
	'question_edit_lb_usertext_desc' => '请输入答案',
	
	
	//admin/lv_manager/question_list.php
	'question_list_title' => '问答库',
	'question_list_btn_add' => '新增问题',
	'question_list_ph_search' => '查找问题',
	'question_list_table_name' => '问题',
	'question_list_table_address' => '答案',
	'question_list_table_createdate' => '创建时间',
	'question_list_edit' => '编辑',
	'question_list_delete' => '删除',
	
	'quicktalk_edit_lb_subject' => '标题',
	'quicktalk_edit_lb_usertext' => '内容',
	'quicktalk_edit_lb_usertext_desc' => '请输入标题',
	
	//admin/lv_manager/question_list.php
	'quicktalk_list_title' => '常用语管理',
	'quicktalk_list_btn_add' => '新增常用语',
	'quicktalk_list_ph_search' => '查找常用语',
	'quicktalk_list_table_name' => '标题',
	'quicktalk_list_table_address' => '内容',
	'quicktalk_list_table_createdate' => '创建时间',
	'quicktalk_list_edit' => '编辑',
	'quicktalk_list_delete' => '删除',
   
   
   //admin/lv_manager/message_list.php
   'message_list_title' => '留言管理',
   'message_list_groupid' => '请选择来源',
   'message_list_not' => '公共会话',
   'message_list_option_username' => '姓名',
   'message_list_option_phone' => '电话',
   'message_list_option_email' => '邮箱',
   'message_list_option_content' => '内容',
   'message_list_option_userid' => '用户ID',
   'message_list_ph_key' => '关键字',
   'message_list_ph_date' => '留言日期',
   'message_list_table_source' => '来源',
   'message_list_table_username' => '姓名',
   'message_list_table_phone' => '电话',
   'message_list_table_email' => '邮箱',
   'message_list_table_createtime' => '时间',
   'message_list_table_note' => '内容',
   
   //admin/lv_manager/rate_list.php
   'rate_list_title' => '评价管理',
   'rate_list_option_account' => '客服帐号',
   'rate_list_option_username' => '访客姓名',
   'rate_list_option_userid' => '用户ID',
   'rate_list_ph_key' => '关键字',
   'rate_list_ph_date' => '会话日期',
   'rate_list_table_chatid' => '会话ID',
   'rate_list_table_operator' => '客服',
   'rate_list_table_userid' => '用户ID',
   'rate_list_table_name' => '姓名',
   'rate_list_table_score' => '评分',
   'rate_list_table_des' => '说明',
   'rate_list_table_date' => '时间',
   
   'blackip_list_title' => '黑名单ip记录',
   'blackip_list_option_account' => '客服帐号',
   'blackip_list_option_username' => '访客姓名',
   'blackip_list_option_userid' => '用户ID',
   'blackip_list_ph_key' => '关键字',
   'blackip_list_ph_date' => '会话日期',
   'blackip_list_table_chatid' => '会话ID',
   'blackip_list_table_operator' => '客服',
   'blackip_list_table_userid' => '用户ID',
   'blackip_list_table_name' => '姓名',
   'blackip_list_table_score' => '评分',
   'blackip_list_table_des' => '说明',
   'blackip_list_table_date' => '时间',
   
  
   //admin/lv_manager/user_list.php
   'user_list_title' => '访客管理',
   'user_list_option_name' => '姓名',
   'user_list_option_phone' => '电话',
   'user_list_option_email' => '邮箱',
   'user_list_ph_key' => '关键字',
   'user_list_table_name' => '姓名',
   'user_list_table_phone' => '电话', //'
   'user_list_table_email' => '邮箱',
   'user_list_table_chater' => '优先接待客服',
   'user_list_table_remarks' => '备注',
   'user_list_table_regtime' => '注册时间',
   'user_list_table_chat' => '交谈',
   'user_list_table_message' => '留言',
   'user_list_table_attach' => '附件',
   
   
   //admin/report/attach_list.php
   'attach_list_tittle' => '附件查询',
   'attach_list_ph_search' => '附件查找',
   'attach_list_table_messageid' => '消息ID',
   'attach_list_table_sender' => '发送者',
   'attach_list_table_recipient' => '接收者',
   'attach_list_table_senddate' => '发送时间',
   'attach_list_table_content' => '消息内容',
   'attach_list_table_filename' => '文件名',
   'attach_list_table_filesize' => '大小',
   'attach_list_table_filetype' => '类型',
   'attach_list_table_fileguid' => '文件ID',
   'attach_type_screenhot' => '截图',
   'attach_type_file' => '普通文件',
     
    //admin/report/board_list.php
   'board_list_title' => '公告查询',
   'board_list_option_title' => '标题',
   'board_list_option_creator' => '发送者',
   'board_list_table_title' => '标题',
   'board_list_table_creator' => '发送者',
   'board_list_table_senddate' => '发送日期',
   'board_list_delete' => '删除',
   
   //admin/report/chat_list.php
   'chat_list_title' => '对话查询',
   'chat_list_txt_account1' => '帐号1:', //':'
   'chat_list_txt_account2' => '帐号2:', //':'
   'chat_list_txt_account3' => '群组号码:', //':'
   'chat_list_txt_account4' => '客服帐号:', //':'
   'chat_list_txt_account5' => '访客帐号:', //':'
   'chat_list_alert_none' => '没有数据',
   'chat_list_alert_enteraccount' => '请输入对话人员帐号',
   
   //admin/report/log_list.php
   'log_list_title' => '登录日志',
   'log_list_option' => '登录/退出',
   'log_list_option1' => '登录',
   'log_list_option2' => '退出',
   'log_list_option3' => '控制台登录',
   'log_list_ph_search' => '查找帐号',
   'log_list_table_account' => '帐号',
   'log_list_table_name' => '姓名',
   'log_list_table_date' => '时间',
   'log_list_table_sign' => '登录/退出',
   'log_list_table_ip' => 'IP地址',
   'log_list_table_mac' => 'MAC地址',
   
   
   //admin/report/msg_list.php
   'msg_list_title' => '消息查询',
   'msg_list_option_subject' => '标题',
   'msg_list_option_senderaccount' => '发送帐号',
   'msg_list_option_sendername' => '发送姓名',
   'msg_list_table_subject' => '标题',
   'msg_list_table_sender' => '发送者',
   'msg_list_table_receiver' => '接收者',
   'msg_list_table_senddate' => '发送日期',
   'msg_list_table_datapath' => '数据目录',
   'msg_list_table_sendermac' => 'MAC地址',
   'msg_list_table_senderip' => 'IP地址',
   'msg_list_table_chat' => '进入聊天',
   'msg_list_groupid' => '请选择群组',
   'msg_list_pid' => '请选择入口',
   
   
   //admin/report/msg_total.php
   'msg_total_title' => '消息统计',
   'msg_total_option_subject' => '标题',
   'msg_total_option_sender' => '发送者',
   'msg_total_table_subject' => '标题',
   'msg_total_table_sender' => '发送者',
   'msg_total_table_senddate' => '发送日期',
   'msg_total_table_datapath' => '数据目录',
   'msg_total_table_sendermac' => 'MAC地址',
   'msg_total_table_senderip' => 'IP地址',
   
   
   //admin/report/online_list.php
   'online_list_title' => '在线用户',
   'online_list_onlineuser' => '在线用户: ',
   'online_list_totaluser' => '总用户数: ',
   'online_list_table_account' => '帐号',
   'online_list_table_user' => '用户',
   'online_list_table_logintime' => '登陆时间',
   'online_list_table_manufacturer' => '品牌',
   'online_list_table_mac' => 'MAC地址',
   'online_list_table_ip' => 'IP地址',
   'online_list_table_version' => '状态',
   'online_list_table_usericoLine1' => '在线',
   'online_list_table_usericoLine2' => '离开',
   'online_list_table_usericoLine3' => '手机在线',
   
   //admin/report/sms_list.php
   'sms_list_title' => '短信统计',
   'sms_list_btn_batchdel' => '批量删除',
   'sms_list_table_sender' => '发送者',
   'sms_list_table_content' => '内容',
   'sms_list_table_recipient' => '接收者',
   'sms_list_table_sendtime' => '发送时间',
   'sms_list_table_status' => '状态',
   'sms_list_delete' => '删除',
   
   //admin/report/sms_recv_list.php
   'sms_recv_list_title' => '短信接收',
   'sms_recv_list_btn_batchdel' => '批量删除',
   'sms_recv_list_table_content' => '内容',
   'sms_recv_list_table_recipient' => '接收者',
   'sms_recv_list_table_sendtime' => '发送时间',
   'sms_recv_list_table_status' => '状态',
   'sms_recv_list_delete' => '删除',
   
   //admin/set/base.php   
   'base_title' => '基本设置',
   'base_alert_success' => '修改成功。',
   'base_lb_companyname' => '单位名',
   'base_lb_companyid' => '单位ID',
   'base_lb_port' => '端口号',
   'base_lb_directory' => '数据目录',
   'base_btn_save' => '保存设置',
   
   //admin/set/board_send.php 
   'board_send_title' => '发送公告',
   'board_send_alert_success' => '发送成功。 ',
   'board_send_lb_psw' => '发送密码',
   'board_send_lb_type' => '发送类型',
   'board_send_lb_onlineuser' => '在线用户',
   'board_send_lb_alluser' => '全部用户',
   'board_send_lb_content' => '发送内容',
   'board_send_btn_publish' => '发送公告',
   
   //admin/set/dw.php 
   'dw_title' => '个性化设置',
   'dw_alert_success' => '修改成功。',
   'dw_lb_unify' => '统一头像',
   'dw_recommend' => '推荐用95*95像素',
   'dw_clear' => '清除头像',
   'dw_save' => '保存设置',
   
   
   //admin/set/ios_set.php
   'ios_set_lb_psw' => 'Api主密码',
   'ios_set_ph_psw' => 'iOS API主密码',
   
   //admin/set/port_edit.php
   'port_edit_lb_port' => '端口',
   'port_edit_ph_port' => '端口',
   
   
   //admin/set/service.php
   'service_title' => '服务控制',
   'service_btn_launch' => '启动服务',
   'service_btn_restart' => '重启服务',
   'service_btn_stop' => '停止服务',
   'service_table_name' => '名称',
   'service_table_des' => '描述',
   'service_table_portaddress' => '端口地址',
   'service_table_porttype' => '端口类型',
   'service_table_status' => '状态',
   'service_table_change' => '修改',
   'service_data_messge' => '消息服务器',
   'service_data_video' => '视频服务器',
   'service_data_doc' => '文档服务',
   'service_data_file' => '文件服务',
   'service_data_meeting' => '会议服务',
   'service_data_meetingforward' => '会议中转服务',
   'service_data_main' => '主服务器',
   'service_data_netrelay' => 'p2p传输服务',
   'service_data_site' => 'php web服务',
   'service_data_upload' => '上传服务',
   'service_data_download' => '下载服务',
   'service_data_telnet' => '远程服务',
   'service_data_setverpic' => '图片传输服务',
   'service_data_zlchat' => '视频会议-主服务',
   'service_data_apache' => '视频会议-web服务',
   'service_data_mysql' => '视频会议-数据库服务器',
   
   
   //admin/set/set.php
   'set_title' => '系统设置',
   'set_alert_success' => '设置成功。',
   'set_alert_restart' => '您需要重新启动服务才能生效',
   'set_alert_restartnow' => '立即重启',
   'set_legend_server' => '服务端设置',
   'set_legend_client' => '客户端配置',
   'set_legend_integrate' => '系统集成设置',
   'set_legend_webserver' => 'Web管理端配置',
   'set_checkbox_disable_save' => '禁止服务端保存消息',
   'set_checkbox_enable_permission' => '启用组织权限控制',
   'set_checkbox_system' => '启动系统验证',
   'set_checkbox_verify' => '启动Active Directory验证用户',
   'set_checkbox_disable_bulletin' => '禁止公告',
   'set_checkbox_disable_changepsw' => '禁止客户端修改密码',
   'set_checkbox_disable_groupsharefile' => '禁止群共享文件',
   'set_checkbox_disable_creategroup' => '禁止客户端创建群组',
   'set_checkbox_allow_creategroup_board' => '允许创建经纪群',
   'set_checkbox_search' => '过滤搜索',
   'set_checkbox_delete' => '自动清除',
   'set_checkbox_days' => '天前的消息及文件',
   'set_btn_manually' => '手动清除消息',
   'set_checkbox_record' => '记录登陆日志信息',
   'set_checkbox_directory' => '数据存放的目录',
   'set_checkbox_datasync' => '启用数据同步推送',
   'set_datasync_url' => '数据同步地址',
   'set_checkbox_disable_saving' => '禁止客户端保存消息',
   'set_checkbox_disable_hyperlink' => '禁止客户端的超级链接',
   'set_checkbox_disable_invisible' => '禁止客户端显示脱机',
   'set_checkbox_allow_p2p' => '允许文件P2P传输',
   'set_checkbox_p2p_threshold' => '阀值',
   'set_checkbox_disable_note' => '禁止客户端显示对方打开消息的通知',
   'set_checkbox_away' => '支持自动离开功能',
   'set_checkbox_minutes' => '分',
   'set_checkbox_disable_mylink' => '禁止网址收藏功能',
   'set_checkbox_enable_online' => '启用多设备同时在线',
   'set_checkbox_enable_forwarding' => '启用音视频中转服务',
   'set_checkbox_enable_loginverify' => '启用第三方登录验证（需定制开发）',
   'set_loginverify_url' => '接入第三方应用验证地址',  
   'set_antserver_access_url' => '接入Server推送地址', 
   'set_push' => 'IOS推送设置',
   'set_btn_setting' => '设置',
   'set_checkbox_transcode' => '上传视频自动转码',
   'set_checkbox_publicdocuments_file_type' => '公共文档某些栏目不显示',
   'set_checkbox_publicdocuments' => '公共文档/图片/音乐/视频/最近更新/搜索结果不显示',
   'set_checkbox_publicdocuments_file_type_view' => '公共文档某些栏目无查看权限不显示',
   'set_checkbox_publicdocuments_view' => '公共文档/图片/音乐/视频/最近更新/搜索结果如果没有查看权限不显示(启用后将增加服务器负担)',
   'set_livechat' => '在线值班',
   'set_openplatform' => 'php7或着以上版本',
   'set_inquirybox' => '云盘上传同名文件弹出询问框(是否替换)',
   'set_enpmessage' => '数据传输加密',
   'set_verifyuserdevice'=>'查询统计',
   'set_userapply' => '客户端申请账号',      
   'set_userapply0' => '需要管理员审核',  
   'set_userapply1' => '申请后即可使用',  
   'set_userapply2' => '禁止申请',  
   'set_chats' => '服务器保存聊天记录(启用后将增加服务器负担)',  
   'set_logs' => '服务器保存事务日志(启用后将增加服务器负担)',  
   'set_control_computer' => '控制电脑(服务端控制客户端电脑)',
   'set_lock_screen' => '服务器程序启动后，自动锁定界面',      
   'set_offline_information' => '离线信息，转发到手机短信(必须启用短信功能)',  
   'set_minimize' => '服务器程序启动后，自动最小化界面',  
   'set_CheckIM0' => '管理员接收系统消息(例如用户注册审核,云盘/群组文件审核)',  
   'set_CheckIM1' => '电脑与手机同时在线,电脑版账号处于在线状态,手机版账号也能收到推送消息', 
   'set_delete_chats' => '服务器自动删除聊天记录',  
   'set_delete_chats1' => '15天前的记录',
   'set_delete_chats2' => '60天前的记录',
   'set_delete_chats3' => '不删除',
   'set_delete_offline_files' => '服务器自动删除离线文件',  
   'set_delete_offline_files1' => '15天前的文件',
   'set_delete_offline_files2' => '60天前的文件',
   'set_delete_offline_files3' => '不删除',
   'set_message_push' => '手机app消息推送间隔',  
   'set_message_push1' => '秒（值越小消息推送越快，但同时对服务器资源损耗越大）',
   'set_delete_server_files' => '当服务器文件达到磁盘',
   'set_delete_server_files1' => '%自动删除服务器文件(防止磁盘爆满损坏磁盘)',
   'set_delete_offline_notices' => '自动清除',
   'set_noticeday' => '天前的离线通知',
   'set_chatsday' => '天前的聊天记录',
   'set_port' => '端口说明',
   'set_port_description' => '基本通信通口:97、98、99、5994、5995、5996、5997(udp)、5998(udp)、6001、6002、6003、6004、6005、6006、6007、6008共16个端口,请确保服务器的端口都已经打开。',
       
   'set_login_error_count' => '后台登录错误次数限制为',
   'set_login_error_count_tip' => '0为不限制',
   
   //admin/set/skin_list.php
   'skin_list_title' => '皮肤管理',
   'skin_list_show' => '点击查看大图',
   'skin_list_preview' => '预览',
		
	//admin/set/server_list.php
	'server_list_title' => '服务器管理(多台即时通讯服务高可用方案)',
	'server_list_ip' => 'IP',
	'server_list_name' => '名称',
	'server_init_all' => '同步所有服务器初始化数据',
   
   //admin/set/update.php
   'update_type_pc' => 'PC端',
   'update_type_android' => '安卓端',
   'update_title' => '升级管理',
   'update_alert_success' => '导入成功',
   'update_restart' => '您需要重新启动服务才能生效',
   'update_alert_restartnow' => '立即重启',
   'update_lb_version' => '版本号',
   'update_ib_package' => '更新包',
   'update_btn_delpackage' => '删除更新包',
   'update_lb_uploadpackage' => '上传更新包',
   'update_btn_upload' => '上传更新包',
   'update_alert_delsuccess' => '删除成功',
   'update_alert_selectpackage' => '请选择更新包',
   
   //admin/set/user_change.php
   'user_change_title'  => '人员数据迁移',
   'user_change_old'    => '用户原账号',
   'user_change_new'    => '用户新账号',         
   'user_change_btn'    => '确认',
   'user_change_warning'=> '提示：这是修改人员账号后，迁移原账号消息，公告等数据到新账号中。请确认是否要修改人员账号！！！',
   'user_change_require'=> '账号不允许为空', 
        
   //admin/tools/addin_edit.php
   'addin_edit_lb_type' => '插件类型',
   'addin_edit_option0' => '插件包',
   'addin_edit_option1' => '命令插件',
   'addin_edit_option2' => '视图插件',
   'addin_edit_lb_status' => '状态',
   'addin_edit_option_normal' => '正常',
   'addin_edit_lb_option_disabled' => '禁用',
   'addin_edit_lb_public' => '是否公开',
   'addin_edit_option_yes' => '是',
   'addin_edit_option_no' => '否',
   'addin_edit_lb_sequence' => '排序',
   
   
   //admin/tools/addin_list.php
   'addin_sms' => '短信插件',
   'addin_list_title' => '插件管理',
   'addin_list_btn_search' => '插件查找',
   'addin_list_btn_import' => '导入插件',
   'addin_list_btn_add' => '新增插件',
   'addin_list_btn_permission' => '设置权限',
   'addin_list_btn_delete' => '删除插件',
   'addin_list_install' => '安装系统插件',
   'addin_list_roam' => '消息漫游',
   'addin_list_bulletin' => '公告查询',
   'addin_list_operator' => '在线客服',
   'addin_list_option_type' => '选择类型',
   'addin_list_option_command' => '命令插件',
   'addin_list_option_view' => '视图插件',
   'addin_list_ph_search' => '插件查找',
   'addin_list_table_type' => '类别',
   'addin_list_table_name' => '名称',
   'addin_list_table_public' => '公开',
   'addin_list_table_disable' => '禁用',
   'addin_list_table_desc' => '描述',
   'addin_list_table_package' => '插件包',
   'addin_list_table_sequence' => '排序',
   'addin_list_table_edit' => '修改',
   'addin_list_table_permission' => '权限',
   'addin_list_table_del' => '删除',
   'addin_list_table_up' => '上移',
   'addin_list_table_down' => '下移',
   'addin_list_add' => '新增插件',
   'addin_list_edit' => '修改插件',
   'addin_plug_name' => '插件名称',
   'addin_plug_displayname' => '显示的名称',
   'addin_plug_target' => 'url地址',
   'addin_plug_desc' => '描述',
   'addin_plug_width' => '窗口宽度',
   'addin_plug_width_desc' => '打开迷你窗口的宽度',
   'addin_plug_height' => '窗口高度',
   'addin_plug_height_desc' => '打开迷你窗口的高度',
   'addin_plug_param' => '参数',
   'addin_plug_image' => '图片的地址',
   'addin_plug_site' => '插件类型',
   'addin_plug_site0' => '短信',
   'addin_plug_site1' => '邮箱',
   'addin_plug_site2' => 'Main Menu 主菜单',
   'addin_plug_site3' => '用户卡片',
   'addin_plug_site4' => '用户卡片按钮',
   'addin_plug_site5' => '用户列表选择一个人的右键菜单',
   'addin_plug_site6' => '群列表选择群的右键菜单',
   'addin_plug_site7' => '手机Main Menu 主菜单',
   'addin_plug_site8' => '手机用户更多菜单选项',
   'addin_plug_site9' => '手机群组更多菜单选项',
   'addin_plug_site10' => '消息漫游',
   'addin_plug_site11' => '消息推送',
   'addin_plug_site12' => '实时音视频',
   'addin_plug_site13' => '消息邮件推送',
   'addin_plug_site14' => '其他',
   'addin_plug_targettype' => '目标程序打开方式',
   'addin_plug_targettype1' => '在客户端内部打开',
   'addin_plug_targettype2' => '在浏览器打开打开',
   'addin_plug_targettype3' => '其他',
   'addin_plug_bie' => '第三方系统编号',
   'addin_plug_enabled' => '状态',
   'addin_plug_enabled1' => '正常',
   'addin_plug_enabled0' => '禁用',
   'addin_plug_warning' => '第三方系统编号必须是正整数',
   'addin_plug_warning1' => '系统内置插件不允许此操作',
   'addin_plug_warning2' => '在线文档插件已关闭',
   'addin_plug_warning3' => '显示的名称不能有汉字',
   
   //admin/tools/client_edit.php
   'client_edit_lb_title' => '上传客户端',
   'client_edit_lb_name' => '客户端名称',
   'client_edit_ph_name' => '客户端名称',
   'client_edit_lb_version' => '版本号',
   'client_edit_ph_version' => '客户端版本',
   
   
   //admin/tools/client_list.php
   'client_list_lb_title' => '客户端程序发布',
   'client_list_btn_add' => '新增客户端',
   'client_list_btn_delete' => '删除客户端',
   'client_list_ph_search' => '查找客户端名称或版本',
   'client_list_table_name' => '客户端名称',
   'client_list_table_version' => '版本',
   'client_list_table_size' => '大小',
   'client_list_table_edit' => '编辑',
   'client_list_table_download' => '下载链接',
   'client_list_table_del' => '删除',
   

   
   //admin/tools/dept_picker.php
   'dept_picker_lb_deletedept' => '删除以前的部门',
   'dept_picker_alert_adduser' => '不能将人员设置到根节点下',
   
   
   //admin/tools/ext_edit.php
   'ext_edit_option_ADSServer' => '文档服务地址',
   'ext_edit_option_ADSPort' => '文档服务端口',
   'ext_edit_option_AVServerAddr' => '音视频服务地址',
   'ext_edit_option_AVServerPort' => '音视频服务端口',
   'ext_edit_option_FileServerAddr' => '文件服务地址',
   'ext_edit_option_FileServerPort' => '文件服务端口',
   'ext_edit_option_RoamingMessageUrl' => '漫游消息地址',
   'ext_edit_lb_data' => '数据',
   'ext_edit_lb_type' => '种类',
   
   
   //admin/tools/ext_list.php
   'ext_list_title' => '扩展属性',
   'ext_list_btn_add_custom' => '自定义扩展',
   'ext_list_btn_add_sys' =>'系统扩展',    
   'ext_list_btn_bulid' => '生成系统配置',
   'ext_list_ph_search' => '属性查找',
   'ext_list_table_name' => '名称',
   'ext_list_table_desc' => '描述',
   'ext_list_table_data' => '数据',
   'ext_list_table_edit' => '修改',
   'ext_list_table_del' => '删除',
   'ext_list_col_ADSServer' => '文档服务地址',
   'ext_list_col_ADSPort' => '文档服务端口',
   'ext_list_col_AVServerAddr' => '音视频服务地址',
   'ext_list_col_AVServerPort' => '音视频服务端口',
   'ext_list_col_FileServerAddr' => '文件服务地址',
   'ext_list_col_FileServerPort' => '文件服务端口',
   'ext_list_col_RoamingMessageUrl' => '漫游消息地址',
   'ext_list_add' => '新增属性',
   'ext_list_change' => '修改属性',
   
   
   //admin/tools/interface_edit.php
   'interface_edit_lb_name' => '名称',
   'interface_edit_lb_address' => '地址',
   'interface_edit_lb_public' => '公开',
   'interface_edit_public_yes' => '是',
   'interface_edit_public_no' => '否',
   'interface_edit_lb_status' => '状态',
   'interface_edit_status0' => '正常',
   'interface_edit_status1' => '禁用',
   'interface_edit_lb_desc' => '描述',
   'interface_edit_lb_sequence' => '排序',
   'interface_edit_lb_type' => '类型',
   'interface_edit_type0' => '全部',
   'interface_edit_type1' => 'PC端应用',
   'interface_edit_type2' => 'Android应用',
   'interface_edit_type3' => 'iOS应用',
   'interface_edit_entername' => '请输入名称',
   'interface_edit_enteraddress' => '请输入地址',
   
   
   //admin/tools/interface_list.php
   'interface_list_title' => '接口管理',
   'interface_list_btn_add' => '新增接口',
   'interface_list_btn_batch' => '批量操作',
   'interface_list_dropdown_permission' => '设置权限',
   'interface_list_dropdown_del' => '删除',
   'interface_list_ph_search' => '接口查找',
   'interface_list_table_name' => '名称',
   'interface_list_table_address' => '地址',
   'interface_list_table_type' => '类型',
   'interface_list_table_disable' => '禁用',
   'interface_list_table_sequence' => '排序',
   'interface_list_table_edit' => '修改',
   'interface_list_table_permission' => '权限',
   'interface_list_table_del' => '删除',
   'interface_list_table_up' => '上移',
   'interface_list_table_down' => '下移',
   'interface_list_type0' => '全部',
   'interface_list_type1' => 'PC端应用',
   'interface_list_type2' => 'Android应用',
   'interface_list_type3' => 'iOS应用',
   'interface_list_add' => '新增接口',
   'interface_list_change' => '修改接口',
   
   
   //admin/tools/sms_account.php
   'sms_account_title' => '短信帐号',
   'sms_account_btn_assign' => '分配',
   'sms_account_table_account' => '帐号',
   'sms_account_table_psw' => '密码',
   'sms_account_table_dept' => '部门',
   'sms_account_table_edit' => '修改',
   'sms_account_table_del' => '删除',
   
   
   //admin/tools/sms_account_edit.php
   'sms_account_edit_lb_account' => '发送帐号',
   'sms_account_edit_lb_psw' => '发送密码',
   'sms_account_edit_lb_dept' => '选择部门',
   'sms_account_edit_btn_select' => '选择部门',
   
   'field_online_lasttime' => '最后登录',
   'field_online_status' => '是否在线',
   
   //admin/tools/view_url.php
   'view_url_link' => '下载链接',
   
   'valid_db_connect_error' => '数据库连接失败，请检查连接配置或重新设置连接',
   
   
   'imp_map_warning' => '属性项用tab键分隔,多行间用换行符分开',
   'btn_impmap' => '导入人员映射',

   'update_software_upgrade' => '软件升级',
   'update_product_website' => '产品网址',
   'update_warning' => '软件不是最新版,请打开www.haoqiniao.cn下载最新版或联系客服获取离线升级包.',
   'update_download' => '下载离线升级包',
   
   'set_client_configuration' => '客户端安装包配置',
   'set_client_warning' => '生成客户端安装包成功。',
   'set_client_download' => '立即下载',
   'set_client_basic_settings' => '基本设置',
   'set_client_WebName' => '公司名称',
   'set_client_WebNa' => '快捷方式',
   'set_client_WebNa_desc' => '客户端电脑显示的软件快捷方式',
   'set_client_WebRun' => '客户端启动时，弹出网站',
   'set_client_logo' => '公司logo',
   'set_client_edit_logo' => '更改logo',
   'set_client_delete_logo' => '清除logo',
   'set_client_banner' => '公司banner',
   'set_client_edit_banner' => '更改banner',
   'set_client_delete_banner' => '清除banner',
   'set_client_pan' => '云盘logo',
   'set_client_server_connection' => '服务器连接',
   'set_client_ServerIp' => 'IP地址',
   'set_client_ServerIp_desc' => '多个ip以逗号隔开',
   'set_client_Option1' => '连接方式',
   'set_client_Option10' => 'IP地址',
   'set_client_Option11' => '域名',
   'set_client_Option12' => '计算机名称',
   'set_client_Server_CheckIM1' => '自动登录',
   'set_client_Server_CheckIM2' => '记住密码',
   'set_client_software_settings' => '软件设置',
   'set_client_CheckIM0' => 'Windows系统启动时,启用本软件',
   'set_client_CheckIM1' => '主面板，总显示前面',
   'set_client_CheckIM2' => '使用大图标',
   'set_client_CheckIM3' => '应用声音主题效果',
   'set_client_CheckIM4' => '自动弹出信息窗体',
   'set_client_CheckIM5' => '禁止所有提示（信息）',
   'set_client_CheckIM6' => '文件传输完成后,打开所在文件夹',
   'set_client_CheckIM7' => '启用热键功能',
   'set_client_CheckIM8' => '禁止用户名片提示',
   'set_client_CheckIM9' => '登录时更新数据',
   'set_client_CheckIM11' => '合并会话窗口',
   'set_client_CheckIM13' => '截屏时隐藏窗口',
   'set_client_CheckIM14' => '文本模式',
   'set_client_CheckTab5' => '显示系统邮箱按钮',
   'set_client_CheckTab6' => '显示云盘按钮',
   'set_client_CheckTab9' => '显示主菜单按钮',
   'set_client_CheckTab10' => '显示高级设置',
   'set_client_CheckTab11' => '显示所有消息记录按钮',
   'set_client_CheckTab12' => '显示文件助手按钮',
   'set_client_CheckTab13' => '显示收藏按钮',
   'set_client_CheckTab14' => '显示查找按钮',
   'set_client_HotKey0' => '提取消息快捷键',
   'set_client_HotKey1' => '屏幕截屏快捷键',
   
   'msg_list_expired'=> '本功能已过期,请联系客服购买授权',
    //admin/tools/keywords_list
    'keywords_type'=>'过滤类型',
    'keywords_content'=>'过滤内容',  
    'enable_keyword'=>'启用敏感词过滤',
	'enable_customerservicemode'=>'客服模式',
    'keywords_type_one'=> '方案一：过滤词变*发送',   
	'keywords_type_two'=> '方案二：有过滤词不能发送'	
)
;
?>
