<?php
return array(
	'header_password_dialog' => '修改密碼',
	'header_download' => '下載用戶端',
	'header_logout' => '退出',
	'header_dropdown' => '幫助',
	'header_register' => '註冊',
	'header_about' => '關於',
	'header_login_btn' => '登錄',
	
	'menu_dir' => '目錄',
	'menu_history' => '最近',
	'menu_doc' => '文檔',
	'menu_img' => '圖片',
	'menu_create' => '創建',
	
	'originalTitle' => '觸點雲',
	'icon_folder_public' => '公共文檔',
	'icon_folder_person' => '個人文檔',
	'icon_recent' => '最近更新',
	'icon_office' => '文檔',
	'icon_pic' => '圖片',
	'icon_music' => '音樂',
	'icon_video' => '視頻',
	'icon_upload' => '上傳',
	'icon_upload1' => '上傳大檔案',
	'icon_upload2' => '上傳單檔案',
	'icon_download' => '下載',
	'icon_attr' => '詳情',
	'icon_edit' => '重命名',
	'icon_delete' => '刪除',
	'icon_share' => '分享',
	'icon_reload' => '刷新',
	'icon_set' => '設置權限',
	'icon_doc_edit' => '編輯',
	'icon_qrcode' => '二維碼下載',
	'icon_save' => '保存到雲盤',
	'icon_folder_create' => '新建目錄',
	'icon_move' => '移動到',
	'dropdown-toggle' => '排序',
	'icon_time' => '按時間排序',
	'icon_az' => '按名稱排序',
	'icon_thumb' => '顯示縮略圖',
	'icon_list' => '顯示列表',
	'path_node' => '目錄',
	'upload_title' => '個文件傳輸中',
	'icon_warning' => '新建文件夾成功!',
	'icon_warning1' => '暫無文件',
	'icon_warning2' => '請點擊左上角的“上傳”按鈕添加文件',
	'icon_warning3' => '搜索全部文件',
	'icon_warning4' => '輸入文件名並按下回車進行搜索',
	
	'pnl_error' => '帳號或密碼錯誤',
	'pnl_error1' => '請先登錄再進行操作',
	'txt_loginname' => '帳號',
	'txt_loginname_desc' => '請輸入帳號',
	'txt_password' => '密碼',
	'txt_password_desc' => '請輸入密碼',
	'btn_login' => '登錄',
	
	'pnl_success' => '密碼修改成功,重新登錄生效。 ',
	'old_password' => '舊密碼',
	'new_password' => '新密碼',
	'confirm_password' => '確認密碼',
	
	'btn_save' => '保存',
	'btn_ok' => '確定',
	'btn_cancel' => '取消',
	'btn_close' => '關閉',
	'btn_cloud_save' => '保存到雲盤',
	
	'doc_type_name' => '類型',
	'col_name' => '名稱',
	'path' => '路徑',
	'doc_attribution' => '歸屬',
	'col_dt_create' => '創建時間',
	'doc_type_file' => '文件',
	'doc_type_folder' => '文件夾',
	
	'share_url' => '鏈接',
	'copy_share_url' => '複製鏈接',
	
	'save_to' => '保存到',
	'move_to' => '移動到',
	'doc_move_alert1' => '個文件/文件夾',
	'doc_move_alert2' => '請選擇移動到的目錄',
	'doc_move_alert3' => '目標地址不能是原來地址',
	
	'txt_folder_name' => '目錄名稱',
	
	'addin_alert' => '在線文檔插件已關閉',
	
	'set_authority1' => '對誰公開',
	'set_authority10' => '所有人',
	'set_authority11' => '特定成員',
	'set_authority12' => '僅自己可用',
	'set_authority2' => '獲得文檔的人',
	'set_authority20' => '選定編輯',
	'set_authority21' => '可以編輯',
	'set_title' => '添加可編輯該文檔的成員(選中的成員有編輯權限,其他成員只有查看權限)',
	'set_title1' => '設置特定成員',
	'set_userkey' => '輸入帳號或姓名',
	'set_addMemberByInput' => '添加成員',
	'set_edit' => '編輯',
	'set_name' => '姓名',
	'set_account' => '帳號',
	'set_authority3' => '發送消息通知',
	'set_authority30' => '忽略',
	'set_authority31' => '通知',
    'menu_sub_ptp_file' => '雲盤檔案',
    'menu_sub_group_file' => '群組檔案',
    'menu_sub_leave_file' => '離線檔案',
    'menu_sub_file_alert1' => '我更新了',
	'menu_sub_file_alert2' => '[系統自動發送]',
	
	'doceditor_title' => '在線文檔',
	'doceditor_warning' => '當前僅能查看,登錄後可獲得更多操作權限',
	'doceditor_read' => '(只讀)',
	'doceditor_login_btn' => '登錄',
	'doceditor_doc_set' => '權限',
	'doceditor_doc_col' => '收藏',
	'doceditor_doc_share' => '分享',
	'doceditor_logout_btn' => '退出',
	'doceditor_file_empty' => '文件不存在',
	'doceditor_file_empty1' => '您沒有權限查看',
	'doceditor_edited_document' => '編輯了文檔',
	
	'onlinefile_warning' => '該帳號不存在,驗證失敗!',
	'onlinefile_warning1' => '該帳號被禁用,驗證失敗!',
	'onlinefile_warning2' => '該帳號未登錄,驗證失敗',
	'onlinefile_warning3' => '驗證失敗,令牌無效',
	'onlinefile_icon_recent' => '最近',
	'onlinefile_icon_folder_person' => '我創建的',
	'onlinefile_icon_folder_public' => '與我共享',
	'onlinefile_doc_create1' => '新建文檔',
	'onlinefile_doc_create2' => '新建表格',
	
	'col_chk_notall' => '全不選',
	'col_chk_all' => '全選',
	'folder_nav_box' => '保存位置:個人文檔',
	'btn_return' => '返回上一級',
	
	'download_title1' => '下載專區',
	'download_title2' => '後臺管理',
	'download_title3' => '開發檔案',
	'download_title4' => '全國統一服務熱線',
	'download_title5' => '官方網站',
	'download_title6' => '當前位置',
	'download_title7' => 'PC版-用戶端',
	'download_title8' => '系統環境 WinNT/2K/XP/vista/7/8/10/11<br />/server 2003/server 2008/server 2012<br />/server 2019/server 2022<br /> 版本：10.9<br />大小：45 M',
	'download_title9' => '系統環境：Android<br />版本：所有<br />大小：42.8 M<br />',
	'download_title10' => '系統環境：IOS<br />版本：所有<br />大小：52.6 M',
	'download_title11' => '掃一掃下載手機版',
	'download_title12' => 'PC端登入時：<br />點擊&quot； 網絡&quot； ,輸入<br />IP/功能變數名稱/電腦名稱。 ',
	'download_title13' => '手機端登入時：點擊&quot； 網絡&quot； ,輸入外網IP/功能變數名稱. <br />說明：ios版可以從app store下載,蒐索&quot； 好奇鳥&quot； ',
	'download_title14' => '相關下載',
	'download_title15' => '售後服務',
	'download_title16' => '1、 當需要特別手機端安裝包時,請和我們聯系,例如需要設定默認服務端IP,這樣的好處是不需要去告訴公司員工服務端IP是多少,直接讓員工輸入用戶名密碼就可以登入了。 <br />2、 無論產品有沒有付費,如果在使用過程中遇到科技問題,請和我們聯系。 <br />3、 如果需要與現有管理系統（例如簡訊系統、企業郵箱、erp、oa、crm）進行集成,因為開發好奇鳥挿件有一定的專業要求,如果有這方面的需求,請和我們聯系。 <br />4、 如果需要將現有系統（例如OA等）員工資訊導入到好奇鳥系統,請和我們聯系。 <br />',
	'download_title17' => '好奇雲盤用戶手冊.docx',
	'download_title18' => '好奇鳥RTC介紹.ppt',
	'download_title19' => '<em></em>打開APP登入頁面<br><em></em>網絡選擇外網輸入功能變數名稱：',
	'download_title20' => '點擊複製功能變數名稱',
);
?>