if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[temp_user]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[temp_user]
GO

CREATE TABLE [dbo].[temp_user] (
	[Col_ID] [int] IDENTITY (1, 1) NOT NULL ,
	[Col_LoginName] [varchar] (50) NULL ,
	[Col_Name] [varchar] (50) NULL ,
	[Col_PWord] [varchar] (50) NULL ,
	[Col_IsSuper] [bit] NOT NULL ,
	[Col_IsSystem] [bit] NOT NULL ,
	[Col_Disabled] [bit] NOT NULL ,
	[Col_EnType] [int] NULL ,
	[Col_IsFarUser] [bit] NOT NULL ,
	[Col_FarServer] [varchar] (50) NULL ,
	[Col_DomainID] [int] NULL ,
	[Col_ItemIndex] [int] NULL ,
	[Col_Dt_Create] [datetime] NULL ,
	[Col_Creator_Name] [varchar] (50) NULL ,
	[Col_OnlineState] [int] NULL ,
	[Col_MsgServer] [varchar] (50) NULL ,
	[Col_SignServer] [varchar] (50) NULL ,
	[Col_Note] [varchar] (255) NULL ,
	[Col_EMail] [varchar] (50) NULL ,
	[Col_Mobile] [varchar] (50) NULL ,
	[Col_Sex] [int] NULL ,
	[Col_Description] [varchar] (255) NULL ,
	[Col_Birthday] [datetime] NULL ,
	[Col_h_Province] [varchar] (50) NULL ,
	[Col_h_City] [varchar] (50) NULL ,
	[Col_h_Address] [varchar] (64) NULL ,
	[Col_h_PostCode] [varchar] (50) NULL ,
	[Col_h_Phone] [varchar] (50) NULL ,
	[Col_h_Fax] [varchar] (50) NULL ,
	[Col_o_CompanyName] [varchar] (50) NULL ,
	[Col_o_Address] [varchar] (64) NULL ,
	[Col_o_PostCode] [varchar] (50) NULL ,
	[Col_o_JobTitle] [varchar] (50) NULL ,
	[Col_o_Phone] [varchar] (50) NULL ,
	[Col_o_Fax] [varchar] (50) NULL ,
	[Col_Picture] [varchar] (100) NULL ,
	[Col_ECard] [varchar] (255) NULL ,
	[Col_DeptInfo] [varchar] (255) NULL ,
	[Col_Pic_MofidyDate] [datetime] NULL ,
	[Col_DeptID] [int] NULL ,
	[Col_IsDelete] [bit] NULL ,
	[Col_UserData] [varchar] (50) NULL ,
	[Col_HomePage] [varchar] (100) NULL ,
	[Col_Online] [int] NULL,
	[Col_CompanyID] [int] NULL,
	[Col_Dt_Modify] [datetime] NULL,
	[Col_IpAddr] [varchar] (255) NULL ,
	[Col_FirstSpell] [varchar] (64) NULL,
	[Col_AllSpell] [varchar] (64) NULL,
	[Col_PhoneID] [varchar] (50) NULL,
	[Col_addnum] [int] NULL,
	[Col_Creator_ID] [int] NULL,
	[col_pos_idx] [smallint] NULL,
	[col_alldeptinfo] [varchar] (1024) NULL,
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[temp_user] WITH NOCHECK ADD
	CONSTRAINT [PK_temp_user] PRIMARY KEY  CLUSTERED
	(
		[Col_ID]
	)  ON [PRIMARY]
GO

ALTER TABLE [dbo].[temp_user] ADD
	CONSTRAINT [DF_temp_user_Col_LoginName] DEFAULT ('') FOR [Col_LoginName],
	CONSTRAINT [DF_temp_user_Col_Name] DEFAULT ('') FOR [Col_Name],
	CONSTRAINT [DF_temp_user_Col_PWord] DEFAULT ('') FOR [Col_PWord],
	CONSTRAINT [DF_temp_user_Col_IsSuper] DEFAULT (0) FOR [Col_IsSuper],
	CONSTRAINT [DF_temp_user_Col_IsSystem] DEFAULT (0) FOR [Col_IsSystem],
	CONSTRAINT [DF_temp_user_Col_Disabled] DEFAULT (0) FOR [Col_Disabled],
	CONSTRAINT [DF_temp_user_Col_EnType] DEFAULT (0) FOR [Col_EnType],
	CONSTRAINT [DF_temp_user_Col_IsFarUser] DEFAULT (0) FOR [Col_IsFarUser],
	CONSTRAINT [DF_temp_user_Col_FarServer] DEFAULT ('') FOR [Col_FarServer],
	CONSTRAINT [DF_temp_user_Col_DomainID] DEFAULT (0) FOR [Col_DomainID],
	CONSTRAINT [DF_temp_user_Col_ItemIndex] DEFAULT (10000) FOR [Col_ItemIndex],
	CONSTRAINT [DF_temp_user_Col_CreateDate] DEFAULT (getdate()) FOR [Col_Dt_Create],
	CONSTRAINT [DF_temp_user_Col_Creator_Name] DEFAULT ('') FOR [Col_Creator_Name],
	CONSTRAINT [DF_temp_user_Col_OnlineState] DEFAULT (0) FOR [Col_OnlineState],
	CONSTRAINT [DF_temp_user_Col_MsgServer] DEFAULT ('') FOR [Col_MsgServer],
	CONSTRAINT [DF_temp_user_Col_SignServer] DEFAULT ('') FOR [Col_SignServer],
	CONSTRAINT [DF_temp_user_Col_Note] DEFAULT ('') FOR [Col_Note],
	CONSTRAINT [DF_temp_user_Col_EMail] DEFAULT ('') FOR [Col_EMail],
	CONSTRAINT [DF_temp_user_Col_Mobile] DEFAULT ('') FOR [Col_Mobile],
	CONSTRAINT [DF_temp_user_Col_Sex] DEFAULT (0) FOR [Col_Sex],
	CONSTRAINT [DF_temp_user_Col_Description] DEFAULT ('') FOR [Col_Description],
	CONSTRAINT [DF_temp_user_Col_Birthday] DEFAULT (getdate()) FOR [Col_Birthday],
	CONSTRAINT [DF_temp_user_Col_h_Province] DEFAULT ('') FOR [Col_h_Province],
	CONSTRAINT [DF_temp_user_Col_h_City] DEFAULT ('') FOR [Col_h_City],
	CONSTRAINT [DF_temp_user_Col_h_Address] DEFAULT ('') FOR [Col_h_Address],
	CONSTRAINT [DF_temp_user_Col_h_PostCode] DEFAULT ('') FOR [Col_h_PostCode],
	CONSTRAINT [DF_temp_user_Col_h_Phone] DEFAULT ('') FOR [Col_h_Phone],
	CONSTRAINT [DF_temp_user_Col_h_Fax] DEFAULT ('') FOR [Col_h_Fax],
	CONSTRAINT [DF_temp_user_Col_o_CompanyName] DEFAULT ('') FOR [Col_o_CompanyName],
	CONSTRAINT [DF_temp_user_Col_o_Address] DEFAULT ('') FOR [Col_o_Address],
	CONSTRAINT [DF_temp_user_Col_o_PostCode] DEFAULT ('') FOR [Col_o_PostCode],
	CONSTRAINT [DF_temp_user_Col_o_JobTitle] DEFAULT ('') FOR [Col_o_JobTitle],
	CONSTRAINT [DF_temp_user_Col_o_Phone] DEFAULT ('') FOR [Col_o_Phone],
	CONSTRAINT [DF_temp_user_Col_o_Fax] DEFAULT ('') FOR [Col_o_Fax],
	CONSTRAINT [DF_temp_user_Col_Picture] DEFAULT ('') FOR [Col_Picture],
	CONSTRAINT [DF_temp_user_Col_ECard] DEFAULT ('') FOR [Col_ECard],
	CONSTRAINT [DF_temp_user_Col_DeptInfo] DEFAULT ('') FOR [Col_DeptInfo],
	CONSTRAINT [DF_temp_user_Col_Pic_MofidyDate] DEFAULT (getdate()) FOR [Col_Pic_MofidyDate],
	CONSTRAINT [DF_temp_user_Col_DeptID] DEFAULT (0) FOR [Col_DeptID],
	CONSTRAINT [DF_temp_user_Col_IsDelete] DEFAULT (0) FOR [Col_IsDelete],
	CONSTRAINT [DF_temp_user_Col_UserData] DEFAULT ('') FOR [Col_UserData],
	CONSTRAINT [DF_temp_user_Col_HomePage] DEFAULT ('') FOR [Col_HomePage],
	CONSTRAINT [DF_temp_user_Col_Online] DEFAULT (0) FOR [Col_Online],
	CONSTRAINT [DF_temp_user_Col_CompanyID] DEFAULT (0) FOR [Col_CompanyID],
	CONSTRAINT [DF_temp_user_Col_Dt_Modify] DEFAULT (getdate()) FOR [Col_Dt_Modify],
	CONSTRAINT [DF_temp_user_Col_IpAddr] DEFAULT ('') FOR [Col_IpAddr],
	CONSTRAINT [DF_temp_user_Col_FirstSpell] DEFAULT ('') FOR [Col_FirstSpell],
	CONSTRAINT [DF_temp_user_Col_AllSpell] DEFAULT ('') FOR [Col_AllSpell],
	CONSTRAINT [DF_temp_user_Col_PhoneID] DEFAULT ('') FOR [Col_PhoneID],
	CONSTRAINT [DF_temp_user_Col_addnum] DEFAULT (0) FOR [Col_addnum],
	CONSTRAINT [DF_temp_user_Col_Creator_ID] DEFAULT (0) FOR [Col_Creator_ID],
	CONSTRAINT [DF_temp_user_col_pos_idx]  DEFAULT ((0)) FOR [col_pos_idx],
	CONSTRAINT [DF_temp_user_col_alldeptinfo]  DEFAULT ('') FOR [col_alldeptinfo]
GO

CREATE INDEX IX_temp_user_1 ON temp_user(Col_LoginName);