delimiter $$

CREATE TABLE `temp_user` (
  `Col_ID` int(11) auto_increment,
  `Col_LoginName` varchar(50) default '',
  `Col_Name` varchar(50) default '',
  `Col_PWord` varchar(50) default '',
  `Col_IsSuper` int(2) default '0',
  `Col_IsSystem` int(2) default '0',
  `Col_Disabled` int(2) default '0',
  `Col_EnType` int(11) default '0',
  `Col_IsFarUser` int(2) default '0',
  `Col_FarServer` varchar(50) default '',
  `Col_DomainID` int(11) default '0',
  `Col_ItemIndex` int(11) default '10000',
  `Col_Dt_Create` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Col_Creator_Name` varchar(50) default '',
  `Col_OnlineState` int(11) default '0',
  `Col_MsgServer` varchar(50) default '',
  `Col_SignServer` varchar(50) default '',
  `Col_Note` varchar(255) default '',
  `Col_EMail` varchar(50) default '',
  `Col_Mobile` varchar(50) default '',
  `Col_Sex` int(11) default '0',
  `Col_Description` varchar(255) default '',
  `Col_Birthday` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `Col_h_Province` varchar(50) default '',
  `Col_h_City` varchar(50) default '',
  `Col_h_Address` varchar(255) default '',
  `Col_h_PostCode` varchar(50) default '',
  `Col_h_Phone` varchar(50) default '',
  `Col_h_Fax` varchar(50) default '',
  `Col_o_CompanyName` varchar(50) default '',
  `Col_o_Address` varchar(64) default '',
  `Col_o_PostCode` varchar(50) default '',
  `Col_o_JobTitle` varchar(50) default '',
  `Col_o_Phone` varchar(50) default '',
  `Col_o_Fax` varchar(50) default '',
  `Col_Picture` varchar(100) default '',
  `Col_ECard` varchar(255) default '',
  `Col_DeptInfo` varchar(255) default '',
  `Col_Pic_MofidyDate` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `Col_DeptID` int(11) default '0',
  `Col_IsDelete` int(2) default '0',
  `Col_UserData` varchar(50) default '',
  `Col_HomePage` varchar(100) default '' ,
  `Col_Online` int(11) default '0',
  `Col_CompanyId` int(11) default '0',
  `Col_Dt_Modify` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `Col_IpAddr` varchar(255) default '' ,
  `Col_FirstSpell` varchar(64) default '' ,
  `Col_AllSpell` varchar(64) default '' ,
  `Col_PhoneID` varchar(50) default '' ,
  `col_addnum` int(11) default '0',
  `Col_Creator_ID` int(11) default '0',
  `col_pos_idx` int(11) DEFAULT '0',
  `col_alldeptinfo` varchar(1024) DEFAULT '',
  KEY `Col_ID` (`Col_ID`),
  KEY `Col_LoginName` (`Col_LoginName`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8