<?php
return array(
	'sample' => '例',
	'url' => '地址',
	'attach' => '附件',
	'attach_size' => '大小',
	'download' => '下載',
	'msg_file_error'  => '消息文件被刪除' ,
	'file_error'  => '文件不存在' ,
	'no_power'=>'沒有權限',
	'index_service' => '在線客服',
		
	'msg_file_error'  => '消息文件被刪除' ,
	'msg_recv_pic'  => '收到新圖片文件' ,
	'msg_recv_sound'  => '收到新語音文件' ,
	'msg_recv_attach'  => '收到新附件' ,
	'msg_recv_chatgpt'  => '[小觸機器人已回復]' ,
	'msg_recv_chatgpt1'  => '小觸機器人未開啟，請聯系管理員!' ,
	'msg_recv_chatgpt2'  => '小觸機器人API Key不能為空，請聯系管理員!' ,
	'msg_recv_chatgpt12'  => '小觸機器人Secret Key不能為空，請聯系管理員!' ,
	'msg_recv_chatgpt13'  => '小觸機器人API地址不能為空，請聯系管理員!' ,
	
	'viewport_org'  => '組織結構',
	'doc_manager_public' => '公共文檔',
	'customer_service_list'  => '客服列表',
	
	'valid_file_type_error' => '文件類型不正確',
	'valid_file_not_exist' => '文件不存在',
	'valid_upload_size_limit' => '上傳文件不能超過[{FileSize}M]',
	'valid_local_limit' => '只能在服務器上操作',
	
	'error_db_connect_error' => '連接失敗！ 如果使用軟件內寘資料庫請等待所有彈出的挿件安裝好再來配寘資料庫； 如果使用服務器已安裝的資料庫請檢查資料庫資訊是否正確.',
	
	'sn_path_error' => '配置的服務器路徑錯誤',
	'sn_activation_error' => '激活碼錯誤',
	'sn_machine_error' => '激活碼錯誤[機器碼不符]',
	'ad_connect_fail' => 'AD服務器連接失敗',
	
	'module_doc_manager' => '共享文檔',
		
	'grant_exist' => '用戶已經授權過此部門',
	'grant_beyond' => '超出授權人數',      
	
	'file' => '文件',
	'folder' => '文件夾',
	'cloud_isexists' => '已經存在！',
	'cloud_authority_error' => '妳沒有權限下載',   
	'cloud_download' => '下載雲盤文件',
	'cloud_download_leavefile' => '下載離線文件',
	'cloud_download_onlinefile' => '下載在線文件',
	'cloud_delete_leavefile' => '刪除離線文件',
	'cloud_delete_clotfile' => '刪除群組文件',
	'cloud_delete_onlinefile' => '刪除在線文檔',
	'cloud_file' => '雲盤文件',
	'cloud_clotfile' => '群組文件',
	'cloud_error' => '請不要在根目錄上傳',
	'cloud_error1' => '請等待管理員通過審核', 
	'cloud_error2' => '妳沒有權限修改', 
	'cloud_error3' => '妳沒有權限刪除', 
	'cloud_error4' => '妳沒有權限管理', 
	'cloud_error5' => '保存成功，請等待管理員通過審核!', 
	'cloud_error6' => '數據不存在',
	'cloud_error7' => '妳沒有權限創建',
	'cloud_error8' => '已經存在',
	'cloud_error9' => '此文件夾沒有文件',
	'cloud_error10' => '存在非法字符',
	'cloud_revisedfile1' => '將文檔恢復到第',
	'cloud_revisedfile2' => '版',
	'cloud_create_folder' => '創建文件夾',
	'cloud_warning' => '修改共享成員為',
	'cloud_warning1' => '文件共享',
	'cloud_warning2' => '退出共享',
	'cloud_warning3' => '添加共享成員',
	'cloud_warning4' => '刪除共享成員',
	'cloud_warning5' => '下載多個雲盤文件',
	'cloud_warning6' => '下載多個離線文件',
	'cloud_warning7' => '目前有',
	'cloud_warning8' => 'M,打包文件大小限制為',
	'cloud_warning9' => '個文件,打包文件數限制為',
	'cloud_warning10' => '個',
	'cloud_warning11' => '文件共享有更新，趕緊去看看新增了哪些好內容把！',
	'cloud_warning12' => '您已成為',
	'cloud_warning13' => '文件共享的壹員，趕緊去看看有什麽好的內容把！',
	'cloud_warning14' => '您已被移出了該文件共享！',
	'cloud_warning15' => '退出了文件共享！',
	'cloud_warning16' => '上傳了文件，請您通過審核！',
	'cloud_warning17' => '請先刪除子節點!',
	'cloud_warning18' => '文件重複部分文件移動失敗!',
	
	'docdir_error' => '非法路徑',
	'docdir_error1' => '路徑錯誤',
	
	'fun_error' => '非法登錄',
	'fun_error1' => '需重新登錄',
	
	'import_export_start_time' => '開始導入時間',
	'import_export_end_time' => '開始導入時間',
	'import_export_warning' => 'AD服務器連接失敗',
	'import_export_warning1' => '進來了',
	'import_export_warning2' => '沒有數據',
	'import_export_warning3' => '格式不正確',
	
	'install_warning' => '安裝完畢',
	
	'role_warning' => '通過壹鍵創建的角色。',
	
	'class_site_warning' => '只能在服務器上操作,請打開',
	'class_site_warning1' => '如果打開頁面空白,請使用高版本瀏覽器!',
	'class_thumbHandler_warning' => '圖片不存在',
	'class_thumbHandler_warning1' => '圖片源為空',
	'class_thumbHandler_warning2' => '字體文件不存在',
	'class_thumbHandler_warning3' => '圖片縮放比例不得小於1',
	'class_thumbHandler_warning4' => '目標寬度不能為0',
	'class_thumbHandler_warning5' => '目標高度不能為0',
	'class_thumbHandler_warning6' => '水印文字過大',
	'class_thumbHandler_warning7' => '水印圖片為空',
	'class_thumbHandler_warning8' => '圖片邊框過大，已超過了圖片的寬度',
	'class_thumbHandler_warning9' => '水印圖片尺寸大於原圖，請縮小水印圖',
	'class_thumbHandler_warning10' => '文件不存在,不能取得文件類型!',
	'class_thumbHandler_warning11' => '水印圖片為空',
	
	'class_doc_warning' => '目錄',
	'class_doc_warning1' => '不存在',
	'class_doc_warning2' => '上傳雲盤文件',
	'class_doc_warning3' => '刪除雲盤文件',
	'class_doc_warning4' => '將',
	'class_doc_warning5' => '存入雲盤',
	'class_doc_warning6' => '個人文檔',
	'class_doc_warning7' => '文件名包含特殊字符',
	'class_doc_warning8' => '不能上傳特殊文件',
	'class_doc_warning9' => '文件夾名稱包含特殊字符',
	'class_doc_warning10' => '文件上傳失敗',
	'class_doc_warning11' => '上傳並覆蓋同名雲盤檔案',
	'class_doc_warning12' => '上傳文件',
	'class_doc_warning13' => '失敗，原因檔案太大',
	'class_doc_warning14' => '失敗，原因目錄',
	'class_doc_warning15' => '失敗，原因不能上傳特殊檔案',
	'class_doc_warning16' => '删除雲盤目錄',
	
	'class_grant_warning' => '沒有權限新增用戶',
	'class_grant_warning1' => '新增用戶數已經超出，最多',
	'class_grant_warning2' => '人',
	
	'class_hs_warning' => '數據列數與定義的不符',
	'class_hs_warning1' => '已經存在',
	'class_hs_warning2' => '沒有內容',
	
	'class_passport_warning' => '登錄服務端管理後臺',
	'class_passport_warning1' => '登錄雲盤',
	'class_passport_warning2' => '登入線上客服',
	
	'class_msgreader_warning' => '成功發送',
	'class_msgreader_warning1' => '轉發',
	'class_msgreader_warning2' => '到雲盤查看',
	'class_msgreader_warning3' => '名片',
	'class_msgreader_warning4' => '發消息',
	'class_msgreader_warning5' => '群名片',
	'class_msgreader_warning6' => '查看',
	
	'class_PHPExcel_UppeID' => '分組',
	'class_PHPExcel_UserName' => '賬號',
	'class_PHPExcel_FcName' => '姓名',
	'class_PHPExcel_UserIco' => '性別(1為男,2為女)',
	'class_PHPExcel_Effigy' => '其他',
	'class_PHPExcel_Tel1' => '手機',
	'class_PHPExcel_Jod' => '職務',
	'class_PHPExcel_UserPaws' => '密碼',
	'class_PHPExcel_ItemIndex' => '排序號',
	
	'class_PHPExcel_Col_Ro' => '常用語分組',
	'class_PHPExcel_Col_Form' => '常用語',
	
	'online_list_table_account' => '帳號',
	'online_list_table_user' => '用戶',
	'online_list_table_logintime' => '登陸時間',
	'online_list_table_mac' => 'MAC地址',
	'online_list_table_ip' => 'IP地址',
	'online_list_table_version' => '狀態',
	'online_list_table_usericoLine1' => '在線',
	'online_list_table_usericoLine2' => '離開',
	'online_list_table_usericoLine3' => '手機在線',
	'field_dept' => '部門',
	'user_list_col_sex' => '性別',
	'user_edit_lb_gender1' => '男',
	'user_edit_lb_gender2' => '女',
	
	'livechat_message0' => '客服 {name} 不在線，請留言',
	'livechat_message1' => '客服 {name} 為您服務',
	'livechat_message2' => ' 用戶進入',
	'livechat_message3' => '用戶長時間未回复，稍後系統將自動結束會話',
	'livechat_message4' => '系統關閉',
	'livechat_message5' => ' 會話轉接至 {name}',
	'livechat_message6' => ' 不能和自己聊天',
	'livechat_message7' => '客服',
	'livechat_message8' => '我',
	'livechat_message9' => '未知',
	'livechat_message10' => '未選擇',
	'livechat_message11' => '未評估',
	'livechat_message12' => '無價值',
	'livechat_message13' => '有價值',
	'livechat_message14' => '非入口會話',
	'livechat_message15' => '公共會話',
	'livechat_message16' => '在線訪客',
	'livechat_message17' => '進入',
	'livechat_message18' => '訪客不在線',
	'livechat_message19' => '訪客對話中',
	'livechat_message20' => '用戶點擊了熱門問題 {name}',
	
	'register_alert1' => '系統關閉了自由申請帳號功能，請聯系管理員。',
	'register_alert2' => '用戶賬號已存在,請使用另外壹個用戶賬號!',
	'register_alert3' => '賬號申請',
	'register_alert4' => '申請了帳號，請您通過審核!',
	'register_alert5' => '賬號不能含有中文',
	'register_alert6' => '姓名不能包含特殊字符',
	
	'meeting_alert1' => '人正在',
	'meeting_alert2' => '語音通話',
	'meeting_alert3' => '視頻通話',
	'meeting_alert4' => '妳正在其他設備通話,點擊轉至本機.',
	
	'lv_chat_file' => '[文件]',
	'lv_chat_location' => '[位置]',
	'lv_chat_pic' => '[圖片]',
	'lv_chat_expression' => '[表情]',
	'lv_chat_video' => '[視頻]',
	'lv_chat_voice' => '[語音消息]',
	'lv_chat_link' => '[鏈接]',
	
	// 文檔日誌類型
	'type_downloadfile' => '下載文件',
	'type_editfile' => '編輯文件',
	'type_newfile' => '創建文件',
	'type_removefile' => '移動文件',
	'type_viewfile' => '查看文件',
	'type_deletefile' => '刪除文件',
	'type_sharefile' => '共享文件',
	'type_login' => '登錄',
)
;
?>
