CREATE TABLE "SYSDBA"."YFSDL"
(
 "ID" INT DEFAULT 0
 NULL,
 "MOBILE" VARCHAR(15) NOT NULL,
 "CONTENT" VARCHAR(255) NOT NULL,
 "DEADTIME" TIMESTAMP(0) NOT NULL,
 "STATUS" INT NOT NULL,
 "MSGID" INT NULL,
 "IMUSERID" VARCHAR(20) NULL
);

CREATE TABLE "SYSDBA"."WEATHERFORM"
(
 "TODATE" VARCHAR(10) NOT NULL,
 "TEMPERATURE" VARCHAR(40) NULL,
 "MORNING" VARCHAR(40) NULL,
 "EVENING" VARCHAR(40) NULL,
 "WEICO" SMALLINT NULL,
 "TOTIME" TIMESTAMP(0) NULL,
 "CITY" VARCHAR(20) NULL
);

CREATE TABLE "SYSDBA"."USERS_WININFO"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "WINDOWSINFO" VARCHAR(200) NULL,
 "USERNAME" VARCHAR(20) NULL,
 "UPAN" VARCHAR(50) NULL,
 "LOCALIP" VARCHAR(50) NULL,
 "USERICOLINE" SMALLINT DEFAULT 0
 NULL,
   CONSTRAINT "PK_Users_WinInfo"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."USERS_ROLE"
(
 "USERID" VARCHAR(50) NULL,
 "ROLEID" INT DEFAULT 0
 NULL
);

CREATE TABLE "SYSDBA"."USERS_RO"
(
 "TYPEID" VARCHAR(20) NOT NULL,
 "TYPENAME" VARCHAR(200) NULL,
 "PARENTID" VARCHAR(50) DEFAULT 0
 NULL,
 "DESCRIPTION" VARCHAR(3900) NULL,
 "ITEMINDEX" VARCHAR(50) DEFAULT 0
 NULL,
 "CREATORID" VARCHAR(50) DEFAULT 1
 NULL,
 "CREATORNAME" VARCHAR(200) DEFAULT 'admin'
 NULL,
   CONSTRAINT "PK_Users_Ro"  CLUSTER PRIMARY KEY("TYPEID") ENABLE 
);

CREATE TABLE "SYSDBA"."USERS_PIC"
(
 "USERID" VARCHAR(20) NOT NULL,
 "PIC" INT DEFAULT 0
 NULL,
 "SFILE" INT DEFAULT 0
 NULL,
   CONSTRAINT "PK_Users_Pic"  CLUSTER PRIMARY KEY("USERID") ENABLE 
);

CREATE TABLE "SYSDBA"."USERS_ID"
(
 "UPPEID" VARCHAR(200) NOT NULL,
 "USERID" VARCHAR(20) NOT NULL,
 "USERNAME" VARCHAR(200) NULL,
 "USERPAWS" VARCHAR(200) NULL,
 "FCNAME" VARCHAR(200) NULL,
 "AGE" VARCHAR(5) NULL,
 "JOD" VARCHAR(20) NULL,
 "TEL1" VARCHAR(20) NULL,
 "TEL2" VARCHAR(20) NULL,
 "ADDRESS" VARCHAR(30) NULL,
 "SAY" VARCHAR(3900) NULL,
 "USERICO" SMALLINT DEFAULT 0
 NULL,
 "USERICOLINE" SMALLINT DEFAULT 0
 NULL,
 "SCHOOL" VARCHAR(30) NULL,
 "EFFIGY" VARCHAR(20) NULL,
 "CONSTELLATION" VARCHAR(20) NULL,
 "REMARK" VARCHAR(200) NULL,
 "SEQUENCE" INT DEFAULT 0
 NULL,
 "BINDING" BIT DEFAULT 1
 NOT NULL,
 "LOGINTIME" TIMESTAMP(0) NULL,
 "USERSTATE" INT DEFAULT 1
 NULL,
 "NETWORKIP" VARCHAR(50) NULL,
 "LOCALIP" VARCHAR(50) NULL,
 "MAC" VARCHAR(50) NULL,
 "REGISTRATION_ID" VARCHAR(200) NULL,
 "PLATFORM" VARCHAR(50) NULL,
 "MANUFACTURER" VARCHAR(50) NULL,
 "LOCALIPLIST" VARCHAR(200) NULL,
 "MACLIST" VARCHAR(200) NULL,
 "ISVERIFY" INT DEFAULT 1
 NULL,
 "ISMANAGER" INT DEFAULT 0
 NULL,
 "FAV_FORMVESR" INT DEFAULT 0
 NULL,
 "COL_FORMVESR" INT DEFAULT 0
 NULL,
 "USERS_IDVESR" INT DEFAULT 0
 NULL,
 "CREATORID" VARCHAR(50) DEFAULT 1
 NULL,
 "CREATORNAME" VARCHAR(200) DEFAULT 'admin'
 NULL,
   CONSTRAINT "PK_Users_ID"  CLUSTER PRIMARY KEY("USERID") ENABLE 
);

CREATE TABLE "SYSDBA"."UPDATEFORM"
(
 "ID" INT NULL,
 "USERS_ROVESR" INT DEFAULT 0
 NULL,
 "USERS_IDVESR" INT DEFAULT 0
 NULL,
 "CLOT_ROVESR" INT DEFAULT 0
 NULL,
 "CLOT_FORMVESR" INT DEFAULT 0
 NULL,
 "CLOTFILE_VESR" INT DEFAULT 0
 NULL,
 "SECINFOVESR" INT DEFAULT 0
 NULL,
 "TEL_FORMVESR" INT DEFAULT 0
 NULL,
 "PTPFILE_VESR" INT DEFAULT 0
 NULL,
 "PTPFOLDER_VESR" INT DEFAULT 0
 NULL,
 "PTPFORM_VESR" INT DEFAULT 0
 NULL,
 "LEAVEFILE_VESR" INT DEFAULT 0
 NULL,
 "NEWGO_VESR" INT DEFAULT 0
 NULL,
 "NEWRO_VESR" INT DEFAULT 0
 NULL,
 "MYTEL_ROVESR" INT DEFAULT 0
 NULL,
 "MYTEL_FORMVESR" INT DEFAULT 0
 NULL,
 "PLUG_VESR" INT DEFAULT 0
 NULL
);

CREATE TABLE "SYSDBA"."TOINFO"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "TO_DATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "TO_TIME" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "TO_TXT" VARCHAR(3900) NULL,
 "FONTINFO" VARCHAR(50) NULL,
   CONSTRAINT "PK_ToInfo"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."TEL_FORM"
(
 "UPPEID" VARCHAR(20) NOT NULL,
 "TYPEID" INT IDENTITY(1,1) NOT NULL,
 "PANAME" VARCHAR(20) NOT NULL,
 "TELNAME" VARCHAR(20) NULL,
 "TELICO" SMALLINT DEFAULT 1
 NULL,
 "TELETE1" VARCHAR(40) NULL,
 "TELETE2" VARCHAR(40) NULL,
 "REMARK" VARCHAR(100) NULL,
 "TO_DATE" TIMESTAMP(0) NULL,
   CONSTRAINT "PK_Tel_Form"  CLUSTER PRIMARY KEY("TYPEID") ENABLE 
);

CREATE TABLE "SYSDBA"."TAB_MEET_MSG_XXX"
(
 "COL_MEETID" VARCHAR(38) NOT NULL,
 "COL_MSGID" VARCHAR(38) NOT NULL,
 "COL_SENDLOGIN" VARCHAR(80) DEFAULT ''
 NOT NULL,
 "COL_SENDNAME" VARCHAR(50) DEFAULT ''
 NOT NULL,
 "COL_DATE" TIMESTAMP(0) DEFAULT GETDATE()
 NOT NULL,
 "COL_CONTENT" VARCHAR(512) DEFAULT ''
 NOT NULL,
 "COL_CONTENTTYPE" VARCHAR(50) DEFAULT ''
 NOT NULL,
 "COL_DATAPATH" VARCHAR(50) DEFAULT ''
 NOT NULL,
   CONSTRAINT "PK_Tab_Meet_Msg_XXX"  CLUSTER PRIMARY KEY("COL_MEETID","COL_MSGID") ENABLE 
);

CREATE TABLE "SYSDBA"."TAB_MEET_MEMBER"
(
 "COL_MEETID" VARCHAR(38) NOT NULL,
 "COL_USERLOGIN" VARCHAR(80) DEFAULT ''
 NULL,
 "COL_USERNAME" VARCHAR(50) DEFAULT ''
 NULL,
 "COL_USERID" INT DEFAULT 0
 NOT NULL,
 "COL_JOINSTATE" SMALLINT DEFAULT 0
 NULL,
 "COL_JOINTIME" TIMESTAMP(0) DEFAULT '1900-01-01 00:00:00'
 NULL,
 "COL_ISADMIN" INT DEFAULT 0
 NULL,
 "COL_LASTMSGTIME" TIMESTAMP(0) DEFAULT '1900-01-01 00:00:00'
 NULL,
 "COL_SOCKETID" VARCHAR(200) NULL,
 "COL_LOGINTYPE" SMALLINT DEFAULT 1
 NULL,
 "COL_ISAUDIO" SMALLINT DEFAULT 0
 NULL,
 "COL_ISVIDEO" SMALLINT DEFAULT 0
 NULL,
 "COL_STATE" SMALLINT DEFAULT 0
 NULL
);

CREATE TABLE "SYSDBA"."TAB_MEET_FILE_GROUP"
(
 "COL_MEETID" VARCHAR(38) NOT NULL,
 "COL_NAME" VARCHAR(80) NOT NULL,
   CONSTRAINT "PK_Tab_Meet_File_Group"  CLUSTER PRIMARY KEY("COL_MEETID","COL_NAME") ENABLE 
);

CREATE TABLE "SYSDBA"."TAB_MEET_FILE"
(
 "COL_MEETID" VARCHAR(38) NOT NULL,
 "COL_FILEID" VARCHAR(38) NOT NULL,
 "COL_FILENAME" VARCHAR(255) DEFAULT ''
 NOT NULL,
 "COL_FILESIZE" BIGINT DEFAULT 0
 NOT NULL,
 "COL_FILESNAME" VARCHAR(50) DEFAULT ''
 NOT NULL,
 "COL_FILETYPE" SMALLINT DEFAULT 0
 NOT NULL,
 "COL_SENDLOGIN" VARCHAR(80) DEFAULT ''
 NOT NULL,
 "COL_SENDNAME" VARCHAR(50) DEFAULT ''
 NOT NULL,
 "COL_SENDDATE" TIMESTAMP(0) DEFAULT GETDATE()
 NOT NULL,
 "COL_DOWNCOUNT" INT DEFAULT 0
 NULL,
 "COL_GROUP" VARCHAR(80) DEFAULT ''
 NULL,
   CONSTRAINT "PK_Tab_Meet_File"  CLUSTER PRIMARY KEY("COL_MEETID","COL_FILEID") ENABLE 
);

CREATE TABLE "SYSDBA"."TAB_MEET"
(
 "COL_ID" VARCHAR(38) NOT NULL,
 "COL_NAME" VARCHAR(50) DEFAULT ''
 NOT NULL,
 "COL_DESC" VARCHAR(128) DEFAULT ''
 NULL,
 "COL_NOTICE" VARCHAR(255) DEFAULT ''
 NULL,
 "COL_CREATELOGIN" VARCHAR(80) DEFAULT ''
 NULL,
 "COL_CREATENAME" VARCHAR(50) DEFAULT ''
 NULL,
 "COL_CREATEID" INT DEFAULT 0
 NULL,
 "COL_CREATEDATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "COL_ISDELETE" BIT DEFAULT 0
 NULL,
 "COL_TYPE" SMALLINT DEFAULT 0
 NULL,
 "COL_JOINVERIFY" SMALLINT DEFAULT 0
 NULL,
 "COL_GENRE" VARCHAR(50) DEFAULT ''
 NULL,
 "COL_USERCOUNT" SMALLINT DEFAULT 200
 NULL,
 "COL_MSGINDEX" SMALLINT DEFAULT 0
 NULL,
 "COL_DOMAINID" VARCHAR(50) DEFAULT ''
 NULL,
 "COL_ISAUDIO" SMALLINT DEFAULT 0
 NULL,
 "COL_ISVIDEO" SMALLINT DEFAULT 0
 NULL,
 "COL_STATE" SMALLINT DEFAULT 0
 NULL,
 "COL_SCHDATE" TIMESTAMP(0) DEFAULT '1900-01-01 00:00:00'
 NULL,
   CONSTRAINT "PK_Tab_Meet"  CLUSTER PRIMARY KEY("COL_ID") ENABLE 
);

CREATE TABLE "SYSDBA"."TAB_CONFIG"
(
 "COL_NAME" VARCHAR(50) DEFAULT ''
 NULL,
 "COL_DATA" VARCHAR(150) DEFAULT ''
 NULL,
 "COL_GENRE" VARCHAR(50) DEFAULT ''
 NULL,
 "COL_ANTSERVER" VARCHAR(50) DEFAULT ''
 NULL,
 "COL_LOGINNAME" VARCHAR(50) DEFAULT ''
 NULL,
 "COL_HSITEMID" INT DEFAULT 0
 NULL,
 "COL_HSITEMTYPE" INT DEFAULT 0
 NULL,
 "COL_PACKAGENAME" VARCHAR(50) DEFAULT ''
 NULL,
 "COL_DISABLED" BIT DEFAULT 0
 NULL,
 "COL_ID" INT IDENTITY(1,1) NOT NULL,
   CONSTRAINT "PK_Tab_Config"  CLUSTER PRIMARY KEY("COL_ID") ENABLE 
);

CREATE TABLE "SYSDBA"."TAB_CHAT"
(
 "CHATID" INT NOT NULL,
 "GROUPID" INT DEFAULT 0
 NULL,
 "MYID" VARCHAR(50) NULL,
 "YOUID" VARCHAR(50) DEFAULT 0
 NULL,
 "USERNAME" VARCHAR(50) NULL,
 "IP" VARCHAR(50) NULL,
 "AREA" VARCHAR(50) NULL,
 "INTIME" TIMESTAMP(0) NULL,
 "CONNECTTIME" TIMESTAMP(0) DEFAULT GETDATE()
 NOT NULL,
 "OUTTIME" TIMESTAMP(0) NULL,
 "SOCKETID" VARCHAR(200) NULL,
 "ISAUDIO" SMALLINT DEFAULT 0
 NULL,
 "ISVIDEO" SMALLINT DEFAULT 0
 NULL,
 "LOGINTYPE1" SMALLINT DEFAULT 1
 NULL,
 "LOGINTYPE2" SMALLINT DEFAULT 1
 NULL,
 "ISAUDIO1" SMALLINT DEFAULT 0
 NULL,
 "ISVIDEO1" SMALLINT DEFAULT 0
 NULL,
 "ISAUDIO2" SMALLINT DEFAULT 0
 NULL,
 "ISVIDEO2" SMALLINT DEFAULT 0
 NULL,
 "STATUS" INT DEFAULT 0
 NULL,
 "CLOSEROLE" INT DEFAULT 0
 NULL,
 "RATE" INT DEFAULT 0
 NULL,
 "RATENOTE" VARCHAR(500) NULL,
 "ALLOWUPLOADFILE" INT DEFAULT 0
 NULL,
 "NCONTENT" VARCHAR(500) NULL,
 "ORD" INT DEFAULT 0
 NULL,
   CONSTRAINT "PK_Tab_Chat"  CLUSTER PRIMARY KEY("CHATID") ENABLE 
);

CREATE TABLE "SYSDBA"."SERVERLOG"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "TODATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "TXT" VARCHAR(100) NULL,
 "USERID" VARCHAR(20) NULL,
 "IP" VARCHAR(50) NULL,
 "ICO" INT DEFAULT 1
 NULL,
 "TO_TYPE" INT DEFAULT 1
 NULL,
   CONSTRAINT "PK_ServerLog"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."SERVERERRLOG"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "TODATE" VARCHAR(50) NULL,
 "ERR1" VARCHAR(200) NULL,
 "ERR2" VARCHAR(200) NULL,
   CONSTRAINT "PK_ServerErrLog"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."SECINFO"
(
 "TYPEID" INT IDENTITY(1,1) NOT NULL,
 "INFOTIME" VARCHAR(5) NOT NULL,
 "REMARK" VARCHAR(3900) NULL,
   CONSTRAINT "PK_SecInfo"  CLUSTER PRIMARY KEY("TYPEID") ENABLE 
);

CREATE TABLE "SYSDBA"."RTC_SMS_ADDRESS"
(
 "COL_ID" INT IDENTITY(1,1) NOT NULL,
 "COL_NAME" VARCHAR(50) DEFAULT ''
 NULL,
 "COL_MOBILE" VARCHAR(50) DEFAULT ''
 NULL,
 "COL_OWNER" VARCHAR(50) DEFAULT ''
 NULL,
   CONSTRAINT "PK_ANT_SMS_ADDRESS"  CLUSTER PRIMARY KEY("COL_ID") ENABLE 
);

CREATE TABLE "SYSDBA"."RTC_SMS_ACCOUNT"
(
 "COL_ID" INT IDENTITY(1,1) NOT NULL,
 "COL_ACCOUNT" VARCHAR(50) DEFAULT ''
 NULL,
 "COL_PASSWORD" VARCHAR(50) DEFAULT ''
 NULL,
 "COL_EMP_TYPE" INT DEFAULT 0
 NULL,
 "COL_EMP_ID" INT DEFAULT 0
 NULL,
 "COL_EMP_NAME" VARCHAR(255) DEFAULT ''
 NULL,
 "COL_CREATOR_ID" INT DEFAULT 0
 NULL,
 "COL_CREATOR_NAME" VARCHAR(50) DEFAULT ''
 NULL,
 "COL_DT_CREATE" TIMESTAMP(0) DEFAULT GETDATE()
 NOT NULL,
   CONSTRAINT "PK_Ant_sms_account"  CLUSTER PRIMARY KEY("COL_ID") ENABLE 
);

CREATE TABLE "SYSDBA"."RTC_SMS"
(
 "COL_ID" INT IDENTITY(1,1) NOT NULL,
 "COL_CONTENT" VARCHAR(1024) DEFAULT ''
 NULL,
 "COL_RECV_MOBILE" VARCHAR(1024) DEFAULT ''
 NULL,
 "COL_RECV_NAME" VARCHAR(3900) DEFAULT ''
 NULL,
 "COL_SEND_NAME" VARCHAR(50) DEFAULT ''
 NULL,
 "COL_SEND_TIME" VARCHAR(50) DEFAULT ''
 NULL,
 "COL_SEND_URL" TEXT DEFAULT ''
 NULL,
 "COL_CREATOR_ID" INT DEFAULT 1
 NULL,
 "COL_CREATOR_NAME" VARCHAR(50) DEFAULT ''
 NULL,
 "COL_DT_CREATE" TIMESTAMP(0) DEFAULT GETDATE()
 NOT NULL,
 "COL_STATUS" INT DEFAULT 0
 NULL,
 "COL_RETURN" VARCHAR(255) DEFAULT ''
 NULL,
 "COL_FLAG" INT DEFAULT 0
 NULL,
 "COL_SEND_LOGINNAME" VARCHAR(50) DEFAULT ''
 NULL
);

CREATE TABLE "SYSDBA"."RTC_KEYWORD"
(
 "COL_ID" VARCHAR(50) NOT NULL,
 "COL_TYPE" INT DEFAULT 0
 NOT NULL,
 "COL_KEYWORD" VARCHAR(1024) DEFAULT ''
 NOT NULL,
 "COL_DATE" VARCHAR(20) DEFAULT ''
 NULL,
   CONSTRAINT "PK_ant_keyword"  CLUSTER PRIMARY KEY("COL_ID") ENABLE 
);

CREATE TABLE "SYSDBA"."ROLE"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "ROLENAME" VARCHAR(50) NULL,
 "DESCRIPTION" VARCHAR(3900) NULL,
 "PERMISSIONS" VARCHAR(200) NULL,
 "PLUG" VARCHAR(200) NULL,
 "PTPSIZE" INT DEFAULT 0
 NULL,
 "PTPTYPE" VARCHAR(200) NULL,
 "PUBSIZE" INT DEFAULT 0
 NULL,
 "PUBTYPE" VARCHAR(200) NULL,
 "CLOTSIZE" INT DEFAULT 0
 NULL,
 "CLOTTYPE" VARCHAR(200) NULL,
 "USERSSIZE" INT DEFAULT 0
 NULL,
 "USERSTYPE" VARCHAR(200) NULL,
 "DEPARTMENTPERMISSION" INT DEFAULT 0
 NULL,
 "DEPARTMENT" VARCHAR(3900) NULL,
 "SMSCOUNT" INT DEFAULT 0
 NULL,
 "DEFAULTROLE" INT DEFAULT 0
 NULL,
 "CREATORID" VARCHAR(50) DEFAULT 1
 NULL,
 "CREATORNAME" VARCHAR(200) DEFAULT 'admin'
 NULL,
   CONSTRAINT "PK_Role"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."REMOTE_CHAT"
(
 "CHATID" INT NOT NULL,
 "GROUPID" INT DEFAULT 0
 NULL,
 "MYID" VARCHAR(50) NULL,
 "YOUID" VARCHAR(50) DEFAULT 0
 NULL,
 "USERNAME" VARCHAR(50) NULL,
 "IP" VARCHAR(50) NULL,
 "AREA" VARCHAR(50) NULL,
 "INTIME" TIMESTAMP(0) NULL,
 "CONNECTTIME" TIMESTAMP(0) DEFAULT GETDATE()
 NOT NULL,
 "OUTTIME" TIMESTAMP(0) NULL,
 "STATUS" INT DEFAULT 0
 NULL,
 "CLOSEROLE" INT DEFAULT 0
 NULL,
 "RATE" INT DEFAULT 0
 NULL,
 "RATENOTE" VARCHAR(500) NULL,
 "ALLOWUPLOADFILE" INT DEFAULT 0
 NULL,
 "NCONTENT" VARCHAR(500) NULL,
 "ORD" INT DEFAULT 0
 NULL,
   CONSTRAINT "PK_remote_chat"  CLUSTER PRIMARY KEY("CHATID") ENABLE 
);

CREATE TABLE "SYSDBA"."PTPFORM"
(
 "MYID" VARCHAR(20) NULL,
 "USERID" VARCHAR(20) NULL,
 "PTPFOLDERID" VARCHAR(50) NULL
);

CREATE TABLE "SYSDBA"."PTPFOLDERFORM"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "MYID" VARCHAR(20) NULL,
 "USERID" VARCHAR(20) NULL,
 "TO_TYPE" INT NULL,
 "DOCACE" INT DEFAULT 1
 NULL,
 "PTPFOLDERID" VARCHAR(50) NULL,
 "TODATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "TOTIME" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
   CONSTRAINT "PK_PtpFolderForm"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."PTPFOLDER"
(
 "PTPFOLDERID" INT IDENTITY(1,1) NOT NULL,
 "MYID" VARCHAR(50) NULL,
 "USNAME" VARCHAR(50) NULL,
 "PARENTID" VARCHAR(50) DEFAULT 0
 NULL,
 "TODATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "TOTIME" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "TO_TYPE" SMALLINT DEFAULT 3
 NULL,
 "CREATORID" VARCHAR(50) DEFAULT 1
 NULL,
 "CREATORNAME" VARCHAR(200) DEFAULT 'admin'
 NULL,
   CONSTRAINT "PK_PtpFolder"  CLUSTER PRIMARY KEY("PTPFOLDERID") ENABLE 
);

CREATE TABLE "SYSDBA"."PTPFILE"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "MSG_ID" VARCHAR(255) NULL,
 "MYID" VARCHAR(10) NULL,
 "USNAME" VARCHAR(50) NULL,
 "TYPEPATH" VARCHAR(255) NULL,
 "PCSIZE" VARCHAR(50) NULL,
 "TODATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "TOTIME" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "PTPFOLDERID" VARCHAR(50) NULL,
 "FILPATH" VARCHAR(200) NULL,
 "TO_TYPE" SMALLINT NULL,
 "ONLINEID" INT DEFAULT 0
 NULL,
 "FILESTATE" INT DEFAULT 1
 NULL,
 "CREATORID" VARCHAR(50) DEFAULT 1
 NULL,
 "CREATORNAME" VARCHAR(200) DEFAULT 'admin'
 NULL,
   CONSTRAINT "PK_PtpFile"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."PLUGVESR"
(
 "PLUG_BIE" INT DEFAULT 0
 NULL,
 "PLUG_VESR" INT DEFAULT 0
 NULL
);

CREATE TABLE "SYSDBA"."PLUG"
(
 "PLUG_ID" INT IDENTITY(1,1) NOT NULL,
 "PLUG_NAME" VARCHAR(50) NULL,
 "PLUG_SITE" VARCHAR(50) NULL,
 "PLUG_HEIGHT" VARCHAR(50) NULL,
 "PLUG_WIDTH" VARCHAR(50) NULL,
 "PLUG_TARGETTYPE" VARCHAR(50) NULL,
 "PLUG_TARGET" VARCHAR(3900) NULL,
 "PLUG_DISPLAYNAME" VARCHAR(50) NULL,
 "PLUG_DESC" VARCHAR(3900) NULL,
 "PLUG_PARAM" VARCHAR(3900) NULL,
 "PLUG_IMAGE" VARCHAR(3900) NULL,
 "PLUG_ENABLED" BIT DEFAULT 1
 NOT NULL,
 "PLUG_INDEX" INT DEFAULT 0
 NULL,
 "PLUG_BIE" INT DEFAULT 0
 NULL,
   CONSTRAINT "PK_Plug"  CLUSTER PRIMARY KEY("PLUG_ID") ENABLE 
);

CREATE TABLE "SYSDBA"."OTHERFORM"
(
 "ID" SMALLINT NOT NULL,
 "PAWS" VARCHAR(20) NOT NULL,
 "SUPDATE" VARCHAR(50) NULL,
 "WEBNAME" VARCHAR(50) NULL,
 "WEBURL" VARCHAR(3900) NULL,
 "WEBRUN" INT DEFAULT 0
 NULL,
 "LOGO" INT DEFAULT 0
 NULL,
 "ONERUN" VARCHAR(50) NULL,
 "RUDATE" VARCHAR(50) NULL,
 "RUDATE1" VARCHAR(50) NULL,
 "RUDATE2" VARCHAR(50) NULL,
 "RUDATE3" VARCHAR(50) NULL,
 "LASTRUN" VARCHAR(50) NULL,
 "USERCOUNT" VARCHAR(50) NULL,
 "YESID" VARCHAR(50) NULL,
 "YESID1" VARCHAR(50) NULL,
 "YESID2" VARCHAR(50) NULL,
 "YESID3" VARCHAR(50) NULL,
 "UPDATETIME" VARCHAR(50) NULL,
 "USERAPPLY" INT DEFAULT 0
 NULL,
 "IPADDRESS" VARCHAR(50) NULL,
 "USER_ID" VARCHAR(3900) NULL,
 "WEBCODE" VARCHAR(3900) NULL,
 "WELCOME" VARCHAR(50) NULL
);

CREATE TABLE "SYSDBA"."ONLINEREVISEDFILE"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "MYID" VARCHAR(10) NULL,
 "USNAME" VARCHAR(50) NULL,
 "TYPEPATH" VARCHAR(255) NULL,
 "PCSIZE" VARCHAR(50) NULL,
 "TODATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "TOTIME" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "ONLINEID" INT NULL,
 "FILPATH" VARCHAR(200) NULL,
 "DESCRIPTION" VARCHAR(255) NULL,
 "CALLBACKJSON" VARCHAR(3900) NULL,
 "CREATORID" VARCHAR(50) NULL,
 "CREATORNAME" VARCHAR(200) NULL,
   CONSTRAINT "PK_OnlineRevisedFile"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."ONLINEHEAT"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "MYID" VARCHAR(50) NULL,
 "ONLINEID" INT NULL,
 "TODATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "TOTIME" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "ISTOP" INT DEFAULT 0
 NULL,
   CONSTRAINT "PK_OnlineHeat"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."ONLINEFORM"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "MYID" VARCHAR(20) NULL,
 "USERID" VARCHAR(20) NULL,
 "AUTHORITY" INT DEFAULT 0
 NULL,
 "ONLINEID" INT NULL,
 "TODATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "TOTIME" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "ISTOP" INT DEFAULT 0
 NULL,
   CONSTRAINT "PK_OnlineForm"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."ONLINEFILE"
(
 "ONLINEID" INT IDENTITY(1,1) NOT NULL,
 "MYID" VARCHAR(50) NULL,
 "USNAME" VARCHAR(50) NULL,
 "TYPEPATH" VARCHAR(255) NULL,
 "PCSIZE" VARCHAR(50) NULL,
 "TODATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "TOTIME" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "FILPATH" VARCHAR(200) NULL,
 "FORMFILETYPE" SMALLINT DEFAULT 7
 NULL,
 "AUTHORITY1" INT DEFAULT 0
 NULL,
 "AUTHORITY2" INT DEFAULT 0
 NULL,
 "ISTOP" INT DEFAULT 0
 NULL,
 "FILESTATE" INT DEFAULT 1
 NULL,
   CONSTRAINT "PK_OnlineFile"  CLUSTER PRIMARY KEY("ONLINEID") ENABLE 
);

CREATE TABLE "SYSDBA"."NOTICE_ACKS"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "MSG_ID" VARCHAR(255) NULL,
 "MYID" VARCHAR(20) NULL,
 "YOUID" VARCHAR(20) NULL,
 "ISACK1" INT DEFAULT 0
 NULL,
 "ISACK2" INT DEFAULT 0
 NULL,
   CONSTRAINT "PK_Notice_Acks"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."NEWS_RO"
(
 "MYID" VARCHAR(20) NULL,
 "USERID" VARCHAR(20) NULL
);

CREATE TABLE "SYSDBA"."NEWS_FORM"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "USERID" VARCHAR(20) NULL,
 "FCNAME" VARCHAR(50) NULL,
 "MOTIF" VARCHAR(120) NULL,
 "NCONTENT" VARCHAR(3900) NULL,
 "TEL" VARCHAR(50) NULL,
 "TODATE" TIMESTAMP(0) NULL,
 "TOTYPE" INT DEFAULT 1
 NULL,
 "LOOKOVER" SMALLINT DEFAULT 0
 NULL
);

CREATE TABLE "SYSDBA"."MYTEL_RO"
(
 "UPPERID" VARCHAR(20) NOT NULL,
 "TYPEID" VARCHAR(20) NOT NULL,
 "TYPENAME" VARCHAR(20) NULL,
   CONSTRAINT "PK_MyTel_Ro"  CLUSTER PRIMARY KEY("TYPEID") ENABLE 
);

CREATE TABLE "SYSDBA"."MYTEL_FORM"
(
 "UPPERID" VARCHAR(20) NOT NULL,
 "TELID" VARCHAR(50) NOT NULL,
 "TELNAME" VARCHAR(20) NOT NULL,
 "TELICO" SMALLINT NULL,
 "TEL1" VARCHAR(50) NULL,
 "TEL2" VARCHAR(50) NULL,
 "TEL3" VARCHAR(50) NULL,
 "EMAIL" VARCHAR(50) NULL,
 "REK" VARCHAR(255) NULL,
 "TODATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
   CONSTRAINT "PK_MyTel_Form"  CLUSTER PRIMARY KEY("TELID") ENABLE 
);

CREATE TABLE "SYSDBA"."MSG_ACKS"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "MSG_ID" VARCHAR(255) NULL,
 "CLOTID" VARCHAR(20) NULL,
 "MYID" VARCHAR(20) NULL,
 "YOUID" VARCHAR(20) NULL,
 "ISRECEIPT1" INT DEFAULT 0
 NULL,
 "ISRECEIPT2" INT DEFAULT 0
 NULL,
   CONSTRAINT "PK_Msg_Acks"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."MESSENG_TYPE"
(
 "TYPEID" INT IDENTITY(1,1) NOT NULL,
 "USERID1" VARCHAR(20) NOT NULL,
 "USERID2" VARCHAR(20) NOT NULL,
 "USERTEXT" VARCHAR(3900) NULL,
 "TO_IP" VARCHAR(20) NULL,
 "TO_DATE" TIMESTAMP(0) NULL,
 "TO_TYPE" INT DEFAULT 1
 NULL,
 "FONTINFO" VARCHAR(50) NULL,
   CONSTRAINT "PK_Messeng_Type"  CLUSTER PRIMARY KEY("TYPEID") ENABLE 
);

CREATE TABLE "SYSDBA"."MESSENG_TEXT"
(
 "TYPEID" INT IDENTITY(1,1) NOT NULL,
 "MSG_ID" VARCHAR(255) NULL,
 "MYID" VARCHAR(20) NULL,
 "YOUID" VARCHAR(20) NULL,
 "FCNAME" VARCHAR(20) NULL,
 "TO_TYPE" SMALLINT DEFAULT 1
 NULL,
 "ISRECEIPT" BIT DEFAULT 0
 NULL,
 "TO_DATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "TO_TIME" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "USERTEXT" VARCHAR(3900) NULL,
 "FONTINFO" VARCHAR(50) NULL,
 "ISRECEIPT1" INT DEFAULT 0
 NULL,
 "ISRECEIPT2" INT DEFAULT 0
 NULL,
 "ISACK1" INT DEFAULT 0
 NULL,
 "ISACK2" INT DEFAULT 0
 NULL,
 "ISACK3" INT DEFAULT 0
 NULL,
 "ISACK4" INT DEFAULT 0
 NULL,
 "ISACK5" INT DEFAULT 0
 NULL,
 "ISACK6" INT DEFAULT 0
 NULL,
 "ISACK7" INT DEFAULT 0
 NULL,
 "ISACK8" INT DEFAULT 0
 NULL,
   CONSTRAINT "PK_Messeng_Text"  CLUSTER PRIMARY KEY("TYPEID") ENABLE 
);

CREATE TABLE "SYSDBA"."MESSENGVERIFY_TYPE"
(
 "TYPEID" INT IDENTITY(1,1) NOT NULL,
 "USERID1" VARCHAR(20) NOT NULL,
 "CLOTID" VARCHAR(50) NULL,
 "USERID2" VARCHAR(20) NOT NULL,
 "USERTEXT" VARCHAR(3900) NULL,
 "TO_IP" VARCHAR(20) NULL,
 "TO_DATE" TIMESTAMP(0) NULL,
 "TO_TYPE1" INT DEFAULT 0
 NULL,
 "TO_TYPE2" INT DEFAULT 0
 NULL,
 "TO_TYPE3" INT DEFAULT 0
 NULL,
 "TO_TYPE4" INT DEFAULT 0
 NULL,
   CONSTRAINT "PK_MessengVerify_Type"  CLUSTER PRIMARY KEY("TYPEID") ENABLE 
);

CREATE TABLE "SYSDBA"."MESSENGVERIFY_BLACKLIST"
(
 "TYPEID" INT IDENTITY(1,1) NOT NULL,
 "MYID" VARCHAR(20) NOT NULL,
 "YOUID" VARCHAR(20) NOT NULL,
 "TO_IP" VARCHAR(20) NULL,
 "TO_DATE" TIMESTAMP(0) NULL,
 "TO_TYPE" INT DEFAULT 0
 NULL,
   CONSTRAINT "PK_MessengVerify_Blacklist"  CLUSTER PRIMARY KEY("TYPEID") ENABLE 
);

CREATE TABLE "SYSDBA"."MESSENGTEL_TEXT"
(
 "TYPEID" INT IDENTITY(1,1) NOT NULL,
 "MYID" VARCHAR(20) NULL,
 "TELETE" VARCHAR(20) NULL,
 "FCNAME" VARCHAR(20) NULL,
 "TO_TYPE" SMALLINT DEFAULT 1
 NULL,
 "TO_DATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "TO_TIME" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "USERTEXT" VARCHAR(3900) NULL,
   CONSTRAINT "PK_MessengTel_Text"  CLUSTER PRIMARY KEY("TYPEID") ENABLE 
);

CREATE TABLE "SYSDBA"."MESSENGNOTICE_TEXT"
(
 "TYPEID" INT IDENTITY(1,1) NOT NULL,
 "MSG_ID" VARCHAR(255) NULL,
 "MYID" VARCHAR(50) NULL,
 "YOUID" VARCHAR(50) NULL,
 "NTITLE" VARCHAR(50) NULL,
 "NCONTENT" VARCHAR(3900) NULL,
 "NLINK" VARCHAR(3900) NULL,
 "TO_IP" VARCHAR(50) NULL,
 "TO_DATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
   CONSTRAINT "PK_MessengNotice_Type"  CLUSTER PRIMARY KEY("TYPEID") ENABLE 
);

CREATE TABLE "SYSDBA"."MESSENGKEFU_TYPE"
(
 "TYPEID" INT IDENTITY(1,1) NOT NULL,
 "USERID1" VARCHAR(20) NOT NULL,
 "USERID2" VARCHAR(20) NOT NULL,
 "FCNAME" VARCHAR(50) NULL,
 "USERTEXT" VARCHAR(3900) NULL,
 "TO_IP" VARCHAR(20) NULL,
 "TO_DATE" TIMESTAMP(0) NULL,
 "TO_TYPE" INT DEFAULT 1
 NULL,
   CONSTRAINT "PK_MessengKefu_Type"  CLUSTER PRIMARY KEY("TYPEID") ENABLE 
);

CREATE TABLE "SYSDBA"."MESSENGKEFU_TEXT"
(
 "TYPEID" INT IDENTITY(1,1) NOT NULL,
 "MSG_ID" VARCHAR(255) NULL,
 "MYID" VARCHAR(20) NULL,
 "YOUID" VARCHAR(20) NULL,
 "FCNAME" VARCHAR(20) NULL,
 "CHATID" INT NULL,
 "TO_TYPE" SMALLINT DEFAULT 1
 NULL,
 "ISRECEIPT" INT DEFAULT 0
 NULL,
 "TO_DATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "TO_TIME" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "USERTEXT" VARCHAR(3900) NULL,
 "FONTINFO" VARCHAR(50) NULL,
 "ISRECEIPT1" INT DEFAULT 0
 NULL,
 "ISRECEIPT2" INT DEFAULT 0
 NULL,
 "ISACK1" INT DEFAULT 0
 NULL,
 "ISACK2" INT DEFAULT 0
 NULL,
 "ISACK3" INT DEFAULT 0
 NULL,
 "ISACK4" INT DEFAULT 0
 NULL,
 "ISACK5" INT DEFAULT 0
 NULL,
 "ISACK6" INT DEFAULT 0
 NULL,
 "ISACK7" INT DEFAULT 0
 NULL,
 "ISACK8" INT DEFAULT 0
 NULL,
   CONSTRAINT "PK_MessengKefu_Text"  CLUSTER PRIMARY KEY("TYPEID") ENABLE 
);

CREATE TABLE "SYSDBA"."MESSENGCLOT_TYPE"
(
 "TYPEID" INT IDENTITY(1,1) NOT NULL,
 "USERID1" VARCHAR(20) NOT NULL,
 "CLOTID" VARCHAR(50) NULL,
 "USERID2" VARCHAR(20) NOT NULL,
 "USERTEXT" VARCHAR(3900) NULL,
 "TO_IP" VARCHAR(20) NULL,
 "TO_DATE" TIMESTAMP(0) NULL,
 "TO_TYPE" INT DEFAULT 1
 NULL,
 "FONTINFO" VARCHAR(50) NULL,
   CONSTRAINT "PK_MessengClot_Type"  CLUSTER PRIMARY KEY("TYPEID") ENABLE 
);

CREATE TABLE "SYSDBA"."MESSENGCLOT_TEXT"
(
 "TYPEID" INT IDENTITY(1,1) NOT NULL,
 "MSG_ID" VARCHAR(255) NULL,
 "CLOTID" VARCHAR(20) NULL,
 "MYID" VARCHAR(20) NULL,
 "YOUID" VARCHAR(20) NULL,
 "FCNAME" VARCHAR(20) NULL,
 "TO_TYPE" SMALLINT DEFAULT 1
 NULL,
 "TO_DATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "TO_TIME" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "USERTEXT" VARCHAR(3900) NULL,
 "FONTINFO" VARCHAR(50) NULL,
   CONSTRAINT "PK_MessengClot_Text"  CLUSTER PRIMARY KEY("TYPEID") ENABLE 
);

CREATE TABLE "SYSDBA"."MD5FILE"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "MYID" VARCHAR(10) NULL,
 "FORMFILETYPE" SMALLINT DEFAULT 0
 NULL,
 "TYPEPATH" VARCHAR(255) NULL,
 "PCSIZE" VARCHAR(50) NULL,
 "TODATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "TOTIME" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "FILPATH" VARCHAR(200) NULL,
 "MD5HASH" VARCHAR(200) NULL,
   CONSTRAINT "PK_MD5File"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."LV_USER_RO"
(
 "TYPEID" INT IDENTITY(1,1) NOT NULL,
 "TYPENAME" VARCHAR(50) NULL,
 "DESCRIPTION" VARCHAR(500) NULL,
 "STATUS" INT DEFAULT 0
 NULL,
 "ORD" INT DEFAULT 0
 NULL,
 "CREATETIME" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
   CONSTRAINT "PK_lv_user_ro"  CLUSTER PRIMARY KEY("TYPEID") ENABLE 
);

CREATE TABLE "SYSDBA"."LV_USER_FORM"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "USERID" VARCHAR(50) NULL,
 "LOGINNAME" VARCHAR(50) NULL,
 "USERNAME" VARCHAR(50) NULL,
 "TYPEID" INT NULL,
   CONSTRAINT "PK_lv_user_form"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."LV_USER"
(
 "USERID" VARCHAR(50) DEFAULT 0
 NOT NULL,
 "USERNAME" VARCHAR(50) NULL,
 "EMAIL" VARCHAR(50) NULL,
 "PHONE" VARCHAR(50) NULL,
 "QQ" VARCHAR(50) NULL,
 "WECHAT" VARCHAR(50) NULL,
 "REMARKS" VARCHAR(500) NULL,
 "REGTIME" TIMESTAMP(0) DEFAULT GETDATE()
 NOT NULL,
 "IP" VARCHAR(50) NULL,
 "AREA" VARCHAR(50) NULL,
 "CHATCOUNT" INT DEFAULT 0
 NULL,
 "LASTTIME" TIMESTAMP(0) NULL,
   CONSTRAINT "PK_lv_user"  CLUSTER PRIMARY KEY("USERID") ENABLE 
);

CREATE TABLE "SYSDBA"."LV_TRACK"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "SOURCEID" VARCHAR(50) NULL,
 "CHATID" VARCHAR(50) NULL,
 "GROUPID" INT DEFAULT 0
 NULL,
 "CHATER" VARCHAR(50) NULL,
 "USERID" VARCHAR(50) NULL,
 "USERNAME" VARCHAR(50) NULL,
 "TRACKURL" VARCHAR(500) NULL,
 "FLAG" INT DEFAULT 0
 NULL,
 "INTIME" TIMESTAMP(0) DEFAULT GETDATE()
 NOT NULL,
 "ORD" INT DEFAULT 0
 NULL,
   CONSTRAINT "PK_lv_track"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."LV_SOURCE"
(
 "SOURCEID" INT IDENTITY(1,1) NOT NULL,
 "CHATID" VARCHAR(50) NULL,
 "GROUPID" INT DEFAULT 0
 NULL,
 "CHATER" VARCHAR(50) NULL,
 "USERID" VARCHAR(50) NULL,
 "USERNAME" VARCHAR(50) NULL,
 "SOURCEURL" VARCHAR(500) NULL,
 "LAUNCHURL" VARCHAR(500) NULL,
 "KEYWORD" VARCHAR(255) NULL,
 "FLAG" INT DEFAULT 0
 NULL,
 "IP" VARCHAR(50) NULL,
 "AREA" VARCHAR(50) NULL,
 "BROWSER" VARCHAR(50) NULL,
 "INTIME" TIMESTAMP(0) DEFAULT GETDATE()
 NOT NULL,
 "ORD" INT DEFAULT 0
 NULL,
   CONSTRAINT "PK_lv_source"  CLUSTER PRIMARY KEY("SOURCEID") ENABLE 
);

CREATE TABLE "SYSDBA"."LV_QUICKTALK"
(
 "TALKID" INT DEFAULT 0
 NOT NULL,
 "CHATER" VARCHAR(50) NULL,
 "SUBJECT" VARCHAR(255) NULL,
 "USERTEXT" VARCHAR(3900) NULL,
 "TO_TYPE" SMALLINT DEFAULT 0
 NULL,
 "STATUS" INT DEFAULT 0
 NULL,
 "ORD" INT DEFAULT 0
 NULL,
 "CREATETIME" TIMESTAMP(0) DEFAULT GETDATE()
 NOT NULL,
   CONSTRAINT "PK_lv_quick_talk"  CLUSTER PRIMARY KEY("TALKID") ENABLE 
);

CREATE TABLE "SYSDBA"."LV_QUESTION"
(
 "QUESTIONID" INT DEFAULT 0
 NOT NULL,
 "CHATER" VARCHAR(50) NULL,
 "SUBJECT" VARCHAR(255) NULL,
 "USERTEXT" VARCHAR(3900) NULL,
 "TO_TYPE" SMALLINT DEFAULT 0
 NULL,
 "STATUS" INT DEFAULT 0
 NULL,
 "ORD" INT DEFAULT 0
 NULL,
 "CREATETIME" TIMESTAMP(0) DEFAULT GETDATE()
 NOT NULL,
   CONSTRAINT "PK_lv_question"  CLUSTER PRIMARY KEY("QUESTIONID") ENABLE 
);

CREATE TABLE "SYSDBA"."LV_MESSAGE"
(
 "ID" INT DEFAULT 0
 NOT NULL,
 "USERID" VARCHAR(50) DEFAULT 0
 NULL,
 "USERNAME" VARCHAR(50) NULL,
 "EMAIL" VARCHAR(50) NULL,
 "PHONE" VARCHAR(50) NULL,
 "IP" VARCHAR(50) NULL,
 "USERTEXT" VARCHAR(1024) NULL,
 "CREATETIME" TIMESTAMP(0) DEFAULT GETDATE()
 NOT NULL,
   CONSTRAINT "PK_lv_message"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."LV_LINK"
(
 "LINKID" INT DEFAULT 0
 NOT NULL,
 "CHATER" VARCHAR(50) NULL,
 "LINKNAME" VARCHAR(255) NULL,
 "LINKURL" VARCHAR(255) NULL,
 "LINKTYPE" INT DEFAULT 0
 NULL,
 "ORD" INT DEFAULT 0
 NULL,
 "CREATETIME" TIMESTAMP(0) DEFAULT GETDATE()
 NOT NULL,
   CONSTRAINT "PK_lv_link"  CLUSTER PRIMARY KEY("LINKID") ENABLE 
);

CREATE TABLE "SYSDBA"."LV_FILE"
(
 "FILEID" INT DEFAULT 0
 NOT NULL,
 "CHATID" VARCHAR(50) NULL,
 "GROUPID" INT DEFAULT 0
 NULL,
 "CHATER" VARCHAR(50) NULL,
 "USERNAME" VARCHAR(50) NULL,
 "FILENAME" VARCHAR(255) NULL,
 "FILESIZE" INT DEFAULT 0
 NULL,
 "FILEPATH" VARCHAR(255) NULL,
 "FLAG" INT DEFAULT 0
 NULL,
 "CREATEUSER" VARCHAR(255) NULL,
 "CREATETIME" TIMESTAMP(0) DEFAULT GETDATE()
 NOT NULL,
 "ORD" INT DEFAULT 0
 NULL,
   CONSTRAINT "PK_lv_file"  CLUSTER PRIMARY KEY("FILEID") ENABLE 
);

CREATE TABLE "SYSDBA"."LV_CHATER_RO"
(
 "TYPEID" INT IDENTITY(1,1) NOT NULL,
 "TYPENAME" VARCHAR(50) NULL,
 "DESCRIPTION" VARCHAR(500) NULL,
 "STATUS" INT DEFAULT 0
 NULL,
 "ORD" INT DEFAULT 0
 NULL,
 "CREATETIME" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
   CONSTRAINT "PK_lv_chater_ro"  CLUSTER PRIMARY KEY("TYPEID") ENABLE 
);

CREATE TABLE "SYSDBA"."LV_CHATER_FORM"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "USERID" VARCHAR(50) NULL,
 "LOGINNAME" VARCHAR(50) NULL,
 "USERNAME" VARCHAR(50) NULL,
 "TYPEID" INT NULL,
   CONSTRAINT "PK_lv_chater_form"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."LV_CHATER"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "USERID" INT DEFAULT 0
 NOT NULL,
 "LOGINNAME" VARCHAR(50) NULL,
 "USERNAME" VARCHAR(50) NULL,
 "DEPTNAME" VARCHAR(50) NULL,
 "JOBTITLE" VARCHAR(50) NULL,
 "EMAIL" VARCHAR(50) NULL,
 "PHONE" VARCHAR(50) NULL,
 "MOBILE" VARCHAR(50) NULL,
 "PICTURE" VARCHAR(100) NULL,
 "STATUS" INT DEFAULT 0
 NULL,
 "WELCOME" VARCHAR(500) NULL,
 "RECEPTION" INT DEFAULT 1
 NULL,
 "FREETIME" INT DEFAULT 0
 NULL,
 "ORD" INT DEFAULT 0
 NULL,
   CONSTRAINT "PK_lv_chater"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."LV_CHAT"
(
 "CHATID" INT NOT NULL,
 "GROUPID" INT DEFAULT 0
 NULL,
 "CHATER" VARCHAR(50) NULL,
 "USERID" VARCHAR(50) DEFAULT 0
 NULL,
 "USERNAME" VARCHAR(50) NULL,
 "IP" VARCHAR(50) NULL,
 "AREA" VARCHAR(50) NULL,
 "INTIME" TIMESTAMP(0) NULL,
 "CONNECTTIME" TIMESTAMP(0) DEFAULT GETDATE()
 NOT NULL,
 "OUTTIME" TIMESTAMP(0) NULL,
 "STATUS" INT DEFAULT 0
 NULL,
 "CLOSEROLE" INT DEFAULT 0
 NULL,
 "RATE" INT DEFAULT 0
 NULL,
 "RATENOTE" VARCHAR(500) NULL,
 "ALLOWUPLOADFILE" INT DEFAULT 0
 NULL,
 "NCONTENT" VARCHAR(500) NULL,
 "ORD" INT DEFAULT 0
 NULL,
   CONSTRAINT "PK_lv_chat"  CLUSTER PRIMARY KEY("CHATID") ENABLE 
);

CREATE TABLE "SYSDBA"."LEAVEFILE"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "MSG_ID" VARCHAR(255) NULL,
 "USERID1" VARCHAR(10) NULL,
 "USERID2" VARCHAR(50) NULL,
 "TYPEPATH" VARCHAR(255) NULL,
 "PCSIZE" VARCHAR(50) NULL,
 "TODATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "SENDTY" BIT NOT NULL,
 "FILPATH" VARCHAR(200) NULL,
 "ONLINEID" INT DEFAULT 0
 NULL,
   CONSTRAINT "PK_LeaveFile"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."KEFUCONFIG"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "IPADDRESS" VARCHAR(50) NULL,
 "USER_ID" VARCHAR(3900) NULL,
 "WEBCODE" VARCHAR(3900) NULL,
 "WELCOME" VARCHAR(200) NULL,
   CONSTRAINT "PK_KefuConfig"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."KEFU"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "IP" VARCHAR(50) NULL,
 "CITY" VARCHAR(50) NULL,
   CONSTRAINT "PK_Kefu"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."JSDL2"
(
 "ID" INT DEFAULT 0
 NULL,
 "MOBILE" VARCHAR(15) NOT NULL,
 "CONTENT" VARCHAR(255) NOT NULL,
 "STATUS" INT NOT NULL
);

CREATE TABLE "SYSDBA"."JSDL"
(
 "ID" INT NOT NULL,
 "MOBILE" VARCHAR(15) NOT NULL,
 "CONTENT" VARCHAR(255) NOT NULL,
 "RECETIME" TIMESTAMP(0) NOT NULL
);

CREATE TABLE "SYSDBA"."JOD"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "TYPENAME" VARCHAR(50) NULL,
   CONSTRAINT "PK_jod"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."HEAT_FORM"
(
 "USERID" VARCHAR(20) NOT NULL,
 "TYPE" INT NULL,
 "LOCOUN" VARCHAR(5) NULL,
 "FCNAME" VARCHAR(50) NULL,
   CONSTRAINT "PK_Heat_Form"  CLUSTER PRIMARY KEY("USERID") ENABLE 
);

CREATE TABLE "SYSDBA"."FONTFORM1"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "FONTNAME" VARCHAR(50) NULL,
 "FONTSIZE" INT DEFAULT 0
 NULL,
 "FONTCOLRO" VARCHAR(20) NULL,
 "BOLD" BIT NOT NULL,
 "UNDERLINE" BIT NOT NULL,
 "ITALIC" BIT NOT NULL,
   CONSTRAINT "PK_FontForm1"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."FONTFORM"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "FONTNAME" VARCHAR(50) NULL,
 "FONTSIZE" INT DEFAULT 0
 NULL,
 "FONTCOLRO" VARCHAR(20) NULL,
 "BOLD" BIT NOT NULL,
 "UNDERLINE" BIT NOT NULL,
 "ITALIC" BIT NOT NULL,
   CONSTRAINT "PK_FontForm"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."FAV_FORM"
(
 "UPPERID" VARCHAR(20) DEFAULT 1
 NOT NULL,
 "USERID" VARCHAR(20) NOT NULL,
 "MYID" VARCHAR(50) NULL
);

CREATE TABLE "SYSDBA"."DOWNLOAD"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "MYID" VARCHAR(10) NULL,
 "TYPEPATH" VARCHAR(255) NULL,
 "PCSIZE" VARCHAR(50) NULL,
 "USNAME" VARCHAR(50) NULL,
 "USID" VARCHAR(20) NULL,
 "TYPES" INT DEFAULT 1
 NULL,
 "TODATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "TOTIME" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
   CONSTRAINT "PK_DownLoad"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."DFSDL"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "MOBILE" VARCHAR(15) NOT NULL,
 "NCONTENT" VARCHAR(255) NOT NULL,
 "DEADTIME" TIMESTAMP(0) NOT NULL,
 "STATUS" INT NOT NULL,
 "MSGID" SMALLINT NULL,
 "IMUSERID" VARCHAR(20) NULL
);

CREATE TABLE "SYSDBA"."COL_RO"
(
 "TYPEID" INT IDENTITY(1,1) NOT NULL,
 "TYPENAME" VARCHAR(200) NULL,
 "TODATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "TOTIME" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "MYID" VARCHAR(50) NULL,
   CONSTRAINT "PK_Col_Ro"  CLUSTER PRIMARY KEY("TYPEID") ENABLE 
);

CREATE TABLE "SYSDBA"."COL_FORM"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "UPPERID" INT NOT NULL,
 "TITLE" VARCHAR(50) NULL,
 "NCONTENT" VARCHAR(3900) NULL,
 "USNAME" VARCHAR(50) NULL,
 "USID" VARCHAR(20) NULL,
 "TYPES" VARCHAR(255) NULL,
 "TODATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "TOTIME" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "MYID" VARCHAR(50) NULL,
   CONSTRAINT "PK_Col_Form"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."CLOT_SILENCE"
(
 "TYPEID" INT IDENTITY(1,1) NOT NULL,
 "MYID" VARCHAR(20) NOT NULL,
 "YOUID" VARCHAR(20) NOT NULL,
 "TO_IP" VARCHAR(20) NULL,
 "TO_DATE" TIMESTAMP(0) NULL,
 "TO_TYPE" INT DEFAULT 0
 NULL,
   CONSTRAINT "PK_Clot_Silence"  CLUSTER PRIMARY KEY("TYPEID") ENABLE 
);

CREATE TABLE "SYSDBA"."CLOT_RO"
(
 "TYPEID" VARCHAR(20) NOT NULL,
 "TYPENAME" VARCHAR(200) NULL,
 "REMARK" VARCHAR(3900) NULL,
 "TO_DATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "SENDER" INT DEFAULT 0
 NULL,
 "USERSTATE" INT DEFAULT 0
 NULL,
 "DISK_SPACE" VARCHAR(50) DEFAULT 1024
 NULL,
 "ISPUBLIC" INT DEFAULT 0
 NULL,
 "OWNERID" VARCHAR(50) DEFAULT 1
 NULL,
 "ITEMINDEX" VARCHAR(50) DEFAULT 0
 NULL,
 "CREATORID" VARCHAR(50) DEFAULT 1
 NULL,
 "CREATORNAME" VARCHAR(200) DEFAULT 'admin'
 NULL,
 "USERS_IDVESR" INT DEFAULT 0
 NULL,
 "USERS_FORMVESR" INT DEFAULT 0
 NULL,
   CONSTRAINT "PK_Clot_Ro"  CLUSTER PRIMARY KEY("TYPEID") ENABLE 
);

CREATE TABLE "SYSDBA"."CLOT_PIC"
(
 "CLOTID" VARCHAR(20) NOT NULL,
 "CLOTINFO" INT DEFAULT 0
 NULL,
 "PIC" INT DEFAULT 0
 NULL,
 "SFILE" INT DEFAULT 0
 NULL,
   CONSTRAINT "PK_Clot_Pic"  CLUSTER PRIMARY KEY("CLOTID") ENABLE 
);

CREATE TABLE "SYSDBA"."CLOT_FORM"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "UPPERID" VARCHAR(20) NOT NULL,
 "USERID" VARCHAR(20) NOT NULL,
 "ISADMIN" SMALLINT NULL,
 "REMARK" VARCHAR(255) NULL,
 "LAST_ACK_TYPEID1" INT DEFAULT 0
 NULL,
 "LAST_ACK_TYPEID2" INT DEFAULT 0
 NULL,
 "LAST_ACK_TYPEID3" INT DEFAULT 0
 NULL,
 "LAST_ACK_TYPEID4" INT DEFAULT 0
 NULL,
 "LAST_ACK_TYPEID5" INT DEFAULT 0
 NULL,
 "LAST_ACK_TYPEID6" INT DEFAULT 0
 NULL,
 "LAST_ACK_TYPEID7" INT DEFAULT 0
 NULL,
 "LAST_ACK_TYPEID8" INT DEFAULT 0
 NULL,
   CONSTRAINT "PK_Clot_Form"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."CLOTFILE"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "MSG_ID" VARCHAR(255) NULL,
 "MYID" VARCHAR(10) NULL,
 "USNAME" VARCHAR(50) NULL,
 "CLOTID" VARCHAR(50) NULL,
 "TYPEPATH" VARCHAR(255) NULL,
 "PCSIZE" VARCHAR(50) NULL,
 "TODATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "TOTIME" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "FILPATH" VARCHAR(200) NULL,
 "ONLINEID" INT DEFAULT 0
 NULL,
 "FILESTATE" INT DEFAULT 1
 NULL,
   CONSTRAINT "PK_ClotFile"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "SYSDBA"."BOARD_VISITER"
(
 "COL_ID" INT IDENTITY(1,1) NOT NULL,
 "COL_BOARDID" VARCHAR(50) NULL,
 "COL_HSITEM" VARCHAR(50) NULL,
 "COL_HSITEM_NAME" VARCHAR(50) NULL,
 "COL_DT_CREATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "COL_READED" INT DEFAULT 0
 NULL,
 "COL_DT_READED" TIMESTAMP(0) NULL,
 "COL_HSITEM_ID" INT DEFAULT 0
 NULL,
   CONSTRAINT "PK_Board_Visiter"  CLUSTER PRIMARY KEY("COL_ID") ENABLE 
);

CREATE TABLE "SYSDBA"."BOARD_REVERT"
(
 "COL_ID" INT IDENTITY(1,1) NOT NULL,
 "COL_BOARDID" VARCHAR(50) NULL,
 "COL_CONTENT" TEXT NULL,
 "COL_CREATOR_ID" INT NOT NULL,
 "COL_CREATOR_NAME" VARCHAR(50) NULL,
 "COL_CREATOR" VARCHAR(50) NULL,
 "COL_EXPRESSION" VARCHAR(200) NULL,
 "COL_DT_CREATE" TIMESTAMP(0) NOT NULL
);

CREATE TABLE "SYSDBA"."BOARD_CATALOG"
(
 "COL_ID" INT IDENTITY(1,1) NOT NULL,
 "COL_NAME" VARCHAR(50) NULL,
 "COL_DESC" TEXT NULL,
 "COL_ORDER" INT NULL,
 "COL_COMPANYID" INT NULL
);

CREATE TABLE "SYSDBA"."BOARD_ATTACH"
(
 "COL_ID" INT IDENTITY(1,1) NOT NULL,
 "COL_BOARDID" VARCHAR(50) NULL,
 "COL_FILESIZE" INT NULL,
 "COL_FILEPATH" VARCHAR(255) NULL,
 "COL_FILENAME" VARCHAR(255) NULL,
 "COL_DT_CREATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "COL_DT_MODIFY" TIMESTAMP(0) NULL,
   CONSTRAINT "PK_Board_Attach"  CLUSTER PRIMARY KEY("COL_ID") ENABLE 
);

CREATE TABLE "SYSDBA"."BOARD"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "COL_ID" VARCHAR(50) NULL,
 "COL_CREATOR_ID" INT DEFAULT 0
 NULL,
 "COL_CREATOR_NAME" VARCHAR(50) NULL,
 "COL_MODIFYER_ID" INT DEFAULT 0
 NULL,
 "COL_DT_MODIFY" TIMESTAMP(0) NULL,
 "COL_SUBJECT" VARCHAR(200) NULL,
 "COL_CONTENT" TEXT NULL,
 "COL_ATTACHMENTCOUNT" INT DEFAULT 0
 NULL,
 "COL_CLICKCOUNT" INT DEFAULT 0
 NULL,
 "COL_DT_CREATE" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "COL_ORDER" INT DEFAULT 0
 NULL,
 "COL_G_CLASSID" INT DEFAULT 0
 NULL,
 "COL_G_OBJID" INT DEFAULT 0
 NULL,
 "COL_ISPUBLIC" INT DEFAULT 0
 NULL,
 "COL_CREATOR" VARCHAR(64) NULL,
 "COL_SENDERIP" VARCHAR(50) NULL,
 "COL_SENDERMAC" VARCHAR(50) NULL,
 "COL_CONTENTTYPE" VARCHAR(50) NULL,
 "COL_DATAPATH" VARCHAR(3900) NULL,
 "COL_COMPANYID" INT DEFAULT 0
 NULL,
 "COL_CREATOR_DEPT" VARCHAR(100) NULL,
 "COL_CREATOR_DEPTID" INT DEFAULT 0
 NULL
);

CREATE TABLE "SYSDBA"."ADMINGRANT"
(
 "ID" INT IDENTITY(1,1) NOT NULL,
 "USERID" VARCHAR(50) NULL,
 "FCNAME" VARCHAR(200) NULL,
 "UPPEID" VARCHAR(200) NULL,
 "DEPTNAME" VARCHAR(3900) NULL,
 "COUNTUSER" INT DEFAULT 0
 NULL,
 "CREATORID" VARCHAR(50) NULL,
 "CREATORNAME" VARCHAR(200) NULL,
 "CREATETIME" TIMESTAMP(0) DEFAULT GETDATE()
 NULL,
 "STATUS" INT DEFAULT 1
 NULL,
   CONSTRAINT "PK_Grant"  CLUSTER PRIMARY KEY("ID") ENABLE 
);

ALTER TABLE "SYSDBA"."BOARD" ADD CONSTRAINT "PK_Board" PRIMARY KEY("ID") ;

