<?php
return array(
	'sample' => '例',
	'url' => '地址',
	'attach' => '附件',
	'attach_size' => '大小',
	'download' => '下载',
	'msg_file_error'  => '消息文件被删除' ,
	'file_error'  => '文件不存在' ,
	'no_power'=>'没有权限',
	'index_service' => '在线客服',
		
	'msg_file_error'  => '消息文件被删除' ,
	'msg_recv_pic'  => '收到新图片文件' ,
	'msg_recv_sound'  => '收到新语音文件' ,
	'msg_recv_attach'  => '收到新附件' ,
	'msg_recv_chatgpt'  => '[小触机器人已回复]' ,
	'msg_recv_chatgpt1'  => '小触机器人未开启,请联系管理员!' ,
	'msg_recv_chatgpt2'  => '小触机器人API Key不能为空,请联系管理员!' ,
	'msg_recv_chatgpt12'  => '小触机器人Secret Key不能为空,请联系管理员!' ,
	'msg_recv_chatgpt13'  => '小触机器人API地址不能为空,请联系管理员!' ,
	'msg_recv_chatgpt3'  => 'API-KEY不合法!' ,
	'msg_recv_chatgpt4'  => '问题和上下文长度超限，请重新提问!' ,
	'msg_recv_chatgpt5'  => '同时访问用户过多，请稍后再试!' ,
	'msg_recv_chatgpt6'  => '违规使用，API-KEY被封禁!' ,
	'msg_recv_chatgpt7'  => '未提供API-KEY!' ,
	'msg_recv_chatgpt8'  => 'API-KEY余额不足!' ,
	'msg_recv_chatgpt9'  => '账户已禁用!' ,
	'msg_recv_chatgpt10'  => 'OpenAI模型超负荷，请重新发起请求!' ,
	'msg_recv_chatgpt11'  => 'OpenAI服务器故障，错误类型：{errcode}' ,
	'msg_recv_rate_limit_reached'  => '访问频率超限' ,
	'msg_recv_access_terminated'  => '违规使用,被封禁' ,
	'msg_recv_no_api_key'  => '未提供API-KEY' ,
	'msg_recv_insufficient_quota'  => 'API-KEY余额不足' ,
	'msg_recv_model_overloaded'  => 'OpenAI服务器超负荷' ,
	
	'viewport_org'  => '组织结构',
	'doc_manager_public' => '公共文档',
	'customer_service_list'  => '客服列表',
	
    'valid_file_type_error' => '文件类型不正确',
	'valid_file_not_exist' => '文件不存在',
	'valid_upload_size_limit' => '上传文件不能超过[{FileSize}M]',
	'valid_local_limit' => '只能在服务器上操作',
	
	'error_db_connect_error' => '连接失败!如果使用软件内置数据库请等待所有弹出的插件安装好再来配置数据库;如果使用服务器已安装的数据库请检查数据库信息是否正确.',
	
	'sn_path_error' => '配置的服务器路径错误',
	'sn_activation_error' => '激活码错误',
	'sn_machine_error' => '激活码错误[机器码不符]',
	'ad_connect_fail' => 'AD服务器连接失败',
	
	'module_doc_manager' => '共享文档',
		
	'grant_exist' => '用户已经授权过此部门',
    'grant_beyond' => '超出授权人数',      
	
	'file' => '文件',
	'folder' => '文件夹',
	'cloud_isexists' => '已经存在！',
	'cloud_authority_error' => '你没有权限下载',   
	'cloud_download' => '下载云盘文件',
	'cloud_download_leavefile' => '下载离线文件',
	'cloud_download_onlinefile' => '下载在线文件',
	'cloud_delete_leavefile' => '删除离线文件',
	'cloud_delete_clotfile' => '删除群组文件',
	'cloud_delete_onlinefile' => '删除在线文档',
	'cloud_file' => '云盘文件',
	'cloud_clotfile' => '群组文件',
	'cloud_error' => '请不要在根目录上传',
	'cloud_error1' => '请等待管理员通过审核', 
	'cloud_error2' => '你没有权限修改', 
	'cloud_error3' => '你没有权限删除', 
	'cloud_error4' => '你没有权限管理', 
	'cloud_error5' => '保存成功，请等待管理员通过审核!', 
	'cloud_error6' => '数据不存在',
	'cloud_error7' => '你没有权限创建',
	'cloud_error8' => '已经存在',
	'cloud_error9' => '此文件夹没有文件',
	'cloud_error10' => '存在非法字符', 
	'cloud_revisedfile1' => '将文档恢复到第',
	'cloud_revisedfile2' => '版',
	'cloud_create_folder' => '创建文件夹',
	'cloud_warning' => '修改共享成员为',
	'cloud_warning1' => '文件共享',
	'cloud_warning2' => '退出共享',
	'cloud_warning3' => '添加共享成员',
	'cloud_warning4' => '删除共享成员',
	'cloud_warning5' => '下载多个云盘文件',
	'cloud_warning6' => '下载多个离线文件',
	'cloud_warning7' => '目前有',
	'cloud_warning8' => 'M,打包文件大小限制为',
	'cloud_warning9' => '个文件,打包文件数限制为',
	'cloud_warning10' => '个',
	'cloud_warning11' => '文件共享有更新，赶紧去看看新增了哪些好内容把！',
	'cloud_warning12' => '您已成为',
	'cloud_warning13' => '文件共享的一员，赶紧去看看有什么好的内容把！',
	'cloud_warning14' => '您已被移出了该文件共享！',
	'cloud_warning15' => '退出了文件共享！',
	'cloud_warning16' => '上传了文件，请您通过审核！',
	'cloud_warning17' => '请先删除子节点!',
	'cloud_warning18' => '文件重复部分文件移动失败!',
	
	'docdir_error' => '非法路径',
	'docdir_error1' => '路径错误',
	
	'fun_error' => '非法登录',
	'fun_error1' => '需重新登录',
	
	'import_export_start_time' => '开始导入时间',
	'import_export_end_time' => '开始导入时间',
	'import_export_warning' => 'AD服务器连接失败',
	'import_export_warning1' => '进来了',
	'import_export_warning2' => '没有数据',
	'import_export_warning3' => '格式不正确',
	
	'install_warning' => '安装完毕',
	
	'role_warning' => '通过一键创建的角色。',
	
	'class_site_warning' => '只能在服务器上操作,请打开',
	'class_site_warning1' => '如果打开页面空白,请使用高版本浏览器!',
	'class_thumbHandler_warning' => '图片不存在',
	'class_thumbHandler_warning1' => '图片源为空',
	'class_thumbHandler_warning2' => '字体文件不存在',
	'class_thumbHandler_warning3' => '图片缩放比例不得小于1',
	'class_thumbHandler_warning4' => '目标宽度不能为0',
	'class_thumbHandler_warning5' => '目标高度不能为0',
	'class_thumbHandler_warning6' => '水印文字过大',
	'class_thumbHandler_warning7' => '水印图片为空',
	'class_thumbHandler_warning8' => '图片边框过大，已超过了图片的宽度',
	'class_thumbHandler_warning9' => '水印图片尺寸大于原图，请缩小水印图',
	'class_thumbHandler_warning10' => '文件不存在,不能取得文件类型!',
	'class_thumbHandler_warning11' => '水印图片为空',
	
	'class_doc_warning' => '目录',
	'class_doc_warning1' => '不存在',
	'class_doc_warning2' => '上传云盘文件',
	'class_doc_warning3' => '删除云盘文件',
	'class_doc_warning4' => '将',
	'class_doc_warning5' => '存入云盘',
	'class_doc_warning6' => '个人文档',
	'class_doc_warning7' => '文件名包含特殊字符',
	'class_doc_warning8' => '不能上传特殊文件',
	'class_doc_warning9' => '文件夹名称包含特殊字符',
	'class_doc_warning10' => '文件上传失败',
	'class_doc_warning11' => '上传并覆盖同名云盘文件',
	'class_doc_warning12' => '上传文件',
	'class_doc_warning13' => '失败，原因文件太大',
	'class_doc_warning14' => '失败，原因目录',
	'class_doc_warning15' => '失败，原因不能上传特殊文件',
	'class_doc_warning16' => '删除云盘目录',
	
	'class_grant_warning' => '没有权限新增用户',
	'class_grant_warning1' => '新增用户数已经超出，最多',
	'class_grant_warning2' => '人',
	
	'class_hs_warning' => '数据列数与定义的不符',
	'class_hs_warning1' => '已经存在',
	'class_hs_warning2' => '没有内容',
	
	'class_passport_warning' => '登录服务端管理后台',
	'class_passport_warning1' => '登录云盘',
	'class_passport_warning2' => '登录在线客服',
	
	'class_msgreader_warning' => '成功发送',
	'class_msgreader_warning1' => '转发',
	'class_msgreader_warning2' => '到云盘查看',
	'class_msgreader_warning3' => '名片',
	'class_msgreader_warning4' => '发消息',
	'class_msgreader_warning5' => '群名片',
	'class_msgreader_warning6' => '查看',
	
	'class_PHPExcel_UppeID' => '分组',
	'class_PHPExcel_UserName' => '账号',
	'class_PHPExcel_FcName' => '姓名',
	'class_PHPExcel_UserIco' => '性别(1为男,2为女)',
	'class_PHPExcel_Effigy' => '其他',
	'class_PHPExcel_Tel1' => '手机',
	'class_PHPExcel_Jod' => '职务',
	'class_PHPExcel_UserPaws' => '密码',
	'class_PHPExcel_ItemIndex' => '排序号',
	
	'class_PHPExcel_Col_Ro' => '常用语分组',
	'class_PHPExcel_Col_Form' => '常用语',
	
   'online_list_table_account' => '帐号',
   'online_list_table_user' => '用户',
   'online_list_table_logintime' => '登陆时间',
   'online_list_table_mac' => 'MAC地址',
   'online_list_table_ip' => 'IP地址',
   'online_list_table_version' => '状态',
   'online_list_table_usericoLine1' => '在线',
   'online_list_table_usericoLine2' => '离开',
   'online_list_table_usericoLine3' => '手机在线',
   'field_dept' => '部门',
   'user_list_col_sex' => '性别',
	'user_edit_lb_gender1' => '男',
	'user_edit_lb_gender2' => '女',

   'livechat_message0' => '客服 {name} 不在线，请留言',	
   'livechat_message1' => '客服 {name} 为您服务',
   'livechat_message2' => ' 用户进入',
   'livechat_message3' => '用户长时间未回复，稍后系统将自动结束会话',
   'livechat_message4' => '系统关闭',
   'livechat_message5' => ' 会话转接至 {name}',
   'livechat_message6' => ' 不能和自己聊天',
   'livechat_message7' => '客服',
   'livechat_message8' => '我',
   'livechat_message9' => '未知',
   'livechat_message10' => '未选择',
   'livechat_message11' => '未评估',
   'livechat_message12' => '无价值',
   'livechat_message13' => '有价值',
   'livechat_message14' => '非入口会话',
   'livechat_message15' => '公共会话',
   'livechat_message16' => '在线访客',
   'livechat_message17' => '进入',
   'livechat_message18' => '访客不在线',
   'livechat_message19' => '访客对话中',
   'livechat_message20' => '用户点击了热门问题 {name}',
   
   'register_alert1' => '系统关闭了自由申请帐号功能，请联系管理员。',
   'register_alert2' => '用户账号已存在,请使用另外一个用户账号!',
   'register_alert3' => '账号申请',
   'register_alert4' => '申请了帐号，请您通过审核!',
   'register_alert5' => '账号不能含有中文',
   'register_alert6' => '姓名不能包含特殊字符',
   
   'meeting_alert1' => '人正在',
   'meeting_alert2' => '语音通话',
   'meeting_alert3' => '视频通话',
   'meeting_alert4' => '你正在其他设备通话,点击转至本机.',
   
   'lv_chat_file' => '[文件]',
   'lv_chat_location' => '[位置]',
   'lv_chat_pic' => '[图片]',
   'lv_chat_expression' => '[表情]',
   'lv_chat_video' => '[视频]',
   'lv_chat_voice' => '[语音消息]',
   'lv_chat_link' => '[链接]',
   
    // 文档日志类型
    'type_downloadfile' => '下载文件',
    'type_editfile' => '编辑文件',
    'type_newfile' => '创建文件',
    'type_removefile' => '移动文件',
    'type_viewfile' => '查看文件',
    'type_deletefile' => '删除文件',
    'type_sharefile' => '共享文件',
    'type_login' => '登录'
)
;
?>
