<?php
return array(
	'header_password_dialog' =>'Change Password',
	'header_download' => 'Download Client',
	'header_logout' =>'Exit',
	'header_dropdown' =>'Help',
	'header_register' =>'Register',
	'header_about' =>'About',
	'header_login_btn' =>'Login',
	
	'menu_dir' =>'Directory',
	'menu_history' =>'Recent',
	'menu_doc' =>'Document',
	'menu_img' =>'Picture',
	'menu_create' =>'Create',
	
	'originalTitle' =>'RTC Cloud',
	'icon_folder_public' =>'Public',
	'icon_folder_person' =>'Personal',
	'icon_recent' =>'Recently Updated',
	'icon_office' =>'Document',
	'icon_pic' =>'Picture',
	'icon_music' =>'Music',
	'icon_video' =>'Video',
	'icon_upload' =>'Upload',
	'icon_upload1' => 'Upload Large Files',
	'icon_upload2' => 'Upload the Document File',
	'icon_download' =>'Download',
	'icon_attr' =>'Details',
	'icon_edit' =>'Rename',
	'icon_delete' =>'Delete',
	'icon_share' =>'Share',
	'icon_reload' =>'Refresh',
	'icon_set' =>'Set Permissions',
	'icon_doc_edit' =>'Edit',
	'icon_qrcode' =>'QR Code',
	'icon_save' =>'Save to Cloud Disk',
	'icon_folder_create' =>'New Folder',
	'icon_move' =>'Move to',
	'dropdown-toggle' =>'Sort',
	'icon_time' =>'Sort by Time',
	'icon_az' =>'Sort by Name',
	'icon_thumb' =>'Show Thumbnails',
	'icon_list' =>'Display List',
	'path_node' =>'Directory',
	'upload_title' =>'A file is being transferred',
	'icon_warning' =>'Create a new folder successfully!',
	'icon_warning1' =>'No files yet',
	'icon_warning2' =>'Please click the "Upload" button in the upper left corner to add files',
	'icon_warning3' =>'Search all files',
	'icon_warning4' =>'Enter the file name and press Enter to search',
	
	'pnl_error' =>'Account or password error',
	'pnl_error1' =>'Please log in before proceeding',
	'txt_loginname' =>'Account',
	'txt_loginname_desc' =>'Please enter the account number',
	'txt_password' =>'Password',
	'txt_password_desc' =>'Please enter the password',
	'btn_login' =>'Login',
	
	'pnl_success' =>'Password modification is successful, re-login takes effect. ',
	'old_password' =>'Old password',
	'new_password' =>'New password',
	'confirm_password' =>'Confirm password',
	
	'btn_save' =>'Save',
	'btn_ok' =>'OK',
	'btn_cancel' =>'Cancel',
	'btn_close' =>'Close',
	'btn_cloud_save' =>'Save to Cloud Disk',
	
	'doc_type_name' =>'Type',
	'col_name' =>'Name',
	'path' =>'Path',
	'doc_attribution' =>'Attribution',
	'col_dt_create' =>'Create Time',
	'doc_type_file' =>'File',
	'doc_type_folder' =>'Folder',
	
	'share_url' =>'Link',
	'copy_share_url' =>'Copy Link',
	
	'save_to' =>'Save to',
	'move_to' =>'Move to',
	'doc_move_alert1' =>'Files/Folders',
	'doc_move_alert2' =>'Please select the directory to move to',
	'doc_move_alert3' =>'The target address cannot be the original address',
	
	'txt_folder_name' =>'Directory Name',
	
	'addin_alert' =>'Online documentation plugin is closed',
	
	'set_authority1' =>'Open to whom',
	'set_authority10' =>'Everyone',
	'set_authority11' =>'Specific Members',
	'set_authority12' =>'Only Available to You',
	'set_authority2' =>'The person who obtained the document',
	'set_authority20' =>'Selected Editor',
	'set_authority21' =>'Can Edit',
	'set_title' =>'Add members who can edit the document (selected members have editing rights, other members only have viewing rights)',
	'set_title1' =>'Set a specific member',
	'set_userkey' =>'Enter account number or name',
	'set_addMemberByInput' =>'Add Member',
	'set_edit' =>'Edit',
	'set_name' =>'Name',
	'set_account' =>'Account',
	'set_authority3' => 'Notification',
	'set_authority30' => 'Ignored',
	'set_authority31' => 'Notification',
    'menu_sub_ptp_file' => 'Cloud Disk Document',
    'menu_sub_group_file' => 'Group file',
    'menu_sub_leave_file' => 'Offline file',
    'menu_sub_file_alert1' => 'I updated',
	'menu_sub_file_alert2' => '[System automatically sends]',
	
	'doceditor_title' =>'Online document',
	'doceditor_warning' =>'Currently it can only be viewed, you can get more operation permissions after logging in',
	'doceditor_read' =>'(Read Only)',
	'doceditor_login_btn' =>'Login',
	'doceditor_doc_set' =>'Permission',
	'doceditor_doc_col' =>'Collection',
	'doceditor_doc_share' =>'Share',
	'doceditor_logout_btn' =>'Exit',
	'doceditor_file_empty' =>'File does not exist',
	'doceditor_file_empty1' =>'You do not have permission to view',
	'doceditor_edited_document' =>'Document Edited',
	
	'onlinefile_warning' =>'The account does not exist, verification failed!',
	'onlinefile_warning1' =>'The account is disabled, verification failed!',
	'onlinefile_warning2' =>'The account is not logged in, the verification failed',
	'onlinefile_warning3' =>'Verification failed, token is invalid',
	'onlinefile_icon_recent' =>'Recent',
	'onlinefile_icon_folder_person' =>'I created it',
	'onlinefile_icon_folder_public' =>'Share me',
	'onlinefile_doc_create1' =>'New document',
	'onlinefile_doc_create2' =>'New form',
	
	'col_chk_notall' =>'Not all selected',
	'col_chk_all' =>'Select all',
	'folder_nav_box' =>'Save location: personal document',
	'btn_return' =>'Return to the previous level',
	
	'download_title1' => 'Download',
	'download_title2' => 'backend management',
	'download_title3' => 'Development documentation',
	'download_title4' => 'National Unified Service Hotline',
	'download_title5' => 'official website',
	'download_title6' => 'current location',
	'download_title7' => 'PC version - client',
	'download_title8' => 'System environment WinNT/2K/XP/vista/7/8/10/11<br />/server 2003/server 2008/server 2012<br />/server 2019/server 2022<br /> Version: 10.9<br/>Size: 45 M',
	'download_title9' => 'System environment: Android<br/>Version: All<br/>Size: 42.8 M<br/>',
	'download_title10' => 'System environment: IOS<br/>Version: All<br/>Size: 52.6 M',
	'download_title11' => 'Scan to download mobile version',
	'download_title12' => 'When logging in on the PC:<br/>Click on "Network"; Enter<br/>IP/domain name/computer name.',
	'download_title13' => 'When logging in on the mobile end: click "Network"; Enter the external IP/domain name <br/>Explanation: The iOS version can be downloaded from the app store, search for "好奇鸟"; ',
	'download_title14' => 'Related downloads',
	'download_title15' => 'After sales service',
	'download_title16' => '1、 When special mobile installation packages are needed, please contact us, such as setting the default server IP. The advantage of this is that employees do not need to be told what the server IP is, and can simply enter their username and password to log in. <br />2、 Regardless of whether the product is paid or not, if you encounter technical problems during use, please contact us. <br />3、 If you need to integrate with existing management systems (such as SMS systems, enterprise email, ERP, OA, CRM), as developing the Curiosity Bird plugin requires certain professional requirements, please contact us if you have such a need. <br />4、 If you need to import employee information from existing systems (such as OA) into the Curiosity Bird system, please contact us. <br />',
	'download_title17' => 'RTC Cloud Drive User Manual.docx',
	'download_title18' => 'RTC Introduction.ppt',
	'download_title19' => '<em></em>Open the APP login page<br><em></em>Select the external network and enter the domain name:',
	'download_title20' => 'Click to copy domain name',
);
?>